- .changeset/fast-keys-joke.md
- .changeset/plenty-cars-jam.md
- .github/workflows/reusable-test.yaml
- docker-compose.registry.yaml
- examples/oapp/.eslintignore
- examples/oapp/.prettierignore
- examples/oapp/README.md
- examples/oapp/package.json
- examples/oft/.eslintignore
- examples/oft/.prettierignore
- examples/oft/README.md
- examples/oft/package.json
- packages/create-lz-oapp/src/config.ts
- packages/create-lz-oapp/src/utilities/cloning.ts
- tests-user/tests/create-lz-oapp.bats
- Enable user tests for `create-lz-oapp`
- Update the repository URL to the https one (since we are public it's easier than struggling with SSH)
- Fix a typo is a test case
- Use the medium runner for the user tests since they grew after this change
- Fix `compile` and `test` scripts for examples - they were not playing nice with `npm` that requires `npm run compile` instead of `npm compile`
- Show a bit more output to the user if the cloning fails
> 🪚 Enable user tests for create-lz-oapp

- .changeset/mighty-gifts-own.md
- packages/devtools-evm-hardhat/package.json
- packages/devtools-evm/package.json
- packages/devtools/package.json
- packages/io-devtools/package.json
- packages/omnicounter-devtools-evm/package.json
- packages/omnicounter-devtools/package.json
- packages/protocol-devtools-evm/package.json
- packages/protocol-devtools/package.json
- packages/test-devtools-evm-foundry/package.json
- packages/test-devtools-evm-hardhat/package.json
- packages/test-devtools/package.json
- packages/toolbox-foundry/package.json
- packages/toolbox-hardhat/package.json
- packages/ua-devtools-evm-hardhat/package.json
- packages/ua-devtools-evm/package.json
- packages/ua-devtools/package.json
- Set the package access to `public`
- Bump our very first minor version, `0.1.0`
**IMPORTANT** The versioning PR might try to bump the versions of dependents to `1.0.0` due to how strict semver works. In strict semver, when we are in `0.X.X` range, patch bump is equivalent to minor bump and minor bump is equivalent to major bump. Once the versioning PR is ready, we might need to adjust this **so please once this is merge, take your time reviewing the versioning**
> 🚀 Publish packages publicly

- .github/workflows/actions/setup-build-cache/action.yaml
- Updating the version of `actions/cache` to `v4` since Node 16 actions have been deprecated
> 🧹 Update cache action version

- .github/workflows/reusable-test.yaml
- docker-compose.registry.yaml
- packages/protocol-devtools-evm/package.json
- packages/protocol-devtools-evm/test/uln302/sdk.test.ts
- Make the `Uln302` SDK tests a bit more straightforward; reduce the number of test runs to 20 not to spend 20 minutes on the test pipeline
- Move the GitHub-specific environment variables out of the compose file for user tests
> 🚧 Loose ends in tests

- .changeset/witty-elephants-sing.md
- packages/devtools/package.json
- packages/devtools/src/common/promise.ts
- packages/devtools/test/common/promise.test.ts
- pnpm-lock.yaml
- After exploring the options of retrying failed calls on several levels (SDK, configuration and RPC provider), I created composable retry functionality that can be used on all three levels - yet after seeing that retrying on the provider level is very error-prone, I think we should retry on the configuration level.
- The way the code is structured, allows us to create retry strategies that will for example bump the gas limit on transactions if we need to
```typescript
// This is not a financial advice
//
// This strategy will be bumping the. `gasLimit` on a transaction to infinity
// exponentially by factor of 2
//
// (Being a sketch, it does not account for gasLimit being a string or being 0)
const strategy: RetryStrategy<OmniTransaction> = (attempt, error, [previousTransaction]) => [{ …
```
> 🗞️ Retry helpers

- .changeset/metal-trains-carry.md
- packages/devtools-evm-hardhat/src/cli.ts
- packages/devtools/src/common/index.ts
- packages/devtools/src/common/strings.ts
- packages/io-devtools/src/stdio/logger.ts
- Miniscule code reorganization needed for `lz:deploy` task - moving some schemas around, exporting `isLogLevel` function and removing `CommaSeparatedValuesSchema` in favor of a transformation function that splits a CSV string into individual values, discarding any whitespace
> 🧹 Preparation work for lz:deploy task

- DEVELOPMENT.md
- turbo.json
- Enable `turbo` [strict environment mode](https://turbo.build/repo/docs/reference/configuration#globalpassthroughenv) - this means that any task executed by running `turbo` will only receive the environment variables that are made available to it. This gets rid of the lint warnings cased by `turbo/no-undeclared-env-vars` ESLint rule
> 🧹 Use turbo strict environment mode

- .changeset/long-dolphins-press.md
- packages/ua-devtools-evm/src/oapp/sdk.ts
- packages/ua-devtools/src/oapp/config.ts
- packages/ua-devtools/src/oapp/schema.ts
- packages/ua-devtools/src/oapp/types.ts
- tests/ua-devtools-evm-hardhat-test/test/oapp/config.test.ts
- Fixing configureEnforcedOptions logic to collect EnforcedOptions[] by OApp before executing the transaction. This results in fewer transactions to configure enforced options.
>  🪲Fixing configureEnforcedOptions

- .husky/pre-commit
- After removing the `pnpm/action-setup` in favor of `corepack enable`, the `lint-staged` command [failed to execute on the `main` branch](https://github.com/LayerZero-Labs/devtools/actions/runs/7804238907/job/21287844498). The fix here is to use the `npx` executable instead of the `pnpm` one
> 🪲 Fix lint-staged command

- package.json
- Changed `pnpm` to `npx` for `lint-staged` commands to fix pipeline failures after removing deprecated `pnpm/action-setup`
> 🪲 Fix lint staged commands

- .github/workflows/actions/setup-environment/action.yaml
- .husky/pre-commit
- package.json
- Revert removal of `pnpm/action-setup` that caused `lint-staged` to fail in the publish step. Further investigation as well as a better testing setup is needed since `main` is now failing
> 🪲 Revert pipeline updates

- .changeset/three-pigs-give.md
- packages/build-lz-options/src/components/outputOptions.tsx
- packages/build-lz-options/src/index.tsx
- packages/build-lz-options/src/types.ts
Warn the user if:
* There is no lzReceive option.  compose gas does not count towards lzReceive gas for the default ExecutorFeeLib implementation.
* lzReceive option is specified, but with 0 destination gas.
> 🗞️ warn user if no lzReceive gas is supplied

- README.md
- Since `lz:oapp:config:init` is still feature-flagged, it's best to remove it from the documentation
> 🧹 Remove lz:oapp:config:init from docs

- .changeset/khaki-garlics-run.md
- packages/devtools-evm-hardhat/src/tasks/deploy.ts
- tests/devtools-evm-hardhat-test/test/task/deploy.test.ts
- To make the UX even better, we'll run hardhat's `TASK_COMPILE` before deploying contracts in `lz:deploy`. That way the only thing a person needs to do is set a `MNEMONIC`/`PRIVATE_KEY` and run `npx hardhat lz:deploy`
> 🗞️ Compile project before running lz:deploy

- examples/oapp/deploy/MyOApp.ts
- examples/oapp/hardhat.config.ts
- examples/oapp/layerzero.config.ts
- examples/oft/deploy/MyOFT.ts
- examples/oft/hardhat.config.ts
- examples/oft/layerzero.config.ts
- Fix wrong `eid` for Sepolia EndpointV2 deployments in our examples
- Fix deploy script tag for `MyOFT`
> 🪲 Fix typos in example configurations

- .changeset/wild-brooms-tell.md
- packages/build-lz-options/README.md
Just a small update to README.md which explains the one warning emitted by the tool so far.
> :broom: update build lz options README.md with warning information

- packages/devtools/src/common/assertion.ts
- packages/devtools/src/common/bytes.ts
- packages/devtools/src/common/promise.ts
- packages/devtools/src/transactions/signer.ts
These are mostly cosmetic changes to avoid warnings.
> :broom: devtools;  fix JSDoc names, spelling, typing, etc.

- tests/ua-devtools-evm-hardhat-test/test/__utils__/oapp.ts
There are a few facets of OAppTestConfig which are mistyped as number instead of bigint.
> :beetle: OAppTestConfig typing number -> bigint where appropriate

- .changeset/good-foxes-crash.md
- packages/create-lz-oapp/src/components/error.tsx
- packages/create-lz-oapp/src/components/setup.tsx
- Add a box with next steps after the `create-lz-oapp` flow is done
- Modify the colors of the error next next steps to match this one (swap green comments for white comments)
> 🗞️ Add next steps box to create-lz-oapp

- DEVELOPMENT.md
- docker-compose.yaml
- packages/io-devtools/src/config/loading.ts
- packages/ua-devtools-evm-hardhat/src/utils/taskHelpers.ts
- tests/ua-devtools-evm-hardhat-test/test/task/oapp/__snapshots__/wire.test.ts.snap
- tests/ua-devtools-evm-hardhat-test/test/task/oapp/wire.test.ts
- Simplify the process of snapshot updating by modifying all the logic that worked with absolute filesystem paths. The filesystem paths are visible in verbose/debug logs but will not appear in user errors. The nice side-effect of this is the fact that any errors will display whatever path the user passed in, not the absolute path used
> 🧹 Snapshot improvements

- tests-user/tests/create-lz-oapp.bats
- Change the user tests to deploy Sepolia rather than Fuji since fuji RPC is unstable
> 🪲 Fuji RPC is down, change it in the user tests

- Dockerfile
- Rebuild native bindings in the container to get rid of an annoying issues with `bigint-buffer`
> 🪲 Rebuild modules to get rid of missing bindings issue

- .changeset/polite-jeans-clap.md
- examples/oapp/package.json
- examples/oft/package.json
- packages/create-lz-oapp/src/config.ts
- Lock versions of ethers & @openzeppelin/contracts in examples to prevent installation issues (having to use `npm install --force`)
- List `pnpm` as the first option in `create-lz-oapp` since we recommend it
> 🧹 Lock versions of ethers & @openzeppelin/contracts in examples

- .changeset/shiny-years-join.md
- packages/export-deployments/src/generator/typescript/generate.ts
- packages/export-deployments/src/generator/typescript/typescript.ts
- tests/export-deployments-test/test/export.test.ts
- `viem` relies on ABIs defined as constant expressions, without type widening, for ABI type inferrence. This PR adds `as const` to ABI exports to better support `viem` in all its adventures
> 🪲 Export ABIs as constants for better viem integration

- .changeset/fast-suits-rhyme.md
- packages/ua-devtools/src/oapp/config.ts
- tests/ua-devtools-evm-hardhat-test/test/oapp/config.test.ts
**In this PR**
- Fixing `lz:oapp:wire` task to lock in default send and receive libraries.
> 🪲 Fixing wire task to lock in default send and receive libraries

- .changeset/proud-icons-drop.md
- package.json
- packages/devtools-evm-hardhat/package.json
- packages/devtools-evm-hardhat/src/tasks/transactions/subtask.sign-and-send.ts
- packages/devtools-evm-hardhat/src/transactions/signer.ts
- packages/devtools-evm-hardhat/src/type-extensions.ts
- packages/devtools-evm/package.json
- packages/devtools-evm/src/signer/sdk.ts
- packages/devtools-evm/test/signer/sdk.test.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/index.ts
- pnpm-lock.yaml
Allows users to optionally define gnosis safe settings in `hardhat.config.ts`. If defined, then a gnosis signer will be used.  If not defined, a normal ethers signer will be used.
`@safe-global/protocol-kit@1.3.0` is the newest ethers V5 compatible version, so we rely on this version and the corresponding versions for dependencies.
> 🗞️  gnosis safe signer support

- examples/oapp/package.json
- examples/oft/package.json
- Adding resolutions for `@openzeppelin/contracts-upgradeable` to example projects since NPM installation in the user tests started failing because of a peer dependency requirement not being met
> 🪲 Add resolutions to examples

- packages/verify-contract/package.json
- Adding public access configuration to `@layerzerolabs/verify-contract`
> 🪲 Make verify-contract package public again

- .changeset/lucky-pillows-hunt.md
- packages/verify-contract/src/cli.ts
- packages/verify-contract/src/common/abi.ts
- Remove `any` types in favour of interfaces for the `@layerzerolabs/verify-contract` package
> 🧹 Fix lint warnings for verify-contract

- .changeset/stupid-falcons-hope.md
- packages/devtools-evm-hardhat/src/tasks/deploy.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/index.ts
- tests/ua-devtools-evm-hardhat-test/test/task/oapp/wire.test.ts
- Set correct error exit codes when hardhat tasks fail. This is necessary to be able to correctly detect the state of the task on the command line since in case of error we don't want to throw or exit (for composability reasons) to be able to pass the exact error state to the consumer [*]
[*] JavaScript errors are not typed so for us to be able to pass a typed information about the error state we would need to resort to a bit more advanced techniques like [`Either`](https://itnext.io/either-monad-a-functional-approach-to-error-handling-in-js-ffdc2917ab2) which we can do but not as of yet
> 🧹 Set correct exit codes for failed hardhat tasks

- .changeset/cool-spiders-ring.md
- packages/ua-devtools-evm-hardhat/package.json
- packages/ua-devtools-evm-hardhat/src/oapp/typescript/typescript.ts
- pnpm-lock.yaml
- Use the existing retry logic when generating LayerZero configs
- Don't include `typescript` in the bundle, move it to `dependencies` instead
> 🧹 Update retry logic & exclude typescript from the bundle

- .changeset/metal-rats-fix.md
- examples/oapp/package.json
- examples/oft/package.json
- package.json
- packages/devtools-evm-hardhat/package.json
- packages/io-devtools/test/language/plurals.test.ts
- packages/toolbox-hardhat/package.json
- packages/ua-devtools-evm-hardhat/package.json
- pnpm-lock.yaml
- tests/devtools-evm-hardhat-test/package.json
- tests/export-deployments-test/package.json
- tests/ua-devtools-evm-hardhat-test/package.json
- tests/ua-devtools-evm-hardhat-v1-test/package.json
- [Our PR](https://github.com/wighawag/hardhat-deploy/pull/514) to replace `zksync-web3` with `zksync-ethers` has been merged so we can now update `hardhat-deploy`
> 🧹 Update hardhat-deploy

- .github/workflows/on-develop.yaml
- .github/workflows/reusable-test.yaml
- Fixing an issue with workflows from forks not being run at all. The problem is that pull requests from forks don't trigger a `push` github event ([see here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull-request-events-for-forked-repositories)) so these workflows would never get triggered and the button [mentioned here](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork) does not appear at all
- To allow an arbitrary workflow run on a branch for which there is no PR (some work in progress branch), `workflow_dispatch` trigger has been added as well
> 🪲 Workflow triggers

- .changeset/dry-humans-smash.md
- packages/ua-devtools/src/oapp/schema.ts
- packages/ua-devtools/src/oapp/types.ts
- `value` property is not required and has been made optional in `ExecutorComposeOption` and `ExecutorLzReceiveOption`
> 🧹 Make value attribute optional in enforced options

- .changeset/popular-peaches-accept.md
- packages/ua-devtools/src/oapp/config.ts
- packages/ua-devtools/src/oapp/types.ts
- Make `executorConfig` and `ulnConfig` optional for OApp configuration
> 🧹 Make executorConfig and ulnConfig optional

- .eslintignore
- package.json
- Make `lint-staged` more explicit when it comes to file extensions so we don't need to pile the ignored files in `.eslintignore`
> 🧹 Make lint-staged more explicit

- .changeset/lucky-garlics-end.md
- Dockerfile
- package.json
- patches/bigint-buffer@1.1.5.patch
- pnpm-lock.yaml
- Silencing the `bigint-buffer` warning (safe since it's not being used) warning by patching the package
> 🧹 Silence the bigint-buffer warning

- .changeset/mighty-tigers-beam.md
- .changeset/three-bobcats-hear.md
- packages/devtools/src/transactions/signer.ts
- packages/devtools/src/transactions/utils.ts
- packages/devtools/test/transactions/signer.test.ts
- packages/devtools/test/transactions/utils.test.ts
- tests/ua-devtools-evm-hardhat-test/test/oapp/config.test.ts
- tests/ua-devtools-evm-hardhat-test/test/task/oapp/wire.test.ts
- Adjusting `createSignAndSend` to group the transactions by `eid` and sign these groups in parallel. This makes testing a bit more cumbersome because in general the order of the resulting successful transactions does not match the order of input transactions, the order is only enforced per-group
- Adding `groupTransactionsByEid` utility
> 🗞️ Sign transactions on different chains in parallel

- .changeset/tasty-cougars-tie.md
- packages/protocol-devtools-evm/src/endpointv2/sdk.ts
- packages/protocol-devtools-evm/src/uln302/sdk.ts
- packages/protocol-devtools-evm/test/uln302/sdk.test.ts
- packages/protocol-devtools/src/endpointv2/types.ts
- packages/protocol-devtools/src/uln302/types.ts
- packages/ua-devtools/src/oapp/types.ts
- Creating a new type for Uln302 configuration user input - `Uln302UlnUserConfig`. This type makes some of the properties optional in order to simplify user configuration
> 🧹 Make properties of Uln302 config optional

- .changeset/mean-chicken-tell.md
- packages/protocol-devtools/src/uln302/schema.ts
- packages/ua-devtools/src/oapp/schema.ts
- Adjust validation schemas after the configuration types have been made less strict
> 🪲 Adjust schemas after making the ULN config types optional

- .changeset/hungry-scissors-report.md
- Dockerfile
- packages/devtools/package.json
- packages/devtools/src/docker/compose.ts
- packages/devtools/src/docker/index.ts
- packages/devtools/src/docker/types.ts
- packages/devtools/src/index.ts
- packages/devtools/test/docker/__snapshots__/compose.test.ts.snap
- packages/devtools/test/docker/compose.test.ts
- pnpm-lock.yaml
- Adding generic code generation capabilities for `docker-compose.yaml` files. These will eventually support a dynamic containerized local development environment. The types have been generated from a JSON schema [here](https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json) and pruned a bit
> 🗞️ Add docker compose spec generation functionality

- .changeset/eight-worms-yawn.md
- packages/verify-contract/src/common/url.ts
Update the default url mappings for:
metis
mantle
scroll
> 🧹 Add new urls in verify-contract for mantle, metis, and scroll

- .changeset/brown-ducks-poke.md
- .changeset/happy-cars-glow.md
- packages/devtools-evm/src/omnigraph/sdk.ts
- packages/devtools/src/common/promise.ts
- packages/devtools/test/common/promise.test.ts
- packages/ua-devtools-evm/src/oapp/sdk.ts
- Improve logging for the `OApp` SDK - wrap the original errors with more descriptive ones
- Add `tapError` (for error logging) and `mapError` (for error mapping) functions to `devtools`
> 🧹 Better logging and errors [1/N]

- .changeset/pretty-houses-pay.md
- packages/verify-contract/src/common/url.ts
Add default scan-apis for:
mode
fraxtal
> 🧹 Add default verify urls for fraxtal and mode

- .changeset/tall-turtles-thank.md
- packages/verify-contract/src/common/url.ts
Add a default scan api for:
etherlink
> 🧹  Add etherlink scan url to verify-contract package

- packages/build-lz-options/jest.config.js
- packages/create-lz-oapp/jest.config.js
- packages/devtools-evm-hardhat/jest.config.js
- packages/devtools-evm/jest.config.js
- packages/devtools/jest.config.js
- packages/export-deployments/jest.config.js
- packages/io-devtools/jest.config.js
- packages/omnicounter-devtools-evm/jest.config.js
- packages/omnicounter-devtools/jest.config.js
- packages/protocol-devtools-evm/jest.config.js
- packages/protocol-devtools/jest.config.js
- packages/toolbox-hardhat/jest.config.js
- packages/ua-devtools-evm-hardhat/jest.config.js
- packages/ua-devtools-evm/jest.config.js
- packages/ua-devtools/jest.config.js
- packages/verify-contract/jest.config.js
- tests/devtools-evm-hardhat-test/jest.config.js
- tests/devtools-evm-test/jest.config.js
- tests/export-deployments-test/jest.config.js
- tests/ua-devtools-evm-hardhat-test/jest.config.js
- tests/ua-devtools-evm-hardhat-v1-test/jest.config.js
- A side-effect of one of the tasks - adding `github-actions` reporter to `jest` for easier test failure navigation. Read more about [`github-actions` reporter here](https://jestjs.io/docs/configuration#github-actions-reporter)
At some point, we might isolate the default `jest` config to stay a bit DRY and turn it from a `.js` into a `.ts` file (help welcome).
> 🧹 Add github actions reporter to jest

- .changeset/witty-toes-compare.md
- packages/devtools-evm-hardhat/src/simulation/types.ts
- packages/devtools-evm-hardhat/src/type-extensions.ts
- packages/devtools-evm/src/simulation/anvil.ts
- packages/devtools/src/docker/types.ts
- Adding types for configuring the localnet (a.k.a. _simulation_ as suggested by @kushdave95)
- Adding `state` option to `AnvilOptions`
- Adding names for some of the compose types to be a bit DRY
This PR exists only to reduce the size of the ones to come, there's a lot of code related to generation of the `docker-compose.yaml` files for simulations so every file that can be split off that chunk is a good file.
> 🗞️ Bits and pieces of types and configuration for localnet [3/N]

- .changeset/chilly-glasses-beam.md
- .changeset/perfect-monkeys-cross.md
- .changeset/violet-hornets-prove.md
- packages/devtools-evm-hardhat/jest.config.js
- packages/devtools-evm-hardhat/jest.transformer.raw.js
- packages/devtools-evm-hardhat/src/simulation/assets/Dockerfile.conf
- packages/devtools-evm-hardhat/src/simulation/assets/index.ts
- packages/devtools-evm-hardhat/src/simulation/assets/nginx.conf
- packages/devtools-evm-hardhat/src/simulation/compose.ts
- packages/devtools-evm-hardhat/src/simulation/index.ts
- packages/devtools-evm-hardhat/test/simulation/__snapshots__/compose.test.ts.snap
- packages/devtools-evm-hardhat/test/simulation/compose.test.ts
- packages/devtools-evm-hardhat/test/simulation/config.test.ts
- packages/devtools-evm-hardhat/tsconfig.json
- packages/devtools-evm-hardhat/tsup.config.ts
- packages/devtools-evm-hardhat/types/conf.d.ts
- packages/test-devtools/package.json
- packages/test-devtools/src/arbitraries.ts
- packages/test-devtools/src/constants.ts
- pnpm-lock.yaml
- Adding utilities & assets required to create a compose spec consisting of anvil-based EVM nodes & an nginx-based RPC proxy
- The proxy is added to avoid exposing N networking ports from the forked nodes - instead, these stay internal to the compose stack and the client needs to use the proxy to get to them
- In order to avoid copying files, the `Dockerfile` and `nginx.conf` file are imported as strings to the code itself using `raw`/`text` loaders. This required a `raw` loader for `jest` (instead of installing a package [with three outdated lines of code](https://github.com/keplersj/jest-raw-loader/blob/master/index.js) I just added a local version of the transformer - `jest.transformer.raw.js`) and a `text` loader for `esbuild`. In addition to this a type definition was required so …
> 🗞️ Add docker compose spec generation utilities for localnet [4/N]

- .changeset/fair-cars-tie.md
- examples/oapp/hardhat.config.ts
- examples/oft/hardhat.config.ts
- Take RPC URLs from the environment in our examples and provide defaults only if they don't exist
This is introduced to improve the testing of the examples themselves. If we want to introduce any E2E tests for the examples, we need good-quality RPCs that will not cause any flakiness. At the same time, we want to keep the examples usable out of the box for the users.
The solution for this is to be able to inject private RPCs while testing with the CI/CD pipeline using environment variables. Users can still default to the predefined RPCs (or modify their hardhat configs to their liking).
This PR will play an important role when testing the simulation flow - this flow requires forkable RPCs and as such cannot be tested on our local hardhat nodes.
> 🧹 Take RPC URLs from environment in examples

- packages/devtools-evm-hardhat/package.json
- packages/devtools-evm-hardhat/tsconfig.build.json
- packages/devtools-evm/package.json
- packages/devtools-evm/tsconfig.build.json
- packages/protocol-devtools-evm/package.json
- packages/protocol-devtools-evm/tsconfig.build.json
- Removing `tsconfig.build.json` files that were previously used to filter build output from packages and did not get deleted. These are no longer necessary as `tsup` will only build the source files specified in `tsup.config.ts`
> 🧹 Remove unused build tsconfigs

- .changeset/early-moose-talk.md
- .changeset/thirty-maps-train.md
- packages/ua-devtools/src/lzapp/config.ts
- packages/ua-devtools/src/oapp/config.ts
- tests/ua-devtools-evm-hardhat-test/test/oapp/config.test.ts
- tests/ua-devtools-evm-hardhat-v1-test/test/lzapp/config.test.ts
- Add feature-flagged parallel execution capability to OApp / LzApp configuration. This is enabled by setting `LZ_ENABLE_EXPERIMENTAL_PARALLEL_EXECUTION` environment variable to a truth value (e.g. `'1'` or `'true'` or `'ohboi'`). The reason this has been feature flagged is the fact that when using public RPCs, we might get rate-limited and without a proper retry logic in place for SDKs, this might make our tool unusable.
- We might decide later to pull this one level up and allow the `LzAppConfigurator` and `OAppConfigurator` to accept an applicative (`parallel` or `sequence`)
> 🗞️ Add opt-in parallel configuration execution

- .changeset/dull-bananas-kiss.md
- packages/devtools-evm-hardhat/src/simulation/config.ts
- packages/devtools-evm-hardhat/test/simulation/config.test.ts
- Adjusting the simulation config for `anvil` 
- Pointing `anvil` to `0.0.0.0:8545` since it's running in a docker container
- Making `getHardhatNetworkOverrides` return a full, resolved hardhat network config. The original intention was to store the output of this function in an e.g. `.json` file and merge it with `hardhat.config.ts` at runtime. This meant that it could not contain any sensitive information since a user mistake (like accidentally pushing this file to a public repository) would lead to the loss of private data. The new idea is to call this function at runtime, without storing anything on the filesystem. The output of this function will be used to update the network configuration in hardhat without any intermediate steps.
> 🗞️ Adjust simulation config logic for anvil [7/N]

- .changeset/wet-buckets-flash.md
- packages/protocol-devtools-evm/src/dvn/sdk.ts
- packages/protocol-devtools-evm/src/executor/sdk.ts
- packages/protocol-devtools-evm/src/priceFeed/sdk.ts
- packages/protocol-devtools-evm/src/uln302/sdk.ts
- Replace `printRecord` with `printJson` when adding descriptions to transactions. `printRecord` is meant to be used directly with stdout and it's not suitable for serialization. Also it's much slower than `printJson`, slowing down some of the tests to about 2 minutes
> 🪲 Don't use printRecord in SDKs

- packages/devtools-evm-hardhat/test/simulation/compose.test.ts
- packages/devtools/test/docker/__snapshots__/compose.test.ts.snap
- packages/devtools/test/docker/compose.test.ts
- In our `Dockerfile`, we always install the newest version of `docker`. In the recent update, the logic for `docker compose config` has changed and no longer supports a compose file with no services. The test has been updated to include an empty `services` object
- Small speedup for other compose tests - the validation logic is only ran once
- More assertions for the compose tests to see the details of an error from `stderr` if something goes wrong, instead of just the error code
> 🪲 Fix tests that use docker compose

- .changeset/forty-panthers-breathe.md
- packages/devtools-evm-hardhat/src/cli.ts
- packages/devtools-evm-hardhat/src/tasks/transactions/subtask.sign-and-send.ts
- packages/devtools-evm-hardhat/test/cli.test.ts
- packages/devtools-evm/src/address.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/index.ts
- tests/ua-devtools-evm-hardhat-test/test/task/oapp/wire.test.ts
- Add `--safe` CLI argument for signing transactions with gnosis safe
- Add `--signer` CLI argument for selecting the index or address of a signer
> 🗞️ Add --safe and --signer CLI arguments to the wire task

- .changeset/nasty-ligers-hunt.md
- packages/verify-contract/src/common/url.ts
aded a default verify contract url for: 
blast
> 🧹 Add default verify url for blast network

- packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/enforced.opts.get.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/peers.get.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/index.ts
- packages/ua-devtools-evm-hardhat/src/utils/taskHelpers.ts
- Changing the API of `validateAndTransformOappConfig` so that the config loader is passed as an argument. Config loader is responsible for turning a path to a config file into a strongly typed config, based on the schema it uses.
This is the first step towards making custom configurations easier to accomplish (or more precisely, easier to represent in TypeScript). It creates a bit of extra code on the consumer side that in return allows for more flexibility - custom loader can be created for custom config schemas.
In the first use case, this will be used to add ownership transfer functionality for which we'll use a custom schema and an SDK mixin.
> 🧹 Custom configuration: Pass configLoader to config validator [1/N]

- .changeset/selfish-ways-explode.md
- packages/io-devtools/src/config/loading.ts
- packages/io-devtools/test/config/__snapshots__/loading.test.ts.snap
- packages/io-devtools/test/config/loading.test.ts
- To allow more flexibility when defining configs, we will accept the `layerzero.config.ts` / `layerzero.config.js` to export a function (synchronous or asynchronous) that, when executed, will return the config itself. This allows users to query any information before constructing the config (e.g. on-chain information)
This is very useful when it comes to custom configs - we can now query for information that we'd otherwise need to get and hardcode (e.g. contract addresses).
```typescript
// layerzero.config.ts
import hre from 'hardhat';
// We'll need a per-network HardhatRuntimeEnvironment to access its deployments
const getEnvironment = createGetHreByEid(hre)
export default async () => {
// We'll create a fantom HardhatRuntimeEnvironment
const fantomEnvironment = await …
```
> 🗞️ Configuration functions

- .changeset/new-lies-buy.md
- packages/devtools/src/omnigraph/types.ts
- packages/ua-devtools-evm/src/index.ts
- packages/ua-devtools-evm/src/oapp/sdk.ts
- packages/ua-devtools-evm/src/ownable/factory.ts
- packages/ua-devtools-evm/src/ownable/index.ts
- packages/ua-devtools-evm/src/ownable/mixin.ts
- packages/ua-devtools-evm/test/ownable/mixin.test.ts
- packages/ua-devtools/src/index.ts
- packages/ua-devtools/src/oapp/types.ts
- packages/ua-devtools/src/ownable/config.ts
- packages/ua-devtools/src/ownable/index.ts
- packages/ua-devtools/src/ownable/schema.ts
- packages/ua-devtools/src/ownable/types.ts
- tests/ua-devtools-evm-hardhat-test/test/ownable/config.test.ts
- Adding `OwnableMixin`, a collection of methods that can be mixed in to a class instance / class prototype to add `Ownable` SDk functionality
- Adding `createOwnableFactory` to wrap an arbitrary `OmniSDK` with `OwnableMixin`
- Adding `configureOwnable` function to configure ownership
At this point, the amount of very convoluted code that makes TypeScript happy about mixins does not justify the extra three literal methods on `OApp` that proxy the calls to `OwnableMixin`. Less repetitive solutions can be achieved with class decorators but the support is still experimental and could break TypeScript for lots of client projects - see here https://www.typescriptlang.org/docs/handbook/mixins.html.
On the other hand, having `OwnableMixin` out of the `OApp` prototype chain allows us to mixt it …
> 🗞️ OwnableMixin + OApp = 🆒 [1/N]

- .changeset/tiny-seahorses-suffer.md
- packages/protocol-devtools/src/dvn/types.ts
- packages/protocol-devtools/src/endpointv2/types.ts
- packages/protocol-devtools/src/executor/types.ts
- packages/protocol-devtools/src/priceFeed/types.ts
- packages/protocol-devtools/src/uln302/types.ts
- packages/ua-devtools-evm-hardhat/src/oapp/schema.ts
- packages/ua-devtools-evm-hardhat/src/oapp/types.ts
- packages/ua-devtools/src/lzapp/types.ts
- packages/ua-devtools/src/oapp/schema.ts
- packages/ua-devtools/src/oapp/types.ts
- Type cleanup - reuse `OmniSDKFactory` for all the SDK factories out there
- Add `OAppNodeConfig` - since `OApp` is now ownable, its graph can contain ownership config. We will most probably not configure ownership as part of the wire task (TBD @TRileySchwarz) and keep it as a separate step to match the typical development workflow
> 🗞️ OwnableMixin + OApp = 🆒 [2/N]

- package.json
- To easily wipe all ignored files (builds, artifacts, caches, `node_modules`, everything) we add a `prune` command. This is an addition to the exiting `clean` commands that don't touch `node_modules` (and need to be kept in sync with the package settings so that they truly clean everything)
> 🧹 Add prune script to wipe everything

- .changeset/large-trains-change.md
- examples/oapp/layerzero.config.ts
- examples/oft/layerzero.config.ts
- packages/devtools/src/types.ts
- packages/devtools/test/omnigraph/types.test.ts
- packages/toolbox-hardhat/types/index.d.ts
- packages/ua-devtools-evm-hardhat/src/index.ts
- Re-export types useful for creating strongly-types configs from `toolbox-hardhat`
- Fix a tiny beauty issue with `WithOptionals` type - if passed a union type, e.g. `string | undefined`, it would consider it as non-optional. This meant that once types were added to the example configs, everything was red since the (actually optional) `config` property was considered non-optional
- Fix a missing export in `ua-devtools-evm-hardhat`
> 🧹 Re-export useful types from toolbox-hardhat; Fix small type & export issues

- .github/workflows/reusable-publish-docker.yaml
- Adding a github workflow that builds a base image with everything we need to run our test suite. The idea is to reduce the testing pipeline runtime by using a prebuilt image rather than rebuilding one on every run
- This workflow is for now only available as a manual workflow, we can enable it on `main` if everything goes well after manual testing
> 🧹 Build base development image

- .github/workflows/reusable-publish-docker.yaml
- Removing the matrix strategy from docker build. Turns out that the `docker/build-push-action` does not play nice with parallel builds and the last job to complete will always override any previous build artifacts. In order to keep the job parallel, we'd need to make it much more complex as [per the documentation](https://docs.docker.com/build/ci/github-actions/multi-platform/) - [issue here](https://github.com/docker/build-push-action/issues/1051). Since this job does not have impact on our pipeline duration, we simply build them in series and keep things simple
> 🪲 Fix multiplatform docker build

- .github/workflows/actions/setup-environment/action.yaml
- .github/workflows/reusable-publish.yaml
- .github/workflows/reusable-test.yaml
- Dockerfile
- docker-compose.templates.yaml
- As the next step towards faster pipelines, we'll use the base docker image published to GHCR as the base for our CI runs. Since we don't want to introduce breaking changes to our local workflows, we'll add it as an opt-in feature - we'll allow the base image to be specified as a build argument and we'll allow that to be in turn specified using an environment variable
> 🧹 Use prebuilt base image in github actions [2/N]

- .github/workflows/reusable-publish-docker.yaml
- .github/workflows/reusable-test.yaml
- Dockerfile
- docker-compose.templates.yaml
- pnpm-lock.yaml
- tests/test-evm-node/hardhat.config.ts
- tests/test-evm-node/package.json
- tests/test-evm-node/tsconfig.json
- We also build a new base image - a containerized hardhat EVM node. In its first version, it will be just wrapped `test-evm-node` package with no additional features like environment-based configuration or anything
- Since we are isolating this package, we'll make its `tsconfig.json` independent of the workspace one
- Since we are using `pnpm deploy --prod`, we'll move the `devDependencies` to `dependencies`
- As a bonus we remove the `rebuild` stage that's now been obsolete for some time (it was introduced as a security measure when we were using `NPM_TOKEN` and didn't want it to leak)
> 🧹 Build EVM hardhat node image [3/N]

- .github/workflows/actions/setup-environment/action.yaml
- .github/workflows/reusable-publish.yaml
- Fixing the `HOME` directory for a containerized action (it's always `/__w/<repository name>/<repository name>` as asked [here](https://github.com/actions/runner/discussions/1332)
- Here we need to use `$GITHUB_WORKSPACE` environment variable instead of the `${{ github.workspace }}` context - see [here](https://github.com/actions/runner/issues/2058)
- Fixing problems with _dubious ownership_ as described [here](https://github.com/actions/runner-images/issues/6775)
- A possible solution is to change the docker user as described [here](https://github.com/actions/runner/issues/2033#issuecomment-1598547465) but this, as seen when debugging, will still not change the owner of files coming from checkout action
> 🪲 Fix failing main publish action

- .github/workflows/reusable-publish.yaml
- Debugging the `changesets/action` - at the moment it was complaining about [the current directory not being a git repo](https://github.com/LayerZero-Labs/devtools/actions/runs/8527494307/job/23360046644).
> 🪲 Fix wrong cwd in publish action

- .github/workflows/actions/setup-environment/action.yaml
- .github/workflows/reusable-publish.yaml
- Instead of setting the safe directory, transfer ownership of the workspace directory to the root user (that's the user running the action)
- Fix a problem where environment variables are not expanded when passed as values for `env`
I am not proud but well that's about how much time I have to fix this.
> 🪲 Fix publish action, the saga continues

- .changeset/nervous-rockets-sneeze.md
- packages/ua-devtools/package.json
- packages/ua-devtools/src/oapp/schema.ts
- packages/ua-devtools/src/ownable/schema.ts
- packages/ua-devtools/src/ownable/types.ts
- packages/ua-devtools/test/oapp/schema.test.ts
- Allow any additional `OAppNodeConfig` properties through the schema. This allows for custom, albeit unchecked, configurations to be used with the default schema
- Allow `null` as well as `undefined` for `owner` and `delegate` properties
> 🗞️ Pass additional properties through OAppNodeConfigSchema; Allow null

- .changeset/eight-ravens-fetch.md
- .changeset/red-seals-rule.md
- .changeset/three-spoons-occur.md
- packages/devtools-evm-hardhat/src/omnigraph/types.ts
- packages/devtools-evm-hardhat/test/omnigraph/types.test.ts
- packages/devtools/src/omnigraph/types.ts
- packages/devtools/src/transactions/signer.ts
- packages/protocol-devtools/src/dvn/config.ts
- packages/protocol-devtools/src/dvn/types.ts
- packages/protocol-devtools/src/endpointv2/config.ts
- packages/protocol-devtools/src/endpointv2/types.ts
- packages/protocol-devtools/src/executor/config.ts
- packages/protocol-devtools/src/executor/types.ts
- packages/protocol-devtools/src/priceFeed/config.ts
- packages/protocol-devtools/src/priceFeed/types.ts
- packages/protocol-devtools/src/uln302/config.ts
- packages/protocol-devtools/src/uln302/types.ts
- packages/ua-devtools/src/lzapp/config.ts
- packages/ua-devtools/src/lzapp/types.ts
- packages/ua-devtools/src/oapp/config.ts
- packages/ua-devtools/src/oapp/types.ts
- packages/ua-devtools/src/ownable/config.ts
- packages/ua-devtools/src/ownable/types.ts
- tests/ua-devtools-evm-hardhat-test/layerzero.config.with-custom-configuration.ts
- Add helper types to reduce boilerplate for custom configurations
- `InferOmniGraph` for transforming `OmniGraphHardhat` to `OmniGraph`
- `Configurator` for defining custom configuration functions
- `SignAndSend` type for the result of `createSignAndSend`
> 🧹 Helper types for custom configurations

- .changeset/tricky-laws-cry.md
- packages/ua-devtools/src/oapp/config.ts
- The delegate configuration was not being executed in `lz:oapp:wire`, this fixes it
> 🪲 Add forgotten delegate configuration to wire

- packages/ua-devtools/test/oapp/schema.test.ts
- In #554 a fuzzy test for a schema started failing due to how `zod` handles prototypes and inherited values. Since the purpose of this test is just to ensure that custom values will be passed through and not that it will work once people start overriding built-in values like `toString`, `valueOf` or `__proto__`, the test has been changed to account only for these basic cases
> 🪲 Fix fuzzy tests for OAppNodeConfigSchema

- .changeset/many-toys-explain.md
- packages/devtools/.swcrc
- packages/devtools/src/common/index.ts
- packages/devtools/src/common/retry.ts
- packages/devtools/test/common/retry.test.ts
- packages/devtools/tsconfig.json
- packages/protocol-devtools-evm/.swcrc
- packages/protocol-devtools-evm/src/endpointv2/sdk.ts
- packages/protocol-devtools-evm/src/uln302/sdk.ts
- packages/protocol-devtools-evm/tsconfig.json
- packages/ua-devtools-evm/.swcrc
- packages/ua-devtools-evm/src/lzapp/sdk.ts
- packages/ua-devtools-evm/src/oapp/sdk.ts
- packages/ua-devtools-evm/tsconfig.json
- tsconfig.json
- Adding `AsyncRetriable` decorator factory that can be applied to an `async` method and produces an `async` method that will retry its execution if it rejects
- This functionality is for now feature-flagged under `LZ_EXPERIMENTAL_ENABLE_RETRY` environment variable
- Since we compile `jest` test with `swc`, an additional `.swcrc` needed to be added for jest to be able to handle decorators
> 🗞️ Retry functionality for SDKs

- .changeset/purple-poems-pump.md
- packages/verify-contract/src/common/url.ts
Adds a default url to be used when verifying contracts on Manta
> 🧹 Add default Manta verify contract url

- .changeset/short-melons-approve.md
- EXPERIMENTAL.md
- packages/devtools/src/common/retry.ts
- packages/devtools/test/common/retry.test.ts
- Use `LZ_ENABLE_EXPERIMENTAL_XXX` for all feature flags
- Add a stub markdown file that lists some of the feature flags we have (local simulation is missing but that's for another time)
> 🧹 Consistent feature flag names; Bit of docs on some of the experimental features

- .changeset/slow-ligers-sit.md
- packages/devtools-evm-hardhat/src/runtime.ts
- packages/devtools-evm-hardhat/test/runtime.test.ts
- This feature aims at complex projects with multiple custom configurations. These projects can create custom copies of already existing tasks without overriding them - basically inheriting all the `task`/`subtask` setup and adding their own custom logic
```typescript
import { inheritTask } from '@layerzerolabs/devtools-evm-hardhat'
import { TASK_LZ_OAPP_WIRE } from '@layerzerolabs/ua-devtools-evm-hardhat'
const inheritWireTask = inheritTask(TASK_LZ_OAPP_WIRE)
// This custom task will have access to all the flags & parameters of the wire task
// so it can adjust & pass them to the original wire or do something completely different
inheritWireTask('my-custom-wire-of-type-A').setAction(async ({ ci, oappConfig, /* ... */ }) => {})
// And you can create multiple copies …
```
> 🗞️ Add the ability to inherit task definitions

- .changeset/beige-lies-scream.md
- packages/devtools/src/omnigraph/config.ts
- packages/devtools/src/omnigraph/index.ts
- packages/devtools/src/omnigraph/types.ts
- packages/devtools/test/omnigraph/config.test.ts
- `createConfigureNodes` and `createConfigureEdges` helper functions to reduce the boilerplate for large, custom configurations. These perform the SDK creation, `contracts` / `connections` mapping to `OmniTransaction` objects
> 🗞️ Helpers for reducing boilerplate for custom configurations

- .changeset/pink-apricots-live.md
- packages/devtools/src/omnigraph/config.ts
- packages/devtools/test/omnigraph/config.test.ts
- packages/ua-devtools/src/lzapp/config.ts
- packages/ua-devtools/src/oapp/config.ts
- `createConfigureMultiple` function has been promoted from a local implementation to a utility so that the world can use it should the world want to use it
- In these turbulent times the world should have a choice to use it
> 🗞️ Helper for executing multiple configuration functions

- .changeset/strange-balloons-tie.md
- packages/devtools/src/omnigraph/coordinates.ts
- packages/devtools/test/omnigraph/coordinates.test.ts
- Small `withEid` helper utility for curried `eid` assignment. Useful for DRYing when creating lots of `OmniPoint` / `OmniPointHardhat` etc objects on the same network
> 🧹 Add withEid helper

- .changeset/hot-planets-help.md
- packages/devtools-evm-hardhat/src/cli.ts
- packages/devtools-evm-hardhat/src/transactions/signer.ts
- packages/devtools-evm-hardhat/test/cli.test.ts
- packages/devtools-evm-hardhat/test/transactions/signer.test.ts
- packages/devtools-evm/src/signer/index.ts
- packages/devtools-evm/src/signer/types.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/index.ts
- packages/ua-devtools-evm-hardhat/src/tasks/ownable/transfer.ownership.ts
- tests/ua-devtools-evm-hardhat-test/test/task/oapp/wire.test.ts
- Allow the `--signer` argument to accept a name of a signer as defined using `namedAccounts` configuration
> 🗞️ Add the ability to use named signers

- .changeset/tiny-avocados-begin.md
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/subtask.configure.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/types.ts
- tests/ua-devtools-evm-hardhat-test/hardhat.config.with-custom-configuration.ts
- Make `SubtaskConfigureTaskArgs` type generic since this task is capable of configuring using any matching combination of `configurator` and ~~`oappFactory`~~ `sdkfactory`
> 🧹 Make SubtaskConfigureTaskArgs type generic

- .changeset/blue-starfishes-lick.md
- packages/io-devtools/jest.config.js
- packages/io-devtools/jest.setup.js
- packages/io-devtools/package.json
- packages/io-devtools/src/stdio/logger.ts
- packages/io-devtools/test/stdio/logger.test.ts
- packages/ua-devtools/src/oapp/config.ts
- pnpm-lock.yaml
- Add a new utility function for wrapping `async` functions with logging - `createWithAsyncLogger`
- Add example usage of this function to the OApp config
- The next steps are to add these logs to all the methods that are currently missing logging. Once all the methods are covered, we can switch the logging from `verbose` to `info`
> 🧹 Improve logging

- .changeset/metal-ducks-compete.md
- EXPERIMENTAL.md
- packages/devtools/src/transactions/signer.ts
- packages/devtools/test/transactions/signer.test.ts
- Add a new feature flag `LZ_ENABLE_EXPERIMENTAL_BATCHED_WAIT` that controls the behavior of the transaction signing logic
> 🗞️ Experimental transaction sending

- .changeset/cuddly-goats-rush.md
- packages/devtools/src/common/retry.ts
- packages/devtools/test/common/retry.test.ts
- `AsyncRetriable` needs to call the replaced method with the current `this` context as opposed to the `target` context that points to the object's prototype, otherwise it has no access to non-prototype properties
> 🪲 Fix an issue with non-prototype property access in AsyncRetriable

- .changeset/mighty-rules-film.md
- packages/ua-devtools-evm/src/oapp/sdk.ts
- packages/ua-devtools-evm/src/ownable/index.ts
- packages/ua-devtools-evm/src/ownable/mixin.ts
- packages/ua-devtools-evm/src/ownable/sdk.ts
- packages/ua-devtools/src/ownable/types.ts
- Add an `Ownable` SDK for easier consumption by OApps that extend OpenZeppelin `IOwnable`
- Ignore zero addresses when getting the owner, return `undefined` instead
> 🧹 Add Ownable SDK

- .changeset/great-weeks-appear.md
- packages/devtools-evm-hardhat/src/tasks/deploy.ts
- The progress bar in the deploy task was not being passed the progress as percentage but as a whole number so it was skipping to 100% immediatelly
> 🪲 Fix deployment progress bar

- packages/devtools/test/omnigraph/schema.test.ts
- `fast-check`'s `anything` arbitrary sometimes throws in values with messed up standard object primitives - e.g. `toString` or `toValue` method is not a method. This broke a [recent test run on `main`](https://github.com/LayerZero-Labs/devtools/actions/runs/9004998600/job/24739305144)
- Since the test is checking whether an invalid value will not parse, the fix is to wrap the test precondition with `try`/`catch`
- In case the `try` succeeds, the `fc.pre` is executed an potentially stops the test run
- In case `try` fails, we know we have an invalid value on our hands so we continue the tes
> 🪲 Fix UIntBigIntSchema & UIntNumberSchema tests

- .changeset/slow-walls-impress.md
- packages/devtools/src/omnigraph/schema.ts
- Fix silly cases (mostly for tests) for `UIntNumberSchema` (e.g. missing/invalid `toString` method implementation)
> 🪲 Fix silly cases for UIntNumberSchema

- .changeset/fuzzy-shirts-sleep.md
- packages/devtools-evm-hardhat/src/omnigraph/coordinates.ts
- Only call `deployments.all()` if we fail to get a deployment, then retry. The `deployments.all()` is particularly expensive for large deployment sets and can dramatically decrease the performance
> 🪲 Fix deployment loading slowness for large deployment sets

- .changeset/grumpy-turtles-reply.md
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/index.ts
- tests/ua-devtools-evm-hardhat-test/test/task/oapp/wire.test.ts
- Add `--dry-run` flag to the wire task. This flag will make the task exit without signing any transactions
> 🗞️ Dry run mode for wire task

- .changeset/soft-gorillas-promise.md
- packages/devtools-evm-hardhat/src/omnigraph/coordinates.ts
- packages/devtools-evm-hardhat/src/omnigraph/transformations.ts
- packages/devtools-evm-hardhat/src/omnigraph/types.ts
- packages/devtools-evm-hardhat/test/omnigraph/coordinates.test.ts
- packages/devtools-evm-hardhat/test/omnigraph/transformations.test.ts
- packages/devtools/src/omnigraph/coordinates.ts
- packages/devtools/src/omnigraph/format.ts
- packages/devtools/src/omnigraph/schema.ts
- packages/devtools/src/omnigraph/types.ts
- packages/devtools/test/omnigraph/coordinates.test.ts
- packages/devtools/test/omnigraph/format.test.ts
- packages/test-devtools/src/arbitraries.ts
- Add `contractName` property on `OmniPoint` to support scenarios such as proxy contracts. When using proxy contracts, the contract ABI is not present in the deployment for a particular `address` - instead the ABI needs to be pulled from artifacts by the contract name and associated with an address (this is already the case in `createContractFactory`)
> 🧹 Support contractName property on OmniPoint

- Dockerfile
Devs may run into an issue with `pnpm test:ci` using an older version of `pnpm`. To avoid this, we should always use the version specified in `package.json` within `Dockerfile`
> Updated docker file to use package.json for pnpm version

- .changeset/red-toys-chew.md
- packages/devtools-evm-hardhat/src/tasks/simulation/logs.ts
- Add `--follow` CLI flag to `lz:test:simulation:logs` task that causes the logs command to follow the docker compose logs
> 🧹 Ability to follow simulation logs

- .changeset/old-pens-yawn.md
- packages/ua-devtools/src/oapp/config.ts
- Refactored `configureSendLibraries` in `ua-devtools > src > oapp > config.ts` to use `createConfigureEdges` pattern and added logging
> 🧹  Refactoring configureSendLibraries

- .changeset/stale-lemons-hide.md
- packages/devtools-evm/src/simulation/anvil.ts
- packages/devtools-evm/test/simulation/__snapshots__/anvil.test.ts.snap
- packages/devtools-evm/test/simulation/anvil.test.ts
- For massive simulations on machines with limited resources the `anvil` nodes can quickly run out of space. Adding `pruneHistory` to `AnvilOptions` should take care of that
> 🧹 Add --prune-history to AnvilOptions

- .changeset/heavy-tigers-bow.md
- packages/devtools-evm/src/omnigraph/sdk.ts
- packages/protocol-devtools-evm/src/endpointv2/schema.ts
- packages/protocol-devtools-evm/src/endpointv2/sdk.ts
- packages/protocol-devtools-evm/test/endpoint/sdk.test.ts
- Catch `LZ_DefaultSendLibUnavailable` and `LZ_DefaultReceiveLibUnavailable` errors when getting send/receive libraries from the endpoint.
- In case of a missing receive library, `[address: undefined, isDefault: true]` will be returned
- In case of a missing send library, `undefined` will be returned
The visibility of static `errorParserFactory` needed to be changed since descendant classes could not read this private static property.
> 🪲 Catch reverts when the default libraries are missing

- .changeset/spotty-pants-hear.md
- packages/devtools-evm-hardhat/src/simulation/config.ts
- packages/devtools-evm-hardhat/test/simulation/config.test.ts
- Do not overwrite hardhat account configs for simulation. 
- The simulation nodes will be started with the mnemonic configured in the `anvil` config
- The network account configs will be kept the same
This allows users to run a _true_ simulation - with the accounts they would use on the actual networks.
> 🧹 Don't overwrite the account configs in simulation

- .changeset/seven-coats-add.md
- examples/oapp/layerzero.config.ts
- packages/devtools/src/omnigraph/config.ts
- packages/ua-devtools-evm/src/oapp/sdk.ts
- packages/ua-devtools/src/oapp/config.ts
- packages/ua-devtools/src/oapp/types.ts
- tests/ua-devtools-evm-hardhat-test/contracts/DefaultOApp.sol
- tests/ua-devtools-evm-hardhat-test/test/oapp/config.test.ts
- Adds getter and setter for `OFTWrapper.callerBpsCap` in `packages/ua-devtools-evm/src/oapp/sdk.ts`
- Calling above getter/setter in configurator
- Also have an example of how `callerBpsCap` can be configured in `layerzero.config.ts`
> 🧹 Add devtools configurator for OFTWrapper.setCallerBpsCap(...)

- Dockerfile
- There are concurrency issues when it comes to running `forge build` / `forge test` in monorepo setups (`text file busy` errors). This PR adds `SVM` (crate used by forge to manage `solc` versions) and install `solc` 0.8.22 so that it does not need to be installed on the fly when running tests
- After this PR is merged, a new base image will be built. After  that is done, we can remove the package-specific `turbo.json` files that ensured that the forge tasks are run in series
> 🧹 Install SVM & solc 0.8.22 in the base image

- packages/devtools-cli/.eslintignore
- packages/devtools-cli/.eslintrc.json
- packages/devtools-cli/.prettierignore
- packages/devtools-cli/README.md
- packages/devtools-cli/cli.js
- packages/devtools-cli/jest.config.js
- packages/devtools-cli/package.json
- packages/devtools-cli/src/commands/oapp/index.ts
- packages/devtools-cli/src/commands/oapp/wire/index.ts
- packages/devtools-cli/src/commands/options.ts
- packages/devtools-cli/src/index.ts
- packages/devtools-cli/src/setup/index.ts
- packages/devtools-cli/src/setup/loading.ts
- packages/devtools-cli/src/setup/schema.ts
- packages/devtools-cli/src/setup/types.ts
- packages/devtools-cli/tsconfig.json
- packages/devtools-cli/tsconfig.test.json
- packages/devtools-cli/tsup.config.ts
- pnpm-lock.yaml
- tests-user/tests/devtools-cli.bats
- To support non-EVM chains without resorting to `hardhat`, we're adding a framework-agnostic CLI package that will eventually reach parity with the hardhat version (`@layerzerolabs/toolbox-hardhat`).
- Since we are no longer bound to the `hardhat` context, the consumers need to provide the parts that would otherwise be provided by `hardhat` - SDK & signer factories. This is achieved using a setup file
> 🗞️ Stub of devtools-cli package

- examples/oapp/test/foundry/MyOApp.t.sol
- examples/oft/test/foundry/MyOFT.t.sol
- examples/oft/turbo.json
- examples/onft721/turbo.json
- Remove no-longer-necessary `turbo.json` files from examples
- Update access modifiers for example foundry tests
> 🧹 Clean up examples

- tests/ua-devtools-evm-hardhat-test/test/task/oapp/__data__/configs/valid.config.connected.external.connection.js
- tests/ua-devtools-evm-hardhat-test/test/task/oapp/wire.test.ts
- Add a test case for the wire task that involves an external contract set as a `to` for a connection
> 🧹 Add a test for an external contract in connections

- .changeset/lemon-shrimps-pay.md
- packages/devtools-evm-hardhat/src/simulation/config.ts
- packages/devtools-evm-hardhat/src/simulation/types.ts
- packages/devtools-evm-hardhat/test/simulation/config.test.ts
- To make #642 not affect the existing behavior, it has been adjusted with a flag that turns the account overwrites on/off
- The default value is `true` (which matches the previous behavior), setting it to an explicit `false` will turn the overwrites off
> 🧹 Allow users to specify whether the simulation accounts should be overwritten

- .changeset/afraid-games-poke.md
- packages/devtools-evm-hardhat/src/config.ts
- packages/devtools-evm-hardhat/src/type-extensions.ts
- packages/devtools-evm-hardhat/test/config.test.ts
- When loading external artifacts into hardhat, we now allow custom artifact paths
- `path` alongside a package name will be appended to the resolved package filesystem path (for overriding the default `artifacts` path)
- `path` without a package name will be used as a direct filesystem path to the artifacts folder
> 🗞️ Allow custom paths when loading external artifacts

- .changeset/olive-planes-double.md
- packages/devtools-evm-hardhat/src/runtime.ts
- Add `createDefaultContext` utility to `devtools-evm-hardhat`. This utility mirrors the hardhat initialization stage and allows us to create hardhat environment outside of the hardhat CLI
> 🗞️ Add createDefaultContext utility

- .changeset/twenty-paws-tease.md
- packages/devtools-evm-hardhat/src/omnigraph/coordinates.ts
- tests/ua-devtools-evm-hardhat-test/test/task/oapp/__snapshots__/wire.test.ts.snap
- Improve errors for missing deployments - the error now contains the network name & the endpoint ID of the missing deployment
> 🧹 Improve errors for missing deployments

- .changeset/plenty-fireants-help.md
- packages/test-devtools-evm-foundry/contracts/OptionsHelper.sol
- packages/test-devtools-evm-foundry/contracts/TestHelperOz5.sol
- Add an internal method to initialize `UlnOptionsMock` in `OptionsHelper` to fix issues with fork testing in foundry
- Fixes #666
> 🪲 UlnOptionsMock initialization in OptionsHelper

- .changeset/ten-planets-promise.md
- packages/devtools-cli/README.md
- packages/devtools-cli/cli.js
- packages/devtools-cli/package.json
- packages/devtools-cli/src/cli.ts
- packages/devtools-cli/src/index.ts
- packages/devtools-cli/src/setup/index.ts
- packages/devtools-cli/src/setup/loading.ts
- packages/devtools-cli/src/setup/schema.ts
- packages/devtools-cli/src/setup/types.ts
- packages/devtools-cli/src/types.ts
- packages/devtools-cli/tsup.config.ts
- Add additional `exports` to `@layerzerolabs/devtools-cli` package to expose types that can be used in the client packages
- The binary now lives in `cli.ts`
- The type exports consumable by client packages live in `index.ts`
- Add a bit of `README` (to be continued)
> 🧹 CLI: Add type exports to CLI package [2/N]

- .changeset/sweet-oranges-sneeze.md
- packages/devtools-cli/src/commands/oapp/wire/index.ts
- packages/devtools-cli/src/commands/options.ts
- packages/devtools-cli/src/setup/typescript.ts
- Add support for TypeScript config files in `devtools-cli`
- Fix missing `--log-level` CLI option parser
> 🧹 CLI: Add TypeScript support; Fix missing --log-level CLI flag [4/N]

- .changeset/metal-dryers-share.md
- packages/devtools-evm-hardhat/src/runtime.ts
- packages/devtools-evm-hardhat/src/transactions/format.ts
- When using `formatOmniTransaction` with a transaction whose network is not defined in `hardhat.config`, the function would throw. This is not great if we want to add e.g. Solana to our `layerzero.config`
> 🧹 Don't force a network to be defined in hardhat config when formatting transactions

- verdaccio.yaml
- While working on #700 I found a couple of missing proxying rules for the local NPM registry. Omitting these rules only meant that these packages were not required to be published locally when running the local registry, nothing super serious but better include them
> 🪲 Verdaccio proxy rules

- packages/test-devtools-solana/.eslintignore
- packages/test-devtools-solana/.eslintrc.json
- packages/test-devtools-solana/.gitignore
- packages/test-devtools-solana/.prettierignore
- packages/test-devtools-solana/README.md
- packages/test-devtools-solana/package.json
- packages/test-devtools-solana/src/arbitraries.ts
- packages/test-devtools-solana/src/index.ts
- packages/test-devtools-solana/tsconfig.json
- packages/test-devtools-solana/tsup.config.ts
- pnpm-lock.yaml
- Add `@layerzerolabs/test-devtools-solana` package with testing utilities for Solana-based packages. At the moment the package only contains arbitrariness for seeds, `Keypair` objects and public addresses
> 🗞️ Solana: Add test-devtools-solana package

- .changeset/heavy-cars-push.md
- packages/oft-evm/package.json
We plan to inherit OFT.t.sol in other npm packages.  I would argue, every OFT should be able to pass the OFT.t.sol test suite, albeit with some modifications based on implementation details.  For example, a Fee-based OFT should be able to pass such tests.
> 🧹 export tests from oft-evm

- .changeset/fuzzy-fans-give.md
- packages/devtools-evm/src/signer/sdk.ts
- packages/devtools/src/transactions/signer.ts
- packages/devtools/src/transactions/types.ts
- Since we are introducing Solana, we can utilize the common signer functionality for the Solana signer as well
> 🧹 Solana: Move common signer functionality into devtools

- packages/devtools-evm-hardhat/src/type-extensions.ts
safeUrl is an ambiguous and misleading name.  The least we can do is document what it is supposed to mean.
> 🧹 clean up documentation around safeUrl

- .changeset/little-foxes-sit.md
- packages/devtools-solana/package.json
- packages/devtools-solana/src/index.ts
- packages/devtools-solana/src/omnigraph/sdk.ts
- packages/devtools-solana/src/transactions/index.ts
- packages/devtools-solana/src/transactions/serde.ts
- packages/devtools-solana/src/transactions/signer.ts
- packages/devtools-solana/test/connection/factory.test.ts
- packages/devtools-solana/test/omnigraph/sdk.test.ts
- packages/devtools-solana/test/transactions/serde.test.ts
- packages/devtools-solana/test/transactions/signer.test.ts
- packages/test-devtools-solana/package.json
- packages/test-devtools-solana/src/arbitraries.ts
- pnpm-lock.yaml
- Add `OmniSignerSolana`
- Add `feePayer` and `recentBlockHash` when creating transactions in the SDK. This is where Solana differs from EVM in that SDK and accounts can no longer be separated easily
- Add serialization / deserialization methods for Solana transactions
- Add `solanaBlockhashArbitrary` for testing purposes
> 🗞️ Solana: Add signer & transaction serde methods

- .changeset/clever-pianos-flash.md
- .changeset/gorgeous-ladybugs-swim.md
- packages/devtools-solana/test/omnigraph/sdk.test.ts
- packages/devtools-solana/test/transactions/signer.test.ts
- packages/devtools/package.json
- packages/devtools/src/common/bytes.ts
- packages/devtools/src/types.ts
- packages/devtools/test/bytes.test.ts
- packages/devtools/test/common/bytes.test.ts
- packages/test-devtools-solana/src/arbitraries.ts
- packages/test-devtools/package.json
- packages/test-devtools/src/arbitraries.ts
- packages/ua-devtools-evm/src/oapp/sdk.ts
- packages/ua-devtools-evm/test/oapp/sdk.test.ts
- pnpm-lock.yaml
- tests/ua-devtools-evm-hardhat-test/test/oapp/config.test.ts
- tests/ua-devtools-evm-hardhat-test/test/task/oapp/__data__/configs/valid.config.connected.external.connection.js
- Low-level peer address logic around the `peer` address. This is one special case of an address-like value that cannot be encapsulated in a specific chain implementation of an SDK - the look & feel of this value does not depend on the source chain but rather on the target chain. For example, EVM SDK should return a value that resembles a Solana address if asked for a peer on `SOLANA_V2_MAINNET` and vice versa.
- The logic in the SDK's `getPeer`/`setPeer`/`hasPeer` should always follow a normalization pattern:
- Remote chain address address is converted to a normalized value (32 items long `UInt8Array`)
- Normalized value is converted into a local chain value
- This required several cuts into the underlying bytes logic around `bytes32`. The code should now handle `UInt8Array` as a valid …
> 🗞️ Solana: Generic peer logic [6/N]

- .changeset/strong-dingos-own.md
- packages/devtools/src/common/bytes.ts
- packages/ua-devtools-evm/src/oapp/sdk.ts
- Adding more comments on the bytes utilities in `devtools`
- Improving the `peer` logic in `OApp` SDK (split off the next PR with Solana OFT SDK)
> 🧹 Solana: Better peer logic in OApp [7/N]

- .changeset/tidy-cups-accept.md
- packages/oft-evm/foundry.toml
- packages/toolbox-foundry/Makefile
- Fix a `cp` command in `toolbox-foundry` (`cp` behaves differently on BSD and GNU systems)
> 🪲 Fix solidity-bytes-utils in toolbox-foundry

- packages/onft-evm/contracts/onft721/ONFT721Adapter.sol
Similar to ERC20s, certain token implementations may extend the token logic with things such as pausing, banning and soulbound controls (non-transfer- ability of certain NFTs). For example, here are some users discussing how to make certain NFTs soulbound:
https://forum.openzeppelin.com/t/soulbound-nft-migration-from-v4-9-to--v5-0/38931/4
By using `_burn`, less metadata of who is initiating this transaction is sent to `_update`, potentially causing such checks to still pass because the auth metadata does not include the msg.sender.
This commit simply documents the limitation for such tokens with an appropriate developer warning.
> 🧹document compatibility limitations with tokens which block transactions

- packages/protocol-devtools-solana/.eslintignore
- packages/protocol-devtools-solana/.eslintrc.json
- packages/protocol-devtools-solana/.prettierignore
- packages/protocol-devtools-solana/.swcrc
- packages/protocol-devtools-solana/README.md
- packages/protocol-devtools-solana/jest.config.js
- packages/protocol-devtools-solana/jest.setup.js
- packages/protocol-devtools-solana/package.json
- packages/protocol-devtools-solana/src/endpointv2/index.ts
- packages/protocol-devtools-solana/src/endpointv2/sdk.ts
- packages/protocol-devtools-solana/src/index.ts
- packages/protocol-devtools-solana/test/endpointv2/sdk.test.ts
- packages/protocol-devtools-solana/tsconfig.json
- packages/protocol-devtools-solana/tsup.config.ts
- packages/ua-devtools-solana/jest.config.js
- pnpm-lock.yaml
- Add `protocol-devtools-solana` package with only a stub of `EndpointV2` SDK
- The only implemented getters are `getDefaultReceiveLibrary`, `getDefaultSendLibrary` and `isDefaultSendLibrary`
- The SDK is not yet connected to the OFT SDK
> 🗞️ Solana: Stub of EndpointV2 SDK: Send & receive library getters [10/N]

- packages/protocol-devtools-solana/package.json
- packages/ua-devtools-solana/package.json
- Conditionally disable flaky Solana tests that rely on live RPCs
> 🧹 Solana: Disable flaky tests

- .changeset/lucky-mice-design.md
- packages/protocol-devtools-solana/jest.config.js
- packages/protocol-devtools-solana/src/endpointv2/sdk.ts
- packages/protocol-devtools-solana/test/endpointv2/sdk.test.ts
- packages/ua-devtools-solana/jest.config.js
- Add getters for send & receive library on the endpoint SDK for Solana. There is a slight catch here - if we're asking for a send/receive library for a particular OFT, we need to use the OFT config account address, not the OFT address. I am currently thinking about the prettiest way to encapsulate this into the SDK:
- Subclass the `EndpointV2` SDK if we're getting it through the OFT SDK. The subclass will replace the address of the OFT with its config account address
- Add a function to the `OApp` interface that returns an address that should be used for these calls. For EVM it will return the contract address itself whereas for Solana it will return the config account
> 🗞️ Solana: Send & Receive library getters [11/N]

- .changeset/gentle-frogs-report.md
- packages/protocol-devtools-solana/src/endpointv2/sdk.ts
- packages/protocol-devtools-solana/test/endpointv2/sdk.test.ts
- Fixing my misinterpretation from earlier where I thought `isDefaultSendLibrary` checks whether an address is a default send library. What it is supposed to check is that the address uses a default send library as opposed to using a custom one
> 🪲 Solana: Misinterpreted isDefaultSendLibrary [12/N]

- .changeset/giant-toys-compare.md
- packages/ua-devtools-evm/src/oapp/sdk.ts
- packages/ua-devtools-solana/src/oft/sdk.ts
- packages/ua-devtools/src/oapp/config.ts
- packages/ua-devtools/src/oapp/types.ts
- For non-EVM networks (as proven by Solana), the account that holds the OApp config can differ from the OApp itself. To account for this, `getEndpointConfigAddress` method has been added to the `IOApp` interface
- To avoid issues with mismatching dependencies, this method is used with caution in the `OApp` configurator - if it does not exist, it is substituted with the OApp address (the legacy code)
> 🧹 Solana: Abstract config account [13/N]

- .changeset/polite-eyes-wash.md
- packages/ua-devtools-solana/package.json
- packages/ua-devtools-solana/src/oft/sdk.ts
- packages/ua-devtools-solana/test/oft/sdk.test.ts
- pnpm-lock.yaml
- Return the `EndpointV2` SDK from `OFT` SDK for Solana
> 🧹 Solana: Implement getEndpointSDK for OFT SDK [14/N]

- .changeset/two-items-punch.md
- packages/protocol-devtools-solana/src/endpointv2/sdk.ts
- packages/protocol-devtools-solana/test/endpointv2/sdk.test.ts
- Adding setters for send & receive libraries on the EndpointV2 SDK for Solana
> 🗞️ Solana: Add Send & Receive library setters to EndpointV2 SDK [15/N]

- .changeset/polite-panthers-guess.md
- packages/protocol-devtools-solana/src/endpointv2/sdk.ts
- packages/protocol-devtools-solana/src/index.ts
- packages/protocol-devtools-solana/src/uln302/index.ts
- packages/protocol-devtools-solana/src/uln302/sdk.ts
- packages/protocol-devtools-solana/test/endpointv2/sdk.test.ts
- Add a stub of `Uln302` SDK with only `getAppExecutorConfig` and `getAppUlnConfig` implemented
> 🗞️ Solana: Add Uln302 SDK [16/N]

- .changeset/fuzzy-ducks-divide.md
- packages/protocol-devtools/src/endpointv2/types.ts
- packages/ua-devtools/src/oapp/config.ts
- Adding an extra parameter required for successful config setting on Solana (Solana has 3, not 2 types of config as opposed to EVM. The ULN config has two types for send and receive)
> 🗞️ Solana: Setting configs [17/N]

- .changeset/grumpy-seas-double.md
- packages/protocol-devtools-solana/src/endpointv2/schema.ts
- packages/protocol-devtools-solana/src/endpointv2/sdk.ts
- packages/protocol-devtools-solana/src/uln302/sdk.ts
- packages/protocol-devtools-solana/test/endpointv2/sdk.test.ts
- Update `EndpointV2` SDK to return program IDs for send/receive libraries instead of the config accounts. The `getDefaultSendLibrary` and `getDefaultReceiveLibrary` do not return program ID and need to be fix in upstream before they start working correctly
- Add Send, Receive & Executor config setting functionality to `EndpointV2`
- Seeing the implementation for Solana, we might later encapsulate this logic completely within the `OApp` SDK to avoid passing data around
> 🗞️ Solana: Setting ULN & Executor configs [18/N]

- .changeset/light-birds-rest.md
- .changeset/loud-impalas-shop.md
- packages/devtools-solana/.swcrc
- packages/devtools-solana/src/omnigraph/sdk.ts
- packages/devtools-solana/tsconfig.json
- packages/devtools/src/common/retry.ts
- packages/devtools/test/common/retry.test.ts
- Allow `AsyncRetriable` to be configurable at runtime. This is important especially for Solana where the public RPC is super keen on returning `HTTP 429`
- Use `AsyncRetriable` when creating Solana transactions in the SDK since they need to call the RPC to get a recent block hash
- ~~Bump `esbuild` to include [this change](https://github.com/evanw/esbuild/commit/ae5cc175165551016f8e19475c4ac9872e60f247) that allows abstract classes to have decorators~~ Removed the `abstract` modifier from OmniSDK in Solana to make it compile in `jest` (because of decorator/abstract class incompatibility)
> 🧹 Solana: AsyncRetriable runtime configuration [20/N]

- .changeset/yellow-swans-own.md
- packages/ua-devtools-evm/src/oapp/sdk.ts
- packages/ua-devtools-solana/src/oft/sdk.ts
- packages/ua-devtools-solana/test/oft/sdk.test.ts
- packages/ua-devtools/src/oapp/config.ts
- packages/ua-devtools/src/oapp/types.ts
- Turns out the `getEndpointConfigAddress` was a step sideways. This PR reverts the logic introduced in #768 and instead changes the way OFT identifies itself
- Instead of the program ID, OFT is using its instance account as its address, and its program ID is passed along (and defaulted to the default program ID) to the SDK
> 🧹 Solana: Backtrack getEndpointConfigAddress changes [21/N]

- .changeset/clean-boxes-teach.md
- .changeset/spicy-mails-exercise.md
- packages/ua-devtools-solana/package.json
- packages/ua-devtools-solana/src/oft/factory.ts
- After #783, the `OFT` no longer receives a mint account - it receives a program ID instead. While the types of these are the same, the name for `createOFTFactory` has not been updated and would cause confusion
> 🪲 Solana: Fix typo in createOFTFactory [22/N]

- .changeset/clever-spoons-sniff.md
- packages/devtools-evm/src/signer/sdk.ts
- packages/devtools-solana/src/transactions/signer.ts
- packages/devtools/src/transactions/signer.ts
- packages/devtools/src/transactions/types.ts
- On Solana, we need a user account (or its public key to be precise) when collecting the transactions that need to be executed. This user account needs to match the signer account so the prettiest way to get one is to just ask the signer for its public key
> 🧹 Solana: Add getPoint method to OmniSigner [23/N]

- .changeset/perfect-suits-breathe.md
- packages/devtools-solana/src/connection/factory.ts
- Add `createRpcUrlFactory` method to `devtools-solana` to reduce boilerplate when supplying RPC URLs from environment variables
> 🧹 Solana: Add createRpcUrlFactory convenience method [24/N]

- .changeset/cold-clouds-kick.md
- packages/devtools/src/transactions/signer.ts
- packages/devtools/test/transactions/signer.test.ts
- Fixed an issue with the signing logic that was resulting in a confusing signing state (occurring for Safe signer typically). If the signer factory threw an error, the logic would terminate but would not mark any transactions as failed or successful, resulting in a confusing message saying `Your OApp is now configured, 0 transactions successful`
> 🪲 Wrap errors coming from signer factories

- .changeset/pink-donkeys-itch.md
- packages/protocol-devtools-solana/src/endpointv2/sdk.ts
- packages/protocol-devtools-solana/test/endpointv2/sdk.test.ts
- Adjust the default send/receive library in Solana OFT SDK to return falsy values if defaults are not set
- Adjust the logic to return program IDs instead of config accounts for send/receive libraries
> 🧹 Solana: Adjust default send/receive library logic in Solana OFT SDK [25/N]

- .changeset/grumpy-cobras-run.md
- packages/devtools-solana/src/transactions/signer.ts
- Add the ability to specify `lookupAddress` for `OmniSignerSolana` which will trigger a versioned transaction flow
> 🧹 Solana: Add the ability to specify lookupTable in OmniSignerSolana [28/N]

- packages/protocol-devtools-solana/bin/test
- packages/protocol-devtools-solana/package.json
- packages/ua-devtools-solana/bin/test
- packages/ua-devtools-solana/package.json
- Replace inline bash conditional expression with a bash file and pass script arguments to the underlying `jest` command. This is important for being able to e.g. update snapshots or run focused tests
> 🪲 Solana: Allow CLI arguments to be passed to Solana tests [30/N]

- .changeset/honest-schools-carry.md
- packages/devtools-solana/src/transactions/serde.ts
- packages/protocol-devtools-evm/src/endpointv2/sdk.ts
- packages/protocol-devtools-solana/src/endpointv2/sdk.ts
- packages/protocol-devtools-solana/test/endpointv2/__snapshots__/sdk.test.ts.snap
- packages/protocol-devtools-solana/test/endpointv2/sdk.test.ts
- packages/protocol-devtools/src/endpointv2/types.ts
- packages/ua-devtools/src/oapp/config.ts
- tests/ua-devtools-evm-hardhat-test/test/oapp/config.test.ts
- For Solana specifically, the `setConfig` function for larger projects produced transactions that were too large. This logic introduces a very naive transaction size estimation (not accounting for any lookup tables used and assuming 1 signer) and splits the `setConfig` transaction for Solana into multiple ones
- A backwards-compatible change has been introduced to `ua-devtools` to account for outdated packages being used. This ensures that the wire script will run even if an older SDK is used and only one transaction is returned from `setConfig`
> 🧹 Solana: Allow EndpointV2.setConfig to return multiple OmniTransactions [31/N]

- .changeset/famous-ties-collect.md
- .changeset/purple-dogs-agree.md
- packages/devtools-solana/package.json
- packages/devtools-solana/src/common/index.ts
- packages/devtools-solana/src/common/schema.ts
- packages/devtools-solana/test/common/schema.test.ts
- packages/protocol-devtools-evm/src/endpointv2/sdk.ts
- packages/protocol-devtools-evm/src/uln302/sdk.ts
- packages/protocol-devtools-solana/src/endpointv2/sdk.ts
- packages/protocol-devtools-solana/src/uln302/schema.ts
- packages/protocol-devtools-solana/src/uln302/sdk.ts
- packages/protocol-devtools/src/endpointv2/types.ts
- packages/protocol-devtools/src/uln302/types.ts
- packages/ua-devtools/src/oapp/config.ts
- pnpm-lock.yaml
- Solana `Uln302` SDK had a bug where it was returning the receive config for both send & receive configuration. This was because on Solana the send and receive addresses are/can be the same and we need to specify which config we want
- A `type` parameter has been added to SDKs and configs and logging was adjusted to better reflect on what's going on. For the EVM implementation this type is only displayed in the logs and has no functional meaning - if not passed (e.g. when somebody partially updates the devtools packages), everything will still work so no polyfill necessary
- `getAppUlnConfig` no longer uses the defaults as the fallback, instead, it returns an empty config
- A schema was introduced instead of inline parsing for `getAppUlnConfig`
> 🪲 Solana: Specify ULN config type when getting configuration in the SDK [32/N]

- .changeset/flat-elephants-kneel.md
- packages/protocol-devtools-solana/src/endpointv2/sdk.ts
- packages/ua-devtools-solana/src/oft/config.ts
- packages/ua-devtools-solana/src/oft/index.ts
- packages/ua-devtools-solana/src/oft/sdk.ts
- As demanded at a gunpoint by @St0rmBr3w , the Solana devtools for OFT should provide a convenient way of initializing the OFT-related accounts. This PR adds the first step, a configuration function that can be imported & plugged into a wire task
- At this point only nonce initialization is available
> 🧹 Solana: Add a stub of account initialization functionality for OFT [33/N]

- .changeset/late-bottles-perform.md
- packages/devtools-solana/src/transactions/signer.ts
- Make `OmniSolanaSigner` assign a recent block hash just before signing & sending a transaction to avoid problems with expiring block hashes
- If this feature flagged functionality works, we might want to scrape it from the SDKs completely (the recent block hash is assigned when creating a transaction so that it can be serialized and we might be able to replace a real block hash with `PublicKey(0).toBase58()`)
> 🧹 Solana: Add a feature flagged functionality for reassigning recent block hashes in solana signer [34/N]

- .changeset/young-ants-drive.md
- examples/oapp/hardhat.config.ts
- examples/oft-adapter/hardhat.config.ts
- examples/oft/hardhat.config.ts
- examples/onft721/hardhat.config.ts
Match the name to what is used for verification tool.
> chore:  fuji-testnet should be called avalanche-testnet to match url.ts

- examples/oapp/package.json
- examples/oft-adapter/package.json
- examples/oft/package.json
- examples/onft721/package.json
- package.json
- pnpm-lock.yaml
- Remove edr module resolution after `hardhat` update. This module was fixed since its older versions wouldn't compile on all architectures
> 🪲 Remove edr resolution

- Dockerfile
- Add `anchor` and `solana` binaries to the `base` image to support Solana projects (#812)
> 🗞️ Solana: Add anchor & solana binaries to the base docker image [40/N]

- .github/workflows/reusable-publish-docker.yaml
- Use the 4x runn er to build docker images since the default one is timing out
> 🧹 Use larger runner for building base images

- .github/workflows/reusable-publish-docker.yaml
- Dockerfile
- The build workflow for the base docker images was still being too slow to be practical. This PR adds several optimizations:
- The EVM node build now reuses the base build by separating the build into two jobs and specifying `BASE_IMAGE` build argument
- The Solana binaries are only built from source if the OS/CPU combination is not supported. This is the case for arm64 (M2 macs) on Linux
- Anchor install is no longer forced
Example run is [here](https://github.com/LayerZero-Labs/devtools/actions/runs/10305794296/job/28527452013)
> 🧹 Speed up base image build

- .github/workflows/reusable-publish-docker.yaml
- The `BASE_IMAGE` build argument has been removed from the docker build for the EVM node. This is because of a silly issue - the base image in a `Dockerfile` must be lowercase (see the error [here](https://github.com/LayerZero-Labs/devtools/actions/runs/10307121961/job/28538440169)).
- Since we are using docker layer caching anyway, this does not hurt the performance a lot, see a completed job [here](https://github.com/LayerZero-Labs/devtools/actions/runs/10309412989)
> 🪲 Remove BASE_IMAGE when building EVM node

- .github/workflows/reusable-publish.yaml
- .github/workflows/reusable-test.yaml
- Since we have `solc` preinstalled on the machine, we should be able to run the build in parallel. I will rerun this PR several times and only mark it as ready for review if there is no flakiness
> 🧹 Parallelize build

- Dockerfile
- The user tests have grown and it's time to parallelize them. The first step is to install `parallel` GNU utility into the base image. See more [here](https://bats-core.readthedocs.io/en/stable/usage.html#parallel-execution)
> 🧹 Add parallel utility to the dockerfile

- .github/workflows/reusable-publish-docker.yaml
- Since for `linux/arm64` the base docker image needs to build Solana binaries from source (takes about 2 hours in total to build on the github runner), we'll be using a faster runner for this
> 🧹 Run docker build on faster runner

- packages/protocol-devtools-solana/test/endpointv2/sdk.test.ts
- Unfortunately one of the Solana tests (that we run against mainnet) is flaky due to timeout issues. until we have a local Solana node with endpoints, we'll disable this test. Sad times
> 🧹 Disable flaky test

- .changeset/breezy-tigers-destroy.md
- packages/verify-contract/src/cli.ts
- packages/verify-contract/src/hardhat-deploy/types.ts
- packages/verify-contract/src/hardhat-deploy/verify.ts
- Constructor arguments (`--arguments`) can now be passed as a HEX-encoded string (with leading `0x`) to the `non-target` verification CLI
> 🗞️ Support encoded constructor arguments in non-target verification

- .changeset/fifty-pumas-play.md
- packages/devtools-solana/src/connection/factory.ts
- packages/devtools-solana/test/connection/factory.test.ts
- The default RPC URL for `SOLANA_V2_TESTNET` and `SOLANA_TESTNET` is the devnet URL
> 🧹 Change the default URL for Solana testnet

- .changeset/smooth-hairs-begin.md
- packages/devtools-evm-hardhat/src/cli.ts
- packages/devtools-evm-hardhat/test/cli.test.ts
- Add `eid` hardhat CLI argument parser that accepts both labels `SOLANA_V2_MAINNET` and eids (`30101`)
> 🧹 Add hardhat CLI argument parser for eid

- .changeset/clean-bugs-clap.md
- .changeset/heavy-onions-march.md
- .changeset/poor-days-double.md
- packages/devtools-solana/src/common/accounts.ts
- packages/devtools-solana/src/common/index.ts
- packages/devtools-solana/src/omnigraph/coordinates.ts
- packages/devtools-solana/src/omnigraph/index.ts
- packages/devtools-solana/src/omnigraph/sdk.ts
- packages/devtools-solana/test/common/accounts.test.ts
- packages/protocol-devtools-solana/src/endpointv2/sdk.ts
- packages/ua-devtools-solana/src/oft/config.ts
- packages/ua-devtools-solana/src/oft/sdk.ts
- Add account initialization status checkers to `OFT` and `EndpointV2` SDK. These are used in the initialization configurator to check whether we need to initialize `OApp` nonce, send & receive lib or config accounts
> 🗞️ Solana: Add account initialization checkers for OFT [37/N]

- .changeset/rotten-plants-hear.md
- examples/oft-solana/package.json
- pnpm-lock.yaml
- `@solana-developers/helpers` has just been updated to `2.5.0` and this update includes a broken ESM setup. The version has been fixed to `2.4.0` to prevent the examples from breaking
> 🪲 Solana: Fix @solana-developers/helpers version to 2.4.0

- .changeset/empty-buses-occur.md
- packages/oapp-evm/package.json
- packages/oft-evm/package.json
- packages/onft-evm/package.json
- Add `artifacts` to the `exports` in EVM contract packages
- Requires #866 to be merged since the user tests are failing
> 🧹 Add exports to EVM contract packages

- .changeset/neat-bobcats-stare.md
- packages/protocol-devtools-evm/src/dvn/factory.ts
- packages/protocol-devtools-evm/src/dvn/sdk.ts
- packages/protocol-devtools-evm/src/endpointv2/sdk.ts
- packages/protocol-devtools-evm/src/executor/factory.ts
- packages/protocol-devtools-evm/src/executor/sdk.ts
- packages/protocol-devtools-evm/src/priceFeed/factory.ts
- packages/protocol-devtools-evm/src/priceFeed/sdk.ts
- packages/ua-devtools-evm-hardhat/src/utils/taskHelpers.ts
- tests/test-setup-devtools-evm-hardhat/src/endpointV2/setup.ts
- Continue decoupling SDKs from hardhat-deploy - embedding ABIs for `DVN`, `Executor` and `PriceFeed` SDKs
- The OApp constructor has not changed yet
> 🧹 Decouple DVN, Executor & PriceFeed SDKs from hardhat-deploy

- .github/workflows/reusable-publish-docker.yaml
- Dockerfile
- Specify precise versions of `svm-rs`, `solc` (already there, just moved it to `ARG`) and `anchor` dependencies
- Disable github build for `linux/arm64`. This build is timing out even on the larger runner and at this point I don't want to be introducing a more complex matrix-based build outlined [here](https://docs.docker.com/build/ci/github-actions/multi-platform/). The images for `linux/arm64` are used for M1/2/3 developer machines which can build these much faster than the github machine since it needs to emulate.
> 🧹 Adjust docker build

- packages/oft-evm/contracts/NativeOFTAdapter.sol
- packages/oft-evm/test/OFT.t.sol
- Added test case for when extra `msg.value` is provided (should revert)
- Updated `InsufficientMessageValue` error to `IncorrectMessageValue` since this error will be thrown even if there is extra `msg.value` provided
- Added comments to tests
- See conversation [here](https://github.com/LayerZero-Labs/devtools/pull/838#discussion_r1738903529)
> Updated tests

- packages/oft-evm/contracts/NativeOFTAdapter.sol
- packages/oft-evm/contracts/OFTCore.sol
- Instead of changing `OFTCore.send` to be public so it can be called by `NativeOFTAdapter.send`, the body can be moved into an internal function so it can be called by both `OFTCore.send` and `NativeOFTAdapter.send`
- See conversation [here](https://github.com/LayerZero-Labs/devtools/pull/838#discussion_r1716766844)
> implemented internal _send

- .changeset/blue-brooms-talk.md
- packages/devtools-evm-hardhat/src/constants/tasks.ts
- tests/devtools-evm-hardhat-test/test/task/validate.rpcs.test.expectations/validate-incorrect-https-rpc.exp
- tests/devtools-evm-hardhat-test/test/task/validate.rpcs.test.expectations/validate-incorrect-wss-rpc.exp
- tests/devtools-evm-hardhat-test/test/task/validate.rpcs.test.expectations/validate-invalid-rpc.exp
- tests/devtools-evm-hardhat-test/test/task/validate.rpcs.test.expectations/validate-multiple-rpcs.exp
- tests/devtools-evm-hardhat-test/test/task/validate.rpcs.test.expectations/validate-rpc-for-network-without-eid.exp
- tests/devtools-evm-hardhat-test/test/task/validate.rpcs.test.expectations/validate-rpc-timeout.exp
- tests/devtools-evm-hardhat-test/test/task/validate.rpcs.test.expectations/validate-unresponsive-https-rpc.exp
- tests/devtools-evm-hardhat-test/test/task/validate.rpcs.test.expectations/validate-unresponsive-wss-rpc.exp
- tests/devtools-evm-hardhat-test/test/task/validate.rpcs.test.expectations/validate-valid-https-rpc.exp
- tests/devtools-evm-hardhat-test/test/task/validate.rpcs.test.expectations/validate-valid-wss-rpc.exp
- tests/devtools-evm-hardhat-test/test/task/validate.safe.configs.test.expectations/validate-invalid-safe-configs.exp
- tests/devtools-evm-hardhat-test/test/task/validate.safe.configs.test.expectations/validate-missing-safe-address.exp
- tests/devtools-evm-hardhat-test/test/task/validate.safe.configs.test.expectations/validate-missing-safe-url.exp
- tests/devtools-evm-hardhat-test/test/task/validate.safe.configs.test.expectations/validate-no-safe-configs.exp
- tests/devtools-evm-hardhat-test/test/task/validate.safe.configs.test.expectations/validate-valid-safe-configs.exp
- Updated task names from `lz:validate-safe-configs` and `lz:validate-rpcs` to `lz:healthcheck:validate:safe-configs` and `lz:healthcheck:validate:rpcs`, respectively.
- Updated references within tests
> 🧹 Consistent task naming

- .changeset/tall-books-jam.md
- .changeset/thirty-files-live.md
- examples/oapp/package.json
- examples/oft-adapter/package.json
- examples/oft-solana/package.json
- examples/oft/package.json
- examples/onft721/package.json
- package.json
- packages/devtools-evm-hardhat/package.json
- packages/devtools-evm-hardhat/src/runtime.ts
- packages/test-devtools-evm-hardhat/package.json
- packages/test-devtools-evm-hardhat/src/runtime.ts
- packages/toolbox-hardhat/package.json
- packages/ua-devtools-evm-hardhat/package.json
- pnpm-lock.yaml
- tests/devtools-cli-test/package.json
- tests/devtools-evm-hardhat-test/package.json
- tests/devtools-evm-test/package.json
- tests/export-deployments-test/package.json
- tests/test-evm-node/package.json
- tests/test-setup-devtools-evm-hardhat/package.json
- tests/ua-devtools-evm-hardhat-test/package.json
- tests/ua-devtools-evm-hardhat-v1-test/package.json
- In `hardhat@2.22.10` the `Environment` constructor has changed signatures so we need to update to match the new constructor
- Updated the top-level resolution for `es5-ext` after CI/CD install started complaining about the `https` dependency.
> 🪲 Fix hardhat runtime environment factory

- tests-user/tests/create-lz-oapp.bats
- `yarn` seems to suffer from concurrency issues that result in flaky user tests (see [here](https://github.com/yarnpkg/berry/issues/2847) and [here](https://classic.yarnpkg.com/lang/en/docs/cli/#toc-concurrency-and-mutex)). `YARN_CACHE_FOLDER ` environment variable has been introduced to prevent these
> 🪲 Specify YARN_CACHE_FOLDER to prevent concurrency issues with yarn installs

- .changeset/calm-spies-deny.md
- packages/devtools/src/flows/config.execute.ts
- packages/devtools/src/flows/index.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/subtask.configure.ts
- Move configuration execution subtask into a flow. This was the last subtask to be moved into a flow which means the wire task can now be moved to a flow and subsequently used by both the hardhat and the CLI implementations
> 🧹 Move configuration execution into a flow

- .changeset/slow-rats-itch.md
- packages/devtools-evm-hardhat/src/tasks/transactions/subtask.sign-and-send.ts
- packages/devtools/src/flows/config.execute.ts
- packages/devtools/src/flows/sign.and.send.ts
- packages/devtools/src/transactions/utils.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/subtask.configure.ts
After arriving at the point of being able to create the wire flow, I realized that in the current setup, the wire flow would need to pass a lot of arguments through to these flows, e.g.
- Configuration execution flow needs a configurator and an SDK factory
- Sign an send flow needs a signer factory
This would be an anti-pattern and could grow into a massive headache down the line. Instead, since the flows have not been released yet, I turned them into flow factories. This means that the internal information they need is encapsulated in a closure and the overarching flows don't need to care about the internals.
The only place that suffered is the hardhat setup where the subtasks (e.g. `SUBTASK_LZ_SIGN_AND_SEND`) now need to create and immediately execute these flows - nothing horrible, …
> 🧹 Turn existing flows into flow factories

- .changeset/slimy-pears-approve.md
- packages/devtools/src/flows/config.load.ts
- packages/devtools/test/flows/__snapshots__/config.load.test.ts.snap
- packages/devtools/test/flows/config.load.test.ts
- packages/io-devtools/src/config/loading.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/subtask.config.load.ts
- Turn `configLoadFlow` into `createConfigLoadFlow` so that some of the parameters are encapsulated in a closure. This is the last PR before the versioning PR can be unblocked and merged
> 🧹 Turn configLoadFlow into a factory

- .github/workflows/reusable-publish-docker.yaml
- Dockerfile
- We'll need Aptos CLI In order to support the legacy Aptos programs
- The `Dockerfile` has been restructured and the VM dependencies have been separated into individual stages as opposed to building everything in the `base` image
- `aptos` stage builds the Aptos CLI from specified release
- `solana` stage downloads/builds the Solana CLI from specified release, then adds `avm` and `anchor`
- `evm` stage adds `foundry`, `svm-rs` and `solc`
> 🗞️ Add support for Aptos CLI to the base development images

- .github/workflows/actions/docker-build-image/action.yaml
- .github/workflows/actions/docker-push-image/action.yaml
- .github/workflows/actions/merge-docker-image/action.yaml
- .github/workflows/reusable-publish-docker.yaml
- Dockerfile
- To better support downstream projects and provide base images that can be used with all sorts of VM tooling on both unix and macOS, we distribute the docker build on separate runners, push the digests, then merge the digests into a final image
- The docker publishing action now follows the official guidelines for distributing builds across workers [here](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners)
The action run for this PR is [here](https://github.com/LayerZero-Labs/devtools/actions/runs/11449791078). I want to make sure that it passes before I merge this.
> 🗞️ Restore docker image build for linux/arm64

- .changeset/curvy-vans-worry.md
Missed in the initial merge.  We don't publish this package anyway, so it shouldn't cause issues.
> 🧹 bump "major" version (really minor) for Solana OFT

- .github/workflows/reusable-test.yaml
- packages/devtools-solana/test/common/accounts.test.ts
- Use default Solana RPC URLs for tests for PRs coming from forks
> 🪲 Use defaults for Solana RPC URLs

- .changeset/slimy-adults-bow.md
- packages/devtools-evm-hardhat/src/omnigraph/coordinates.ts
- packages/devtools-evm-hardhat/test/omnigraph/coordinates.test.ts
- Reload the whole hardhat deploy store if we get no deployments back. This fixes an issue currently present in Stargate
- Fixed a small issue with the test - a `spy` was initialized on the top of the test suite but was effectively erased in the `afterEach` hook
> 🪲 Fix an issue with outdated hardhat cache

- packages/test-devtools-ton/jest.config.js
- The TON local node tests depend on the quality of the machine that runs the node so we bump the timeout to remove any flakiness
> 🧹 Bump timeout on TON node tests

- packages/devtools-evm-hardhat/test/cli.test.ts
- There was a failing test in [this CI run](https://github.com/LayerZero-Labs/devtools/actions/runs/11511605645/job/32045294959) that had to do with test preconditions not being strong enough. In this case a string (`"106 "`) that does not represent a valid key on `EndpointId` enum is passed through `parseInt` and becomes `106`, a valid `EndpointId`
> 🪲 Test assumptions

- Dockerfile
- Our Solana stack is using `anchor@0.29.0` so we match that version with the version in the `Dockerfile`
> 🧹 Downgrade anchor in the base image

- .devcontainer/README.md
- .devcontainer/devcontainer.local.json
- Use the prebuilt base images in the devcontainer by default
> 🧹 Prebuilt devcontainer images

- .github/workflows/actions/docker-build-image/action.yaml
- Create cache artifacts in GHCR instead of the GHA cache. This means that the layers of all, including the intermediate, images will be uploaded to GHCR
- The cache will try to use the layers built for its branch will fallback to the `main` branch cache
> 🧹 Docker cache

- .changeset/modern-melons-ring.md
- packages/export-deployments/src/cli.ts
- packages/export-deployments/src/cli/options.ts
- tests/export-deployments-test/test/export.test.expectations/export-exclude.exp
- tests/export-deployments-test/test/export.test.ts
- The `--exclude-files` CLI options has not been typed correctly in the CLI action handler and the provided test case has not been plugged into the test runner 🤦🏻
> 🪲 Fix a typo with CLI option name for export-deployments

- packages/build-devtools/.eslintignore
- packages/build-devtools/.eslintrc.json
- packages/build-devtools/README.md
- packages/build-devtools/jest.config.js
- packages/build-devtools/package.json
- packages/build-devtools/src/index.ts
- packages/build-devtools/src/tsup/declarations.ts
- packages/build-devtools/src/tsup/index.ts
- packages/build-devtools/test/tsup/declarations.test.ts
- packages/build-devtools/tsconfig.build.json
- packages/build-devtools/tsconfig.json
- packages/build-devtools/tsup.config.ts
- pnpm-lock.yaml
- tsconfig.json
- turbo.json
- Simple setup to get local declaration maps working. These will not be published with packages - the declaration map build will only be triggered in non-`production` node environments
- The following PRs can plug this `esbuild` plugin to their `tsup.config.ts` and benefit
- The declaration maps currently rely on bundled files (i.e. files in `dist`) following the same directory structure as files in `src`. Any advanced mapping in `tup.config.ts` can and probably will break the declaration files.
- The declaration build will now run once for every build target (`esm`, `cjs`) which is not ideal
> 🗞️ Declaration maps for local development

- .dockerignore
- Add `.netrc` and `.env*` to `.dockerignore` as a precaution - the images are built on isolated machines without these files but one never knows
> 🧹 Stay on the safe side and docker ignore all .env & .netrc files

- .changeset/sharp-knives-jam.md
- examples/oft-solana/tasks/solana/createOFT.ts
metaplex's `mpl-token-metadata` has a very _strange_ implementation which converts `undefined` to `1` for `mintV1` instruction.  This is really non-intuitive.  As such, if you want to mint 0, you need to elide the mintV1 instruction altogether.
See: https://github.com/metaplex-foundation/mpl-token-metadata/blob/main/clients/js/src/generated/instructions/mintV1.ts#L115
This change fixes #926
> 🪲createOFT should allow mint=0

- turbo.json
- `NODE_ENV` should not be a pass-through variable since it might have effects on the build artifacts
> 🪲 NODE_ENV in turbo

- .changeset/clean-stingrays-drop.md
- packages/build-devtools/src/tsup/declarations.ts
- packages/build-devtools/test/tsup/declarations.test.ts
- The `build-devtools` package's `enabled` option was being defaulted wrongly - it should be disabled in production environment by default
> 🪲 Wrong default enabled value for declaration map plugin

- docker-compose.registry.yaml
- tests-user/tests/build-lz-options.bats
- tests-user/tests/create-lz-oapp.bats
- tests-user/tests/decode-lz-options.bats
- tests-user/tests/devtools-cli.bats
- tests-user/tests/devtools-evm-hardhat-export-deployments.bats
- tests-user/tests/verify-contract.bats
- Unfortunately `cargo` and `npx` are not yet ready to be fully parallelized on one machine due to the cache behavior. Even though the user tests parallelization brought down the pipeline runtime for the happy case, the fact that it became flaky makes it actually run longer on average (due to required reruns)
> 🧹 Disable parallel user tests

- .github/workflows/reusable-test.yaml
- The Solana tests which are running against real deployed programs started misbehaving. We'll disable them on the CI until we spin up a local node and deploy a stable program
> 🪲 Disable solana tests on the CI

- .changeset/serious-lizards-thank.md
- packages/io-devtools/src/async/index.ts
- packages/io-devtools/src/async/time.ts
- packages/io-devtools/src/index.ts
- packages/verify-contract/src/common/etherscan.ts
- packages/verify-contract/src/common/promises.ts
- Moving the `sleep()` helper to `io-devtools` so we can reuse
> 🗞️ Move sleep() helper to io-devtools

- .github/workflows/reusable-test.yaml
- Use the prebuilt TON node image for testing
> 🧹 Use prebuilt TON node image

- .changeset/clean-turtles-hide.md
- packages/devtools/src/common/promise.ts
- packages/devtools/src/omnigraph/config.ts
- The `serial`/`parallel` applicative is chosen based on an feature flag coming from an environment variable. This isolates this small piece of functionality to be reused outside of `createConfigureMultiple`
> 🧹 Add createDefaultApplicative utility

- docker-compose.registry.yaml
- Local unreleased changes were not being published when running user tests since `.changeset/*.md` files were ignored in `.dockerignore` and no volume has been mounted for them
> 🪲 Changesets were being ignored in user tests

- docker-compose.registry.yaml
- Temporary fix for user tests version bumping/publishing flow
- The issue is described in the updated `docker-compose.registry.yaml` file
> 🪲 User tests publishing flow hotfix

- .changeset/big-seals-collect.md
- packages/create-lz-oapp/src/config.ts
- packages/create-lz-oapp/src/index.tsx
- packages/create-lz-oapp/src/options.ts
- packages/create-lz-oapp/src/utilities/prompts.ts
- packages/create-lz-oapp/test/config.test.ts
- packages/create-lz-oapp/tsconfig.json
- The `native-oft-adapter` example object in `create-lz-oapp` was not using the `ref`. This caused the user tests to fail since the example was always being pulled from `main`
- The `EXAMPLES` (and `AVAILABLE_PACKAGE_MANAGERS`) constants were turned into functions for more convenient testing
- Tests were added
> 🪲 Add missing ref option to native OFT adapter example in create-lz-oapp

- .github/workflows/reusable-publish-docker.yaml
- Dockerfile
- docker-compose.local.yaml
- docker-compose.templates.yaml
- docker-compose.yaml
- Add a `Dockerfile` target for Aptos local node image
- Add a build step to the docker publishing workflow
- Add templates to the compose setup - for now we won't make the `network-aptos` a dependency of `tests` since we don't have any tests yet
The action run for this change is [here](https://github.com/LayerZero-Labs/devtools/actions/runs/11806130469)
> 🗞️ Aptos node image

- .github/workflows/reusable-test.yaml
- `actions/upload-artifact@v3` is deprecated and being phased out. This PR updates to `v4`
> 🧹 Update artifact action version

- tests/ua-devtools-evm-hardhat-test/test/task/oapp/wire.test.ts
- Adjust `logLevel` for wire tests to reduce the amount of console.logs in the test report
- Drop a test that does not test much (it was useful in the beginning)
> 🧹 Less logging

- .changeset/real-buttons-deny.md
- packages/oapp-evm/test/OApp.t.sol
- packages/oapp-evm/test/mocks/ERC20Mock.sol
- packages/oapp-evm/test/mocks/OAppMock.sol
Added `ERC20Mock` and `OAppMock` to `test/mocks` for `OApp.t.sol`
Tested `OApp` across `OApp.endpoint().send()` and `OApp.send()`
> Added `oapp-evm` testing

- .changeset/brown-kings-grin.md
- packages/devtools/src/flows/index.ts
- packages/devtools/src/flows/wire.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/index.ts
- tests/ua-devtools-evm-hardhat-test/test/task/oapp/wire.test.ts
- Moving the OApp wiring logic into a platform-agnostic place (i.e. not a hardhat-specific one) to be reused by both the hardhat and the standalone CLIs
> 🗞️ Standalone CLI: Moving wiring logic into a flow

- packages/oapp-evm-upgradeable/package.json
- packages/oapp-evm/package.json
- packages/oft-evm-upgradeable/package.json
- packages/oft-evm/package.json
"compile": "$npm_execpath forge build" is now     "compile": "forge build",
Reason: `forge` is not a yarn command
> 🧹 $npm_execpath forge -> forge in package.json

- packages/oapp-alt-evm/.gitignore
- packages/oapp-alt-evm/README.md
- packages/oapp-alt-evm/artifacts/IOAppComposer.sol/IOAppComposer.json
- packages/oapp-alt-evm/artifacts/IOAppCore.sol/IOAppCore.json
- packages/oapp-alt-evm/artifacts/IOAppMsgInspector.sol/IOAppMsgInspector.json
- packages/oapp-alt-evm/artifacts/IOAppOptionsType3.sol/IOAppOptionsType3.json
- packages/oapp-alt-evm/artifacts/IOAppReceiver.sol/IOAppReceiver.json
- packages/oapp-alt-evm/artifacts/OAppAlt.sol/OAppAlt.json
- packages/oapp-alt-evm/artifacts/OAppCore.sol/OAppCore.json
- packages/oapp-alt-evm/artifacts/OAppOptionsType3.sol/OAppOptionsType3.json
- packages/oapp-alt-evm/artifacts/OAppReceiver.sol/OAppReceiver.json
- packages/oapp-alt-evm/artifacts/OAppSender.sol/OAppSender.json
- packages/oapp-alt-evm/artifacts/OAppSenderAlt.sol/OAppSenderAlt.json
- packages/oapp-alt-evm/artifacts/OptionsBuilder.sol/OptionsBuilder.json
- packages/oapp-alt-evm/artifacts/RateLimiter.sol/RateLimiter.json
- packages/oapp-alt-evm/contracts/oapp/OAppAlt.sol
- packages/oapp-alt-evm/contracts/oapp/OAppSenderAlt.sol
- packages/oapp-alt-evm/foundry.toml
- packages/oapp-alt-evm/package.json
- packages/oapp-alt-evm/test/OAppAlt.t.sol
- packages/oapp-alt-evm/test/mocks/OAppAltMock.sol
- pnpm-lock.yaml
Regular OApps don't work with alt-endpoints which use a ERC20 as the native fee token instead of the local native token either because it has no monetary value or because it is a ERC20 token instead of a native token. 
This package contains the bare OApp implementation for AltEndpoints.
> 🗞️ packages/oapp-alt-evm - for alt endpoint oapps

- .changeset/shy-beds-call.md
- examples/oapp/package.json
- Use `concurrently` to parallelize the `compile` scripts in examples
- The shortcut `pnpm:compile:*` version of concurrently command cannot be used since examples might use different package managers
> 🧹 Use concurrently for parallel compilation

- examples/native-oft-adapter/test/hardhat/MyNativeOFTAdapter.test.ts
- examples/native-oft-adapter/test/hardhat/MyOFT.test.ts
- examples/oapp-read/test/hardhat/MyOAppRead.test.ts
- examples/oapp/test/hardhat/MyOApp.test.ts
- examples/oft-adapter/test/hardhat/MyOFTAdapter.test.ts
- examples/oft-solana/test/hardhat/MyOFT.test.ts
- examples/oft-upgradeable/test/hardhat/MyOFTUpgradeable.test.ts
- examples/oft/test/hardhat/MyOFT.test.ts
- examples/onft721/test/hardhat/MyONFT721.test.ts
- examples/uniswap-read/test/hardhat/UniswapV3QuoteDemo.test.ts
- This is the first PR in a series aimed at synchronizing the linting rules with `@layerzerolabs/eslint-config-next` (so that we can update the packages that are now stuck on version `2.3.39`), with smaller ESLint warnings addressed
> 🧹 ESLint update journey: fixing small warnings [1/N]

- packages/devtools/test/bytes.test.ts
- Improve the fuzz test filtering logic to fix a test failing for `[0,1] and `[1]` - the leading zeros in the first array were making the test precondition pass but since leading zeros can be discarded, the two `UInt8Array`s are actually the same and the precondition should have failed. The failing action run can be found [here](https://github.com/LayerZero-Labs/devtools/actions/runs/11941113443/job/33285243844?pr=1059)
> 🪲 Fix bytes test

- examples/oft-solana/README.md
- link to official Solana setup (Rust, Solana, Anchor)
- Solana private key instructions
- TESTNET naming clarification
- deploy command correction: `mainnet-beta` to `devnet`
> docs(examples/oft-solana): elaborate

- examples/oft-solana/README.md
Changes
- removed link to official solana.com installation guide as that will lead to installing Solana CLI v2 which we don't yet support. 
- instead, list directly instructions to install Rust, Solana, Anchor.
- explainer on priority fees
- provide command to deploy with priority fees
Not yet included:
- how to estimate priority fees
> docs(oft-solana): explain required versions for Solana CLI and mention priority fees

- examples/oft-solana/tasks/evm/send.ts
- current README says to use MyOFTMock if on testnet, as that exposes a mint function
- but then when running the `send` script, there would be an error as the name of the contract is hardcoded as `MyOFT`
- this PR turns contract name into a param, with a default value of `MyOFT`
TODO after this PR is merged: update doc to mention this new optional param, especially if using MyOFTMock
> feat(examples/oft-solana/tasks/evm/send.ts): turn contractName into param with default value

- examples/oft-solana/README.md
Right now, if you follow the instructions to the tee, you will run into an error regarding `token_source` when trying to send from Solana to Sepolia. This is because there are no tokens yet on Solana. We need to mint first on Solana.
> docs(oft-solana/README): include missing mint instructions for Solana

- examples/oft-solana/README.md
- in some instances, users might not have `solana-install` so defaulting to fetch from source is more reliable
Thanks to @DanL0 for flagging this
> docs(oft-solana): remove usage of solana-install

- examples/oft-solana/README.md
AVM requires higher rust version and it is incompatible with our rust-toolchain.yaml
> remove AVM instruction

- examples/oft-solana/README.md
- examples/oft-solana/tasks/common/wire.ts
- examples/oft-solana/tasks/solana/createOFT.ts
- examples/oft-solana/tasks/solana/setAuthority.ts
1. get priority fees command was missing "lz:" prefix so it was broken
2. show meaningful error if wire command is running without solana program id
before: `error:   [OApp] Failed to check OApp configuration: TypeError: Cannot read properties of undefined (reading 'toBase58')`
after: `error:   Missing --solana-program-id CLI argument`
3. fix --only-oft-store param instruction
> fix CLI commands instruction in solana 

- .changeset/eight-llamas-deny.md
- packages/ua-devtools-evm/src/read/commandResolver/compute/sdk.ts
The existing logic evaluates static compute setting values as conditions for ternary expressions, which will always evaluate truthy. They should instead be comparing the existing compute setting to their static counterparts.
> 🧹 Fix logic to compare compute setting to static counterparts, rather than evaluating static ComputeSetting directly

- examples/oft-solana/layerzero.config.ts
- removing receiveLibraryTimeoutConfig from solana to sepolia entry in example
- this is not yet supported, and as @ryandgoulding pointed out, not needed as on Solana there's only one receive library right now
- leaving it in can lead to some devs (who uncomment it) experiencing a confusing error, as one did today. they faced `Error: An error occurred while getting the OApp configuration: TypeError: getReceiveLibraryTimeout() not implemented on Solana Endpoint SDK
` when running the wire command
> docs(solana): remove receiveLibraryTimeoutConfig

- examples/oft-solana/Cargo.lock
- examples/oft-solana/programs/endpoint-mock/Cargo.toml
- examples/oft-solana/programs/oft/Cargo.toml
This pull request addresses a potential vulnerability in the `oapp` library by updating its dependencies to the latest commit.
The vulnerability fix in oapp can be found here: [34321ac](https://github.com/LayerZero-Labs/LayerZero-v2/commit/34321ac15e47e0dafd25d66659e2f3d1b9b6db8f)
This update ensures that the `oapp` library is secure and up-to-date with the latest dependency versions.
> Solana: Update oft dependencies

- .changeset/nice-buttons-work.md
- packages/oft-evm/contracts/MintBurnOFTAdapter.sol
- packages/oft-evm/contracts/interfaces/IMintableBurnable.sol
- packages/oft-evm/test/OFT.t.sol
- packages/oft-evm/test/lib/MintBurnOFTAdapterMockCodec.sol
- packages/oft-evm/test/mocks/ElevatedMinterBurnerMock.sol
- packages/oft-evm/test/mocks/MintBurnERC20Mock.sol
- packages/oft-evm/test/mocks/MintBurnOFTAdapterMock.sol
This PR introduces the audited `MintBurnOFTAdapter` example to the `oft-evm` package and updates the relevant tests to ensure its proper functionality. The `MintBurnOFTAdapter` provides a generic solution for integrating tokens that utilize mint and burn mechanisms into the LayerZero Omnichain Fungible Token (OFT) framework.
Added `MintBurnOFTAdapter` Contract:
- Implemented an abstract contract `MintBurnOFTAdapter` that inherits from `OFTCore`.
- Provides implementations for the `_debit` and `_credit` functions using `mint` and `burn` operations via a `IMintableBurnable` interface.
- Designed to work with tokens that have mintable and burnable capabilities, facilitating cross-chain transfers without the need for token approvals.
Updated Tests:
- Added new test cases to cover the …
> 🗞️ Add MintBurnOFTAdapter.sol to oft-evm package

- examples/oft-solana/README.md
1. existing script to get prioritization fees is a hit and miss (a lot of misses)
2. some partners have recently been blocked due to the script returning 0 for all values
3. the existing script is ideal for when we want to send transactions that write to an account that already exists, but not for deploying programs
> fix: update to refer to QuickNode dashboard

- examples/oft-solana/README.md
- examples/oft-solana/tasks/solana/createOFT.ts
Currently, if a Solana OFT is created with `--only-oft-store true`, the Freeze Authority for the token is set to the Multisig Account. Most projects would like the Freeze Authority to be renounced. We should have this as the default when `--only-oft-store true` is selected.
I tested on devnet:
```
pnpm hardhat lz:oft:solana:create --eid 40168 --program-id CAVtbZAtbkerztLHC6Xary6KDmgdNnv1cDBEctVdNEY2 --only-oft-store true
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
(node:15320) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ You have chosen `--only-oft-store true`. This means that only the OFT Store will be able to mint …
```
> feat(oft-solana): if only oft store, set freeze authority immediately to none

- .changeset/bright-beds-train.md
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.ts
#988 introduced a regression where `to.address` is used when it should be `from.address`.  This caused inappropriate values to be returned to the CLI for the `lz:oapp:config:get` task only.  It did not affect the wiring task which did not suffer the same bug.
This was tested against a testnet deployed OFT to ensure proper functionality of the task was restored.
> 🪲 config get regression

- .changeset/green-trainers-scream.md
- packages/protocol-devtools-solana/src/endpointv2/sdk.ts
Currently, the Solana EndpointV2SDK uses the local hot wallet as the `admin` all of the time.  Although this works well when the OFT is owned by an EOA, it is 100% incorrect after an alternative delegate has been set.
This change swaps in the `delegate` in appropriate places, fixing the bug.
> 🪲 Solana EndpointV2SDK should use `delegate` as the `admin`

- .changeset/new-horses-pull.md
- packages/metadata-tools/src/config-metadata.ts
- packages/metadata-tools/src/types.ts
- packages/metadata-tools/test/data/solana-mainnet.json
- packages/metadata-tools/test/data/solana-testnet.json
Offchain team returns now proper executor address in metadata endpoint, so we can make our metadata-tools package fully working for EVM <> Solana scenarios.
Generated config output confirmed by local test suite ([snapshot](https://github.com/LayerZero-Labs/devtools/blob/main/packages/metadata-tools/test/__snapshots__/config-metadata.test.ts.snap)).
> add solana support to metadata-tools

- examples/oft-solana/tasks/solana/createOFT.ts
- examples/oft-solana/tasks/solana/multisig.ts
- examples/oft-solana/tasks/solana/setAuthority.ts
Testing:
```
LZ_ENABLE_SOLANA_OFT_EXAMPLE=1 LAYERZERO_EXAMPLES_REPOSITORY_REF=#fix/compute-price-multisig-creation npx create-lz-oapp@latest
```
Test OFT with only OFT store = true:
multisig: https://explorer.solana.com/address/5dnMbnXh9zGNNCcviCndF6eR45RLUfagRqbNXZwz8Zjw?cluster=devnet (it can be seen it correctly has only oftStore as signer)
deployment:
```
{
"programId": "EiLAuRV68vj8KLQ6JuRQVs78hQRszcYHVz2fEYtnd3Yv",
"mint": "CjeHnKTgAoc6gLmdWcfrRE5FERj1F6JsnaN9d2rFpq8r",
"mintAuthority": "5dnMbnXh9zGNNCcviCndF6eR45RLUfagRqbNXZwz8Zjw",
"escrow": "HcgW66FnUS22bhqVQfjAFUhW64QaejHXBTHmcPsq3hBZ",
"oftStore": "GmLWtaEk3atQDppohN8QAVpBzXJHAUJj5canshRWbXZ6"
}
```
Another create oft run to check if compute price is now applied correctly (manually added logs):
```
➜  solana-msig-cp …
```
> compute price scaling in multisig creation

- examples/oft-adapter-aptos-move/test/evm/foundry/MyOFT.t.sol
- examples/oft-aptos-move/test/evm/foundry/MyOFT.t.sol
Fixes pnpm "compile" script for "oft-aptos-move" and "oft-adapter-aptos-move" examples.
> 🪲 rm unnecessary view

- examples/oft-solana/tasks/solana/createOFT.ts
To test:
```
LZ_ENABLE_SOLANA_OFT_EXAMPLE=1 LAYERZERO_EXAMPLES_REPOSITORY_REF=#nazreen/oft-solana/rm-unnecessary-multisig-creation npx create-lz-oapp@latest
```
Test results:
When: no additional minters, Mint Authority is OFT Store
Mint: https://solscan.io/account/LbLqBcGtLQ55X13XWM35FS1rG3v1kdH3amXa9MWqxqs?cluster=devnet 
Multisig: not created
Successful cross chain transfers: 
- Solana to Sepolia -> https://testnet.layerzeroscan.com/tx/2RkNWRxcRtZW2zQzMtk5CYKfnAiDGM56Xcpgman7S6Wf39GiRVLa5nLWt6gLNtdSswu2X3UuBGJL4kMs8m7ivSwp 
- Sepolia to Solana -> https://testnet.layerzeroscan.com/tx/0xca6106aaefd9aacfb3a974aece249e9b8e605d1f028516b0fb2d240d72344bab 
When: additional minters provided, Mint Authority is Multisig
Mint: https://solscan.io/token/2H1PMNrahdQjZMpXfv7fdaFyuQjnJXHh7yAwxRqe2Zvc?cl …
> feat(oft-solana): don't create multisig if no additional minters

- tests/devtools-evm-hardhat-test/test/task/validate.rpcs.test.ts
These tests use live rpcs which are blocking our CI.
> 🪲temporarily disable rpc validation tests

- .changeset/strange-apricots-deny.md
- packages/metadata-tools/src/config-metadata.ts
- packages/metadata-tools/test/config-metadata.test.ts
- packages/metadata-tools/test/data/fuji.json
`metadata-tools` can be used in `layerzero.config.ts` to `generateConnectionsConfig`. However if deprecated DVNs are listed, they are not properly filtered out and running `pnpm hardhat lz:oapp:wire` sometimes wires up their oapp to the deprecated dvn which will cause transactions to be inflight indefinitely.
___
In https://metadata.layerzero-api.com/v1/metadata/deployments
we can see config like
```
"dvns": {
"0x3ed2211f49ce343d70cb8ded927ca6c4a6198101": {
"version": 2,
"canonicalName": "Bitgo",
"id": "bitgo"
},
"0xdd1da938b19614d6db8c3973c89908df234ad1ce": {
"version": 2,
"canonicalName": "IntellectEU"
},
"0xe67ef84173d024603a844c4aea6a3a15ccccc32c": {
"version": 2,
"canonicalName": "Blockdaemon",
"id": "blockdaemon"
},
"0xd44e25bea2bedcceceb7e104d5843a55d208e8a9": {
"version": 2, …
```
> Update DVNsToAddresses to filter out deprecated dvns

- .changeset/selfish-chairs-roll.md
- package.json
- packages/build-devtools/package.json
- packages/create-lz-oapp/package.json
- packages/devtools-evm-hardhat/package.json
- packages/devtools-evm/package.json
- packages/devtools-solana/package.json
- packages/devtools/package.json
- packages/export-deployments/package.json
- packages/io-devtools/package.json
- packages/metadata-tools/package.json
- packages/protocol-devtools-evm/package.json
- packages/protocol-devtools/package.json
- packages/ua-devtools-evm/package.json
- packages/ua-devtools/package.json
- packages/verify-contract/package.json
- tests/devtools-cli-test/package.json
- tests/devtools-evm-test/package.json
- tests/export-deployments-test/package.json
- tests/ua-devtools-evm-hardhat-v1-test/package.json
- turbo.json
For now, we will not include the following packages for "test:jest":
* devtools-ton: expects a TON node to be running, which our CI system does not currently perform.
* test-devtools-ton: same as above
* devtools-evm-hardhat-test: rarely changes
* ua-devtools-evm-hardhat-test:  same as above
> add a jest-only target to make snapshot tests easier to run

- .changeset/swift-days-cheat.md
- examples/oft-solana/tasks/solana/createOFT.ts
- examples/oft-solana/tasks/solana/createOFTAdapter.ts
- examples/oft-solana/tasks/solana/index.ts
- examples/oft-solana/tasks/solana/multisig.ts
- examples/oft-solana/tasks/solana/sendOFT.ts
- examples/oft-solana/tasks/solana/setAuthority.ts
We've found that in times of network congestion, the RPC method that supports the `getSimulationComputeUnits` function would fail, resulting in scripts being stuck as every transaction currently relies on `getSimulationComputeUnits`.  This blocks the deployment of Solana OFTs.
Given that as part of a Solana OFT deployment, we are executing a standard set of instructions, we can introduce a fallback by way of hardcoded CU estimates for each transaction type. The following is introduced into `examples/oft-solana/tasks/solana/index.ts`:
```
export enum TransactionType {
CreateToken = 'CreateToken',
CreateMultisig = 'CreateMultisig',
InitOft = 'InitOft',
SetAuthority = 'SetAuthority',
InitConfig = 'InitConfig',
SendOFT = 'SendOFT',
}
const TransactionCuEstimates: Record<TransactionType, …
```
> feat(oft-solana): add fallback for when `getSimulationComputeUnits` fails

- examples/lzapp-migration/foundry.toml
- examples/mint-burn-oft-adapter/foundry.toml
- examples/oapp/foundry.toml
- examples/oft-adapter/foundry.toml
- examples/oft/foundry.toml
- examples/onft721-zksync/foundry.toml
- examples/onft721/foundry.toml
https://x.com/gakonst/status/1881802255202193584
> In the coming weeks, we'll be shipping our last few breaking changes to Foundry (e.g., turning off the optimizer by default, which was recently shipped).
> chore: add optimizer and optimizer runs since foundry disabled optimizer on default

- examples/oft-aptos-move/README.md
- packages/devtools-move/cli/operations/evm-wire.ts
- packages/devtools-move/tasks/evm/utils/types.ts
- packages/devtools-move/tasks/evm/wire-evm.ts
- packages/devtools-move/tasks/evm/wire/transactionExecutor.ts
1. using `--only-calldata` as an execution mode skips transaction submission and only logs in transactions under `/transactions/${--oapp-config}/calldata/run-id.json`
2. Testnets have flaky `gasLimit` and may not always pass. Defaulting on a million (`1_000_000`) should it fail (don't worry the excess gas is refunded, also this is mostly for testnets)
> feat: calldata as an execution mode + default gasLimit 

- packages/devtools-move/tasks/evm/wire-evm.ts
- packages/devtools-move/tasks/evm/wire/setReceiveConfig.ts
- packages/devtools-move/tasks/evm/wire/setReceiveLibrary.ts
- packages/devtools-move/tasks/evm/wire/setSendConfig.ts
- packages/devtools-move/tasks/evm/wire/setSendLibrary.ts
- packages/devtools-move/tasks/evm/wire/transactionExecutor.ts
1. Fixed bug where send and receive libraries would call getDefaultSend/ReceiveLibrary when this is not a valid endpoint v2 function
2. Handling case when using default library fetched from the endpoint and the library is not specified in the lz config
3. calldata no longer requires a private key or mneumonic. it also skips forking
> Fix/rebase aptos examples/config setting epv2 default library

- examples/oft-aptos-move/package.json
- packages/devtools-move/cli/init.ts
- packages/devtools-move/cli/operations/evm-transaction-parser.ts
Since transaction objects may contain 100+ transactions for several eid mappings. This operation was added to make it easier to filter through such massive objects.
`pnpm run lz:sdk:evm:transaction-parser  --oapp-config <value>  --mode <value> --id <value> --src-eid <value> --dst-eid <value>`
where 
1. `--oapp-config` is your layerzero config file
2. `--mode` is either `broadcast`, `dry-run`, or `calldata`
3. `--id` is your the run id 
these are required because of how the transaction folder is structured. it is 
`transactions/oappconfig/mode/runid.json`
> helper function to filter through large transaction objects

- packages/devtools-move/tasks/evm/utils/types.ts
- packages/devtools-move/tasks/evm/wire/transactionExecutor.ts
indexing TxPool by `fromEid` instead of `toEid`. Using `toEid` leads to overwrites on a `<n,1>` mapping of transactions.
> fix: indexing the transaction object on from eid instead of to eid

- .changeset/rude-snails-serve.md
- examples/oft-solana/tasks/solana/sendOFT.ts
Currently, if a dev tries to run the sendOFT.ts script with an amount greater than the balance of their deployer address, they will be faced with an error like so:
```bash
SendTransactionError: Simulation failed. 
Message: Transaction simulation failed: Error processing Instruction 2: custom program error: 0x1. 
Logs: 
[
"Program ComputeBudget111111111111111111111111111111 success",
"Program 13DZBdTFGrhYCcgKFx7ensYs1yBLgGwXdD7kzRA9tU2v invoke [1]",
"Program log: Instruction: Send",
"Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]",
"Program log: Instruction: Burn",
"Program log: Error: insufficient funds",
"Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4171 of 227697 compute units",
"Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: custom program …
```
> feat(oft-solana): throw specific error if trying to send more than owned

- examples/oapp/test/foundry/MyOApp.t.sol
- packages/test-devtools-evm-foundry/contracts/TestHelperOz5.sol
Problem:
- Current TestHelper creates various endpoints, but the are all created on the same network
- The emulate message sending, but never leave the current network
- There is no way to test omnichain applications using already deployed contracts on forked chains
Solution:
The solution we came up with @shankars99 have these advantages:
1- It let you create and configure one endpoints for each fork you want to test
2- ensures oapps wires up thru the forks
3- It will let ppl test messaging and interact with already deployed contracts
Example usage:
- There is a MyOapp.t.sol that works
- Production example could be if you want a messaging system and you need to use Oracles or usa Uniswap to exchange, or any other contract that is already deployed and you want to test with those contracts. …
> Testing on forked chains

- examples/lzapp-migration/.eslintrc.js
- examples/mint-burn-oft-adapter/.eslintrc.js
- examples/native-oft-adapter/.eslintrc.js
- examples/oapp-read/.eslintrc.js
- examples/oapp/.eslintrc.js
- examples/oft-adapter/.eslintrc.js
- examples/oft-solana/.eslintrc.js
- examples/oft-upgradeable/.eslintrc.js
- examples/oft/.eslintrc.js
- examples/onft721-zksync/.eslintrc.js
- examples/onft721/.eslintrc.js
- examples/uniswap-read/.eslintrc.js
Currently, sometimes in feature branches, the following error may appear in one of the example repos:
```
ESLint: 8.57.1
ESLint couldn't determine the plugin "@typescript-eslint" uniquely.
- /__w/devtools/devtools/node_modules/.pnpm/@typescript-eslint+eslint-plugin@7.7.1_@typescript-eslint+parser@7.7.1_eslint@8.57.1_typescript@5.5.3/node_modules/@typescript-eslint/eslint-plugin/dist/index.js (loaded in ".eslintrc.js » @layerzerolabs/eslint-config-next/recommended")
- /__w/devtools/devtools/node_modules/.pnpm/@typescript-eslint+eslint-plugin@7.7.1_@typescript-eslint+parser@7.7.1_eslint@8.57.1_typescript@5.7.3/node_modules/@typescript-eslint/eslint-plugin/dist/index.js (loaded in "../../.eslintrc.json")
Please remove the "plugins" setting from either config or remove either plugin …
```
> fix(eslint): add `root: true` to example directories

- packages/test-devtools-evm-foundry/contracts/mocks/ABAMock.sol
- packages/test-devtools-evm-foundry/contracts/mocks/BatchSendMock.sol
- packages/test-devtools-evm-foundry/contracts/mocks/ComposerMock.sol
- packages/test-devtools-evm-foundry/contracts/mocks/OmniCounterMock.sol
- packages/test-devtools-evm-foundry/test/foundry/ABA.t.sol
- packages/test-devtools-evm-foundry/test/foundry/BatchSend.t.sol
- packages/test-devtools-evm-foundry/test/foundry/Composer.t.sol
- packages/test-devtools-evm-foundry/test/foundry/OmniCounter.t.sol
The goal of this PR is to create more advanced testing scenarios for our TestHelper so we feel more confident merging improvements to it, eg.: https://github.com/LayerZero-Labs/devtools/pull/1164
OmniCounter tests have been ported with fixes from: https://github.com/LayerZero-Labs/LayerZero-v2/blob/main/packages/layerzero-v2/evm/oapp/test/OmniCounter.t.sol
Other patterns tests were ported from: https://github.com/St0rmBr3w/layerzero-design-patterns
> add more Foundry tests, including ABA, lzCompose

- package.json
- pnpm-lock.yaml
Continuing the work of #1234 
This plugin being outdated is the source of this intermittent error in feature branches:
```
TypeError: Failed to load plugin 'turbo' declared in '.eslintrc.json » ../../.eslintrc.json': Cannot convert undefined or null to object
at Function.entries (<anonymous>)
at /__w/devtools/devtools/node_modules/.pnpm/eslint-plugin-turbo@1.12.3_eslint@8.57.1/node_modules/eslint-plugin-turbo/dist/index.js:74:6699
at Array.forEach (<anonymous>)
at Ii.generateKey (/__w/devtools/devtools/node_modules/.pnpm/eslint-plugin-turbo@1.12.3_eslint@8.57.1/node_modules/eslint-plugin-turbo/dist/index.js:74:6665)
at new Ii (/__w/devtools/devtools/node_modules/.pnpm/eslint-plugin-turbo@1.12.3_eslint@8.57.1/node_modules/eslint-plugin-turbo/dist/index.js:74:6088)
at Object.<anonymous> …
```
> chore: update eslint-plugin-turbo

- examples/oft-solana/README.md
As we are using Solana CLI `v1.17.31`, the program deploy command would be allocating twice the size of the program bytecode, which leads to needing twice the amount of rent. On mainnet this can be costly.
Currently, rent for the exact program bytecode size is around 3.8 SOL so 2x this would be 7.6 SOL. At $200 per SOL, that's $760 and $1520 respectively.
This behavior was changed in `v1.18` to require only the exact size of the program bytecode.
To emulate this, we can use the `--max-len` flag and passing it the actual size of the program bytecode.
The alternative to using this flag is to ask the dev to switch to v1.18 temporarily when deploying, which might also be beneficial in that it then allows the user to directly specify a priority fee.
> oft-solana: instruction uses --max-len

- examples/oft-solana/package.json
- examples/oft-solana/tasks/solana/createOFTAdapter.ts
- examples/oft-solana/tasks/solana/setOutboundRateLimit.ts
- pnpm-lock.yaml
Currently, package.json has the following
```
"@layerzerolabs/oft-v2-solana-sdk": "3.0.0",
```
This was locking (exact versioning) the Solana OFT SDK version to 3.0.0, which led our versioning bot to not update it. This PR fixes it by using caret versioning starting from the update that has the updated exports.
this is related to https://github.com/LayerZero-Labs/devtools/pull/1252
> fix(oft-solana): un-lock solana oft sdk version and update imports

- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .github/README.md
- .github/workflows/actions/install-dependencies/action.yaml
- .github/workflows/actions/setup-build-cache/action.yaml
- .github/workflows/reusable-publish.yaml
- .github/workflows/reusable-test.yaml
- Dockerfile
With the devtools image workflow changed and re-published on a tag with `:main` <https://github.com/LayerZero-Labs/devtools/actions/runs/13273422696>
This PR updated the image tagging from using a specific tag from a (now deleted) branch 
`shankar-create_images_for_both_architectures` that was used during the PR for the devtools image+workflow fix - <https://github.com/LayerZero-Labs/devtools/pull/1257> 
The old image tagged `main`:
https://github.com/LayerZero-Labs/devtools/pkgs/container/devtools-dev-base/304693620
And some documentation and comments as a bonus
> chore: update workflow to match images

- .github/workflows/actions/setup-build-cache/action.yaml
This is breaking since it was made architecture-dependent. Rather than try to fix, just disable the cache right now.
> 🪲 temporarily remove hardhat cache

- .changeset/lucky-trainers-yawn.md
- examples/oft-solana/README.md
This PR simplifies the DevEx by removing branches/forks in the path through defaulting instructions to using Solana 1.18 for deployment, which is always the case internally.
Changes:
- remove the need for the `--max-len` flag
- happy path instructions include deploying with priority fee by default (improved DevEx)
This README can now be more linear in reading experience.
> feat: default to using solana 1.18

- .changeset/orange-birds-brush.md
- examples/oft-solana/README.md
- examples/oft-solana/tasks/common/wire.ts
- examples/oft-solana/tasks/index.ts
- examples/oft-solana/tasks/solana/initConfig.ts
This PR
- rename the hardhat task from `lz:oapp:init:solana` to the more accurate `lz:oft:solana:init-config`
- moves that task to under the `solana` folder and into its own file (keeping to 1 task = 1 file) 
Test transaction calling renamed task: https://solscan.io/tx/H1rJyWk4bsirsycT5cKHfrHfyhwrCSTYrZ6rFD6qs1REAewrSiCGdF6SHzVHA7VPYzNJ9ARK226ustoZVEby8vF?cluster=devnet
> refactor(oft-solana): move to own script and update task name

- .github/workflows/actions/install-dependencies/action.yaml
- docker-compose.yaml
- package.json
`anchor build` runs a rust toolchain build process when run, this creates temp files that it later tries copying in. 
The issue is that we run `pnpm turbo compile` in parallel - this makes it so that we have more than 1 `anchor build` running at the same time. 
These `anchor builds` end up in a state where they each create temporary files (`/root/.rustup/downloads/`) that they want to copy into the "main" rust directory (`/root/.rustup/toolchains/`). This breaks because the first `anchor build` that completes building locks the rustup file as it is now building the solana contracts. During this time the other `anchor build` completes and tries copying its new files into `/root/.rustup/toolchains/` which fails because of the original `anchor build` process. 
This PR pre-builds the rust …
> fix: anchor build has a race condition where it tries building the rust toolchain concurrently across different anchor builds

- .changeset/plenty-fireants-greet.md
- examples/oft-solana/README.md
Fix typo for flag from `--multisigKey` to `--multisig-key`
Ideally, the new section is covered in a docs page. Once that is created, just link to there.
> feat(oft-solana): fix typo and mention how to transfer ownership

- examples/lzapp-migration/layerzero.config.ts
without a value for `maxMessageSize`, the following error appears when running `init-config`:
```
An unexpected error occurred:
Error: Config from file 'layerzero.config.ts' is malformed. Please fix the following errors:
Property 'connections.0.config.sendConfig.executorConfig.maxMessageSize': Expected number, received nan
```
> fix(lzapp-migration): add missing value

- .github/workflows/reusable-publish.yaml
publishing npm packages per architecture does not make sense.
<https://github.com/LayerZero-Labs/devtools/actions/runs/13397572520> tries publishing packages for every architecture
> 🪲no longer push npm packages per architecture

- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .github/workflows/reusable-publish.yaml
- .github/workflows/reusable-test.yaml
- Dockerfile
New base image sets the `default rustup` toolchain version to `1.75.0`
This cleans up some ugly code introduced in the anchor-solana race condition resolution PR https://github.com/LayerZero-Labs/devtools/commit/1edf6d7ec45ce45c996ab2e8ada162f45eda7287 where we manually install `rustc v1.75.0` in a `github action` and `docker-compose.yaml`
> using rustc 1.75.0

- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .github/workflows/reusable-publish.yaml
- .github/workflows/reusable-test.yaml
- Dockerfile
PR <https://github.com/LayerZero-Labs/devtools/pull/1303> was created to cleanup some code introduced in the `solana-anchor` race condition resolution commit <https://github.com/LayerZero-Labs/devtools/commit/1edf6d7ec45ce45c996ab2e8ada162f45eda7287> 
This required rebuilding the images as `Dockerfile` was changed. This PR resets the image tagging from a custom tag `:dockerfile-rustc_1_75_0` created at [run-13402494548](https://github.com/LayerZero-Labs/devtools/actions/runs/13402494548) to `:main` created at [run-13402494548](https://github.com/LayerZero-Labs/devtools/actions/runs/13402494548)
> 🧹 using :main tag for images (3/3)

- .devcontainer/README.md
- .devcontainer/devcontainer.json
- .github/workflows/reusable-publish.yaml
- .github/workflows/reusable-test.yaml
- Dockerfile
Successor PR to <https://github.com/LayerZero-Labs/devtools/pull/1307>. This is the final PR 2/2 of the set of PRs to include `initia` and sets the image tagging to `:main` from `:feat-image_initia`. 
+ For this to work we also run the `Build base development images` job that publishes new images tagged at `:main` for which the run can be found [here](https://github.com/LayerZero-Labs/devtools/actions/runs/13440929537)
+ These images created with the `:main` tag are equivalent to those created by <https://github.com/LayerZero-Labs/devtools/actions/runs/13428552457/job/37515905734> with the tag-hash `: b0c4585cfe86ec57bfec2d28fdd27e4342fcb76a4d634ff60798c8fa0f400903` found [here](https://github.com/LayerZero-Labs/devtools/pkgs/container/devtools-dev-base/359196425?tag=feat-image_initia) 
+ …
> 🗞️ Dockerfile + GitHub Workflow - initiad and initia node (2/2)

- .changeset/small-beans-ring.md
- examples/oft-solana/README.md
- examples/oft-solana/tasks/common/wire.ts
- examples/oft-solana/tasks/solana/index.ts
- examples/oft-solana/tasks/solana/initConfig.ts
lzapp-migration-example will be updated in a separate PR (it also needs its init task to be renamed/refactored)
```
LAYERZERO_EXAMPLES_REPOSITORY_REF=#nazreen/solana-rm-secret-key-flag LZ_ENABLE_SOLANA_OFT_EXAMPLE=1 npx create-lz-oapp@latest
```
> feat(oft-solana): remove need to pass in solana secret key flag

- .changeset/polite-experts-jog.md
- tests/devtools-evm-hardhat-test/test/task/validate.safe.configs.test.ts
Gnosis Safe's url <https://safe-transaction-mainnet.safe.global/> is down.
The url can be found at: 
<https://github.com/safe-global/safe-core-sdk/tree/main/packages/api-kit>
This will be brought back once gnosis safe's apis are live
> 🪲 (temporary patch) - skip gnosis safe test 

- .changeset/dull-chairs-develop.md
- examples/oft-upgradeable/deploy/MyOFTAdapterUpgradeable.ts
- examples/oft-upgradeable/deploy/MyOFTUpgradeable.ts
The old OFT Upgradeable deploy used to assume that the layerzero's internally defined network names founds under `deployments` <https://www.npmjs.com/package/@layerzerolabs/lz-evm-sdk-v2?activeTab=code>  is the same as those defined in `hardhat.config.ts`'s network config. 
This isn't the case as developers can name networks differently. 
Other examples <https://github.com/LayerZero-Labs/devtools/blob/main/examples/oapp/deploy/MyOApp.ts> use this pattern where we load the deployments (`EndpointV2` among others) and artifacts into `Hardhat` in [toolbox-hardhat](https://github.com/LayerZero-Labs/devtools/blob/main/packages/toolbox-hardhat/src/index.ts#L25-L37)
```
// And we check the config for packages from which to import deployments as well
const deploymentSourcePackages = …
```
> 🧹 oft  upgradeable example deploy script

- packages/oft-alt-evm/contracts/OFTAltCore.sol
- packages/oft-alt-evm/test/OFTAlt.t.sol
The current `OFTAltCore::send()` was `payable` to match the interface's definition. However it did not have a revert for when `msg.value != 0`.
This means that users can send transactions to the `OFT` with `{value: msg.value}` which would simply get locked up in the OFT. This PR introduces a custom revert message for when `msg.value != 0`
> 🪲 OFTAltCore reverts if non zero msg value

- packages/oft-hyperliquid-evm/HYPERLIQUID.README.md
- packages/oft-hyperliquid-evm/package.json
- packages/oft-hyperliquid-evm/src/index.ts
- packages/oft-hyperliquid-evm/src/io/env.ts
- packages/oft-hyperliquid-evm/src/io/index.ts
- packages/oft-hyperliquid-evm/src/io/parser.ts
- packages/oft-hyperliquid-evm/src/operations/evmUserModify.ts
- packages/oft-hyperliquid-evm/src/operations/index.ts
- packages/oft-hyperliquid-evm/src/operations/spotDeploy.ts
- packages/oft-hyperliquid-evm/src/signer/index.ts
- packages/oft-hyperliquid-evm/src/signer/signer.ts
- packages/oft-hyperliquid-evm/src/signer/utils.ts
- packages/oft-hyperliquid-evm/src/signer/wallet.ts
- packages/oft-hyperliquid-evm/src/types/constants.ts
- packages/oft-hyperliquid-evm/src/types/index.ts
- packages/oft-hyperliquid-evm/src/types/types.ts
- packages/oft-hyperliquid-evm/tsconfig.json
- packages/oft-hyperliquid-evm/tsup.config.ts
Hyperliquid does not have an official ts-sdk and the community built ones don't support all the L1 actions that we need.
This PR is performs 2x L1 actions that we need 
1. [evmUserModify](https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/evm/dual-block-architecture) to toggle between big and smol blocks 
2. [requestEvmContract](https://hyperliquid.gitbook.io/hyperliquid-docs/for-developers/evm/native-transfers) to link a evm spot with a native spot
> 🗞️ typescript sdk for hyperliquid  

- examples/oft-solana/tasks/common/utils.ts
- examples/oft-solana/tasks/solana/debug.ts
- `lz:oft:solana:debug` now takes in a new param, `dstEids` (csv of dstEid)
- `lz:oft:solana:debug` now recognizes a new action, DEBUG_ACTIONS.GET_PEERS which uses dstEids to fetch the PeerConfig accounts
- PeerConfig Account info are printed
```
LAYERZERO_EXAMPLES_REPOSITORY_REF=#nazreen/oft-solana-debug-dst-eid LZ_ENABLE_SOLANA_OFT_EXAMPLE=1 npx create-lz-oapp@latest
```
Either do an (1) end to end deployment first or (2) use the `--oft-store` param to debug an existing deployment.
(1)
```
npx hardhat lz:oft:solana:debug --eid 40168 --dst-eids 40161,40231     
```
(2)
```
npx hardhat lz:oft:solana:debug --eid 40168 --oft-store HRxaPR51cxfjaCvKQAvkkbYbahu5fbeWMEEJLHFSmNpN --dst-eids 40161,40231     
```
```
OFT Store Information
Owner: 8yQ1LVN632bdqmrdwVJeLZ4Hu4AYcbUxAmvPMGBQRduD
OFT …
```
> 🚀  feat(oft-solana): debug command checks peers

- .changeset/five-drinks-visit.md
- examples/oapp-aptos-move/.eslintrc.js
- examples/oapp-aptos-move/scripts/cli.ts
updating `oapp-aptos` 's `scripts/cli` which was missed in the earlier PR  <https://github.com/LayerZero-Labs/devtools/pull/1355>
> 🧹oapp-aptos-example import path update

- .changeset/shy-monkeys-deny.md
- packages/devtools-extensible-cli/cli/index.ts
- packages/devtools-extensible-cli/index.ts
- packages/devtools-extensible-cli/tsup.config.ts
Otherwise, we would need to import as @layerzerolabs/devtools-extensible-cli/cli in all clients.
> 🪲 exports from devtools-extensible-cli are fixed

- .changeset/selfish-brooms-grin.md
- packages/devtools/src/flows/wire.ts
- packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/index.ts
`pnpm hardhat lz:oapp:wire --oapp-config ./layerzero.config.ts`
Result:  2 Transactions, as is normal.
`pnpm hardhat lz:oapp:wire --oapp-config ./layerzero.config.ts --skip-connections-from-eids 40161`
Result:  Only the Fuji transaction
`pnpm hardhat lz:oapp:wire --oapp-config ./layerzero.config.ts --skip-connections-from-eids 40161,40106`
Result:  No transactions, all connections were filtered.
`pnpm hardhat lz:oapp:wire --oapp-config ./layerzero.config.ts --skip-connections-from-eids 40161,pizza`
Result:  Applies only valid eids in the CSV.
> 🗞️ add "lz:oapp:wire" option to filter out connections from certain eids

- .changeset/early-onions-bathe.md
- packages/devtools/src/omnigraph/builder.ts
Tell users how to actually fix the error instead of being unintentionally vague about what is wrong.
> 🧹 clarify error message

- .changeset/perfect-fishes-move.md
- examples/mint-burn-oft-adapter/package.json
- examples/native-oft-adapter/package.json
- examples/oapp-aptos-move/package.json
- examples/oapp-read/package.json
- examples/oapp/package.json
- examples/oft-adapter-aptos-move/package.json
- examples/oft-adapter/package.json
- examples/oft-aptos-move/package.json
- examples/oft-upgradeable/package.json
- examples/oft/package.json
- examples/onft721-zksync/package.json
- examples/onft721/package.json
- examples/uniswap-read/package.json
- examples/view-pure-read/package.json
- packages/devtools-move/package.json
- pnpm-lock.yaml
- tests/devtools-evm-hardhat-test/package.json
- tests/export-deployments-test/package.json
Many packages depend on `@layerzerolabs/devtools` and `@layerzerolabs/ua-devtools-evm-hardhat` through `@layerzerolabs/toolbox-hardhat`, making upgrades a multi-step process.  As @layerzerolabs/toolbox-hardhat was upgraded here https://github.com/LayerZero-Labs/devtools/pull/1370, we can finally percolate the change to the end consumers.
> 🧹percolate --skip-connections-from-eids to the rest of the project

- .changeset/mean-frogs-lick.md
- packages/metadata-tools/README.md
- packages/metadata-tools/src/config-metadata.ts
- packages/metadata-tools/src/constants.ts
- packages/metadata-tools/src/index.ts
- packages/metadata-tools/src/types.ts
- packages/metadata-tools/test/__snapshots__/config-metadata.test.ts.snap
- packages/metadata-tools/test/config-metadata.test.ts
This PR
- adds a unit test for `generateConnectionsConfig` (added before function was changed)
- adds a new param to `generateConnectionsConfig` (currently only accepts `fetchMetadata` that defaults to `defaultFetchMetadata`)
- creates a `defaultFetchMetadata` function
- extract out the interface `IMetadataDvns` from `IMetadata` for better reusability
- unit test for custom `fetchMetadata` implementation
> 🚀  feat(metadata-tools): allow for custom fetchMetadata implementation

- examples/oft-solana/tasks/common/utils.ts
- examples/oft-solana/tasks/common/wire.ts
- examples/oft-solana/tasks/solana/debug.ts
DebugLogger is not specific to Solana.
To test, run:
```
LAYERZERO_EXAMPLES_REPOSITORY_REF=#refactor-debug-logger-move LZ_ENABLE_SOLANA_OFT_EXAMPLE=1 npx create-lz-oapp@latest
```
Select OFT (Solana)
Then, without needing to deploy anything, you can run the following, to verify that the imports are working.
```
npx hardhat lz:oft:solana:debug --eid 40168 --oft-store 9Ccpw8khitczfmj7ThadPVsrwuvNzSPMeCCrApsXYqBU      
```
If you also want to test for when the logger should output something, then, 
- deploy OFT program
- deploy EVM OFT
- run wire script (deliberately skip init-config)
> 🚀  refactor(oft-solana): move DebugLogger from tasks/solana to tasks/common

- examples/oft-solana/README.md
- examples/oft-solana/layerzero.config.ts
- examples/oft-solana/tasks/common/utils.ts
- examples/oft-solana/tasks/common/wire.ts
- examples/oft-solana/tasks/solana/index.ts
Remove need for manual input of OFT Store in the LZ config. Reduce human error.
will implement custom deployment filename in another PR. currently it's fixed to `OFT.json`
> 🚀 feat(oft-solana): auto-populate oftStore address

- .changeset/unlucky-jeans-eat.md
- packages/devtools-move/tasks/move/utils/moveVMOftConfigOps.ts
Prior to this fix, it was impossible to wire a Solana peer.  This change makes determining the contractAddress more flexible, by reading it from hardhat-deploy deployments for EVM peers and taking it directly from the configuration for Solana peers.  Supporting other blockchains is future work and considered out of scope for this PR.
> 🪲 Fix to allow move OFTs to wire a Solana peer

- examples/oft-solana/tasks/solana/debug.ts
Example output:
```
npx hardhat lz:oft:solana:debug --eid 40168 --oft-store HRxaPR51cxfjaCvKQAvkkbYbahu5fbeWMEEJLHFSmNpN --dst-eids 40161,40231 --action peers
Peer Configurations
send library not initialized, return empty array
40161 (sepolia)
PeerConfig Account: 1eXAQVWf7xW1oPQNxmCED43qSLg1YGcdRKnktqbSUWi
Peer Address: 0xc0941a758e86669fad70fe7ae75ec40995b443da
Enforced Options:
Send: gas: 80_000 , value: 0 wei
SendAndCall: gas: 80_000 , value: 0 wei
Receive Configs (sepolia to solana): 
receiveLibrary: 7a4WjyR8VZ7yZz5XJAKm39BUGn5iT9CKcv2pmG9tdXVH
receiveUlnConfig: 
confirmations: 15
optionalDVNThreshold: 0
requiredDVNs: 4VDjp6XQaxoZf5RGwiPU9NR1EXSZn2TP4ATMmiSzLfhb
optionalDVNs: 
receiveLibraryTimeoutConfig: 
lib: 7a4WjyR8VZ7yZz5XJAKm39BUGn5iT9CKcv2pmG9tdXVH
expiry: 0
Send Configs …
```
> 🚀 feat(oft-solana): enhance debug task to print send and receive configs

- .changeset/warm-candles-judge.md
- packages/oft-evm/test/OFT.t.sol
This is so I can override it in an implementation of the test that uses fees.
> 🧹 make test_quoteOFT virtual

- examples/oft-hyperliquid/deploy/MyHyperliquidComposer.ts
- examples/oft-hyperliquid/deploy/MyHyperliquidOFT.ts
- examples/oft-hyperliquid/test/foundry/ComposerCodec/ComposeMessage.t.sol
- examples/oft-hyperliquid/test/foundry/ComposerCodec/TypeConversion.t.sol
- packages/hyperliquid-composer/src/cli.ts
- packages/hyperliquid-composer/src/commands/register-token.ts
- packages/hyperliquid-composer/src/operations/registerEvmContract.ts
- packages/hyperliquid-composer/src/types/constants.ts
`register-token` used to be a command that would execute 2 hypercore actions `requestEvmContract` and `finalizeEvmContract`. It is possible that the EVM contract and Core Spot are deployed from different accounts, in that event `register-token` would fail as it would run into a `"invalid deployer address"` error. This change introduces
```bash
npx @layerzerolabs/hyperliquid-composer request-evm-contract  --oapp-config <layerzero.config.ts>  --token-index <idx> --network <testnet | mainnet> --private-key $PRIVATE_KEY_HYPERLIQUID_DEPLOYER
```
```bash
npx @layerzerolabs/hyperliquid-composer finalize-evm-contract  --oapp-config <layerzero.config.ts>  --token-index <idx>  --network <testnet | mainnet> --private-key $PRIVATE_KEY_EVM_DEPLOYER
```
using `chainId` instead of network name to …
> 🧹hyperliquid sdk: decompose register-token into request and finalize

- .changeset/quick-flies-grin.md
- .changeset/yellow-suits-approve.md
- .changeset/young-rings-guess.md
- .github/workflows/reusable-test.yaml
- examples/oapp-aptos-move/turbo.json
- examples/oft-adapter-aptos-move/turbo.json
- examples/oft-adapter-initia/turbo.json
- examples/oft-aptos-move/turbo.json
- examples/oft-initia/turbo.json
- packages/devtools-extensible-cli/turbo.json
- packages/devtools-move/tasks/move/utils/config.ts
- packages/devtools-move/turbo.json
- packages/oft-move/package.json
- packages/oft-move/tasks/initOFTFA.ts
- packages/oft-move/turbo.json
- pnpm-lock.yaml
The CI uses a supported version for `0.7.3` [here](https://github.com/LayerZero-Labs/devtools/blob/main/packages/devtools-move/tasks/move/utils/config.ts#L345) but the CI runs at `0.7.2` [here](https://github.com/LayerZero-Labs/devtools/blob/main/Dockerfile#L179). 
This was not caught earlier because `examples/oft-initia` does not include `compile` does not include `compile:initia` and `test` does not include `test:initia`. [compile](https://github.com/LayerZero-Labs/devtools/blob/main/examples/oft-initia/package.json#L7) and [test](https://github.com/LayerZero-Labs/devtools/blob/main/examples/oft-initia/package.json#L37) . 
The PR that introduced `initiad` to devtools - <https://github.com/LayerZero-Labs/devtools/pull/1309>
Initia team told us that they ONLY support local decimals of 6. …
> 🪲 initia fixes for initiad supported version, local decimals, ci

- examples/oft-adapter-initia/package.json
- examples/oft-initia/package.json
Certain examples were missing unit tests and compile for initia
Since aptos and initia use a wrapper to build and test. We need testing for that. Support for this does not exist in devtools-move notably the inclusion of --dev flag
> add initia compile and test

- .changeset/curvy-snails-complain.md
- examples/oft-hyperliquid/HYPERLIQUID.README.md
- packages/hyperliquid-composer/HYPERLIQUID.README.md
Since the composer address needs to be funded it can be done by the user sending in funds (`$1` on `HYPE` or `USDC`) on `HyperCore` or on a `payable constructor` which makes it harder to miss but harder to find an exact value since the value of `HYPE` changes and `USDC` requires the deployer to have some `USDC` in their account and pre-approve to the undeployed address of the composer. 
+ adding warning signs (⚠️) for `notes` to make it more visual
> 🧹hyperliquid - docs update

- .changeset/large-pigs-marry.md
- examples/oft-hyperliquid/HYPERLIQUID.README.md
- package.json
- packages/hyperliquid-composer/HYPERLIQUID.README.md
- packages/hyperliquid-composer/package.json
- packages/hyperliquid-composer/src/cli.ts
- packages/hyperliquid-composer/src/commands/core-spot-deployment.ts
- packages/hyperliquid-composer/src/commands/register-token.ts
- packages/hyperliquid-composer/src/io/parser.ts
- pnpm-lock.yaml
This inclusion caused a requirement where developers needed to execute `npx @layerzerolabs/hyperliquid-composer` scripts from within a hardhat project. This was not required and a user should be able to execute it from anywhere. 
Users may not have `deployment` files as they use their own deploy scripts. As such we prompt developers for the information we need (`oft address` and `oft deployment tx hash`). `oapp-config` made this easier by acting as a point that routes us to the deployment file to extract this information. But since we are decoupled from `deployment` files we no longer are coupled with `oapp-config`.
Updated to match the above changes
So that other developers can test out new changes to `packages/hyperliquid-composer` before publishing the code.
Remove `devDependencies` …
> 🧹improvement: remove hre and oapp-config

- .changeset/red-beds-flash.md
- examples/oft-hyperliquid/HYPERLIQUID.README.md
- examples/oft-hyperliquid/README.md
- examples/oft-hyperliquid/layerzero.config.ts
- packages/hyperliquid-composer/HYPERLIQUID.README.md
- packages/hyperliquid-composer/README.md
Primarily fixing a typo where `--private-key` was called `-private-key` in the docs
> 🧹 hyperliquid docs - fix typo + cleanup

- examples/lzapp-migration/.prettierignore
- examples/mint-burn-oft-adapter/.prettierignore
- examples/native-oft-adapter/.prettierignore
- examples/oapp-aptos-move/.prettierignore
- examples/oapp-read/.prettierignore
- examples/oapp/.prettierignore
- examples/oft-adapter-aptos-move/.prettierignore
- examples/oft-adapter/.prettierignore
- examples/oft-alt/.prettierignore
- examples/oft-aptos-move/.prettierignore
- examples/oft-hyperliquid/.prettierignore
- examples/oft-initia/.prettierignore
- examples/oft-solana/.prettierignore
- examples/oft-upgradeable/.prettierignore
- examples/oft/.prettierignore
- examples/onft721-zksync/.prettierignore
- examples/onft721/.prettierignore
- examples/uniswap-read/.prettierignore
- examples/view-pure-read/.prettierignore
- packages/oft-move/.prettierignore
Several PRs are right now blocked to a prettier check that's impossible to fix. 
The prettier (reported by eslint) error involves needing to move `overrides` in the example `package.json` from a lower line to a higher line. After doing so and re-running CI, it would then error saying it needs to be moved from the higher line to the lower line.
Research and attempts at resolving through other means were unsuccessful. This is happening for all the examples.
Note: I tried to tell eslint to ignore prettier's rules, but then the run of prettier would cause the CI to abort. It's triggered via the `lint:js` script:
```
"lint:js": "eslint '**/*.{js,ts,json}' && prettier --check .",
```
If no better solution is found, we should merge this in to unblock the other PRs.
Why telling prettier to ignore …
> CI: tell prettier to ignore package.json

- examples/lzapp-migration/README.md
- examples/mint-burn-oft-adapter/package.json
- examples/oft-solana/README.md
release.solana.com has been discontinued. Current instructions would lead to an error. 
This PR replaces the domain to release.anza.xyz, the successor
Unrelated change made to fix lint error that's blocking this PR:
```
#
#
#
```
> fix: replace release.solana.com

- examples/lzapp-migration/README.md
- examples/lzapp-migration/deploy/MyLzApp.ts
- examples/lzapp-migration/deploy/MyOApp.ts
- examples/lzapp-migration/layerzero.config.ts
clarifications added to prevent devs from accidentally using MyOApp or LzApp when their intention is to test OFT
> doc(lzapp-migration): fix, add clarifications and warning

- .changeset/tricky-owls-remember.md
- tests/devtools-evm-hardhat-test/test/task/validate.rpcs.test.ts
- tests/devtools-evm-hardhat-test/test/task/validate.safe.configs.test.ts
The test that validate's incorrect wss rpc should return an object with status: 0, it looks like the provider or something has changed the api and it is now returning 
```
{
status: 1,
signal: null,
output: [ null, null, null ],
pid: 2390,
stdout: null,
stderr: null
}
```
signal, output, stdout, stderr being `null` is now used to test this fail case as the rpc should return `null`
also re-enabling a safe test that was disabled earlier due to the safe hack
> 🪲 validate incorrect wss rpc

- examples/lzapp-migration/README.md
- examples/lzapp-migration/tasks/solana/sendOFT.ts
- removes deprecated params from README and task's Args interface
> lzapp-migration: clean up

- .changeset/metal-nails-remain.md
- .changeset/stale-rings-roll.md
- examples/lzapp-migration/tasks/solana/createOFT.ts
- examples/oft-solana/tasks/solana/createOFT.ts
Add a changeset describing the logger helper refactor and export change.
- generated a new changeset marking `io-devtools` and `oft-solana-example` for patch bumps.
- `pnpm changeset` was run to generate the changeset.
> chore: add changeset for logger refactor

- .gitignore
This only affects when examples are run in the monorepo itself - which only affects maintainers' work.
This does not affect examples themselves when inited via the CLI.
> chore: git ignore deployments in examples

- packages/ovault-composer/contracts/ERC20MintBurn.sol
- packages/ovault-composer/contracts/OFTMintBurn.sol
- packages/ovault-composer/contracts/OVault.sol
- packages/ovault-composer/contracts/interfaces/IERC20MintBurnExtension.sol
- packages/ovault-composer/contracts/interfaces/IOVault.sol
- packages/ovault-composer/test/ERC44626.t.sol
- packages/ovault-composer/test/OVault.t.sol
- packages/ovault-composer/test/utils/mocks/MockOFT.sol
- packages/ovault-composer/test/utils/mocks/MockOFTMintBurn.sol
- packages/ovault-composer/test/utils/mocks/MockOVault.sol
`OVault` is the `OApp` version of ERC4626Adapter
The tests use: 
1. `asset` as a `OFT` 
2. `share` as a `OFT` with the `ERC20MintBurnExtension`
Equivalence testing is done against `ERC4626Adapter.t.sol` (which is inturn equivalance tested against Solmate's ERC4626 test)
> feat: converting the ERC20 and ERC4626 into OApps

- packages/ovault-composer/contracts/ERC20MintBurn.sol
- packages/ovault-composer/contracts/ERC4626Adapter.sol
- packages/ovault-composer/contracts/OFTMintBurn.sol
- packages/ovault-composer/contracts/OVault.sol
- packages/ovault-composer/contracts/interfaces/IERC20MintBurnExtension.sol
- packages/ovault-composer/contracts/interfaces/IERC4626Adapter.sol
- packages/ovault-composer/contracts/interfaces/IOVault.sol
- packages/ovault-composer/test/ERC20.t.sol
- packages/ovault-composer/test/ERC44626.t.sol
- packages/ovault-composer/test/OVault.t.sol
- packages/ovault-composer/test/utils/mocks/MockERC20MintBurn.sol
`ERC4626Adapter` now implements ALL functions defined in the `IERC20`
```
function totalSupply() external view returns (uint256);
function balanceOf(address account) external view returns (uint256);
function transfer(address to, uint256 value) external returns (bool);
function allowance(address owner, address spender) external view returns (uint256);
function approve(address spender, uint256 value) external returns (bool);
function transferFrom(address from, address to, uint256 value) external returns (bool);
``` 
Equivalance testing against [solmate's erc20](https://github.com/transmissions11/solmate/blob/main/src/test/ERC20.t.sol) such that the above actions when executed against the share `ERC20` are equivalent to against `ERC4626Adapter` such that the following invariant always stands …
> ovault: erc20 equivalency

- packages/ovault-composer/contracts/OVaultComposer.sol
- packages/ovault-composer/contracts/interfaces/IOVaultComposer.sol
- packages/ovault-composer/test/composer/OVaultComposer_Unit.t.sol
In the case that the target network is the HUB chain then we can't do an `OFT.send` as they aren't self-peered.
In that case we call `OFT.token().transfer()` and also send the user `msg.value` if any.
> fix: dst chain is the hub chain

- packages/ovault-composer/contracts/OVaultComposer.sol
- packages/ovault-composer/contracts/interfaces/IOVaultComposer.sol
- packages/ovault-composer/test/composer/OVaultComposer_Unit.t.sol
Replacing the `quoteSend()` lz check with `oft.peers(dstEid)` since the other things that can go wrong with `quoteSend()` are like 
1. dvn config (protocol issue that should be fixed)
2. rate limiter consumption (temp issue)
3. etc
Since the protocol has peer set for that EID we know that they want to goto that network
> chore: only check if target peer is not set on early exit due to config

- packages/create-lz-oapp/src/examples.json
Using the new `create-lz-oapp` to be compliant with https://github.com/LayerZero-Labs/devtools/pull/1569
> chore: new create-lz-oapp config for example

- .changeset/wet-colts-peel.md
- packages/devtools-move/jest/config.test.ts
- packages/devtools-move/package.json
- packages/devtools-move/tasks/move/utils/config.ts
Based on: https://github.com/LayerZero-Labs/devtools/pull/1592
The version check for the CLI was wrong, as flagged by the original PR creator it was showing that 7.5.0 isn't greater or equal than 6.0.2.
This PR fixes the problem and also adds tests and enables running them in CI.
> INT-406: fix move CLI version checks

- .changeset/tiny-trainers-love.md
- packages/devtools-evm/src/signer/sdk.ts
- packages/devtools-evm/test/signer/sdk.test.ts
So this entire time `LZ_ENABLE_EXPERIMENTAL_BATCHED_SEND` was available which lets users send batch safe txs. 
When testing it out, I ran into issue `Operation DELEGATE_CALL is not allowed`
Quick one liner fix to enforce only Calls and retried everything and it seemed to work: 
Successful multisig batch proposal + signing when running the wire command to update config: https://app.safe.global/transactions/tx?id=multisig_0x1fBd62569885EDc6b757f6C27699F30aB6b0A05a_0x26fd7e96c35a7562ce9d50a85fe16c1419b209858fe90634b0a721c989da2903&safe=bnb:0x1fBd62569885EDc6b757f6C27699F30aB6b0A05a
output when command was run: 
`LZ_ENABLE_EXPERIMENTAL_BATCHED_SEND=1 npx hardhat lz:oapp:wire --oapp-config layerzero.config.ts --safe --log-level debug`
```
 Signing... …
```
> [INT-361]: call is enforced for gnosis safe batch txs

- packages/ovault-evm/contracts/OVaultComposer.sol
- packages/ovault-evm/contracts/interfaces/IOVaultComposer.sol
- packages/ovault-evm/test/composer/OVaultComposer_Unit.t.sol
```
event DecodeFailed(bytes32 indexed guid, address indexed oft, bytes message); // 0xbc772e67
event SendFailed(bytes32 indexed guid, address indexed oft, bytes errMsg); // 0x5feca73a
event OVaultError(bytes32 indexed guid, address indexed oft, bytes errMsg); // 0xc8a2d9e0
event NoPeer(bytes32 indexed guid, address indexed oft, uint32 dstEid); // 0x60e5ac46
event FailedToSendEther(address indexed receiver, uint256 amount, bytes errMsg); // 0xb7da4a55
event lzComposeInFailedState(bytes4 indexed failEventSelector, bytes errMsg) // 0x6875e033
```
emitting `lzComposeInFailedState(bytes4,bytes)`
where `bytes4` part is the event signature and `bytes` is whatever is received from the external call as part of the `try..catch`
> ovault - standardize event emitted during entry of failed state in lzCompose 

- examples/oapp-solana/programs/my_oapp/src/instructions/send.rs
- examples/oapp-solana/programs/my_oapp/src/lib.rs
LzReceiveTypes PDA has the Store as the seed, not the peer.
> oapp-solana: fix comment

- .changeset/dull-dolphins-share.md
- packages/devtools/src/transactions/signer.ts
- packages/devtools/test/transactions/signer.test.ts
When using the LZ_ENABLE_EXPERIMENTAL_BATCHED_SEND feature flag, it will batch all txs together, even if there are 100s of transactions. This can result in exceeding gas limits and reverting, so in practice, users have only been using this feature flag when they are expecting about 7 transactions at once.
Example Queue: https://app.safe.global/transactions/queue?safe=bnb:0x1fBd62569885EDc6b757f6C27699F30aB6b0A05a
Command ran:
`LZ_BATCH_SIZE=2 LZ_ENABLE_EXPERIMENTAL_BATCHED_SEND=1 npx hardhat lz:oapp:wire --oapp-config layerzero.config.ts --safe --log-level debug`
Output:
```
verbose: [signAndSendFlow] Sending the transactions
debug:   [sign & send] Signing 6 transactions
warn:    [sign & send] You are using experimental batched transaction sending
debug:   [sign & send] Signing 3 …
```
> [INT-454] Add chunking of safe multisig batching + LZ_BATCH_SIZE

- .changeset/slimy-dancers-flash.md
- examples/oapp-aptos-move/Move.toml
- examples/oft-adapter-aptos-move/Move.toml
- examples/oft-aptos-move/Move.toml
`aptos-framework`'s latest commit from the `mainnet` branch can introduce breaking changes, as such the branch `mainnet@latest` only supports `aptos-cli v7` and breaks on older `aptos-cli` versions. We use `aptos-cli v6` (6.0.1) 
Using `aptos-framework`'s branch mainnnet @ latest` breaks our CLI and local builds:
https://github.com/LayerZero-Labs/devtools/actions/runs/16329839557/job/46214753285#step:8:2786
Our tooling was testing heavily in February of this year, which is why we're commit-tagging at Feb 4 <https://github.com/aptos-labs/aptos-framework/commit/99f5e915b6d231d0ffbc1aff282d36148d2a8b24>
> Aptos framework rev patch

- .github/workflows/auto-approve-layerzero-bot.yaml
Version Package PRs should not require 2 approvals. This can slow down developers that merge a PR and then wait on another approval to bump packages.
This PR introduces a new github action that auto approves (1 time) PRs from @layerzero-bot  (our version package author).
1. The action ONLY approves when the author is `layerzero-bot` 
2. The action ONLY approves when ALL the files changes are in this allowed list:
- `**/package.json`
- `**/pnpm-lock.yaml`
- `**/.changeset/**`
- `**/CHANGELOG.md`
- `.changeset/**`
3. It creates a SINGLE approval for the PR
4. It leaves a comment on the PR to track the approval
5. A failed auto-approve WILL NOT block 2 human approvals from merging the PR
6. The passing of this action is NOT required for the PR to be merged
> feat: new action to auto approve version packages PRs from layerzero-bot

- .changeset/happy-bottles-cover.md
- packages/oft-evm/contracts/OFTCore.sol
- packages/oft-evm/contracts/interfaces/IOFT.sol
- packages/oft-evm/test/OFT.t.sol
**File: `packages/oft-evm/contracts/OFTCore.sol`**
- **Enhanced `_toSD()` function** with SafeCast overflow protection
- **Before**: `return uint64(_amountLD / decimalConversionRate);` - Silent truncation on overflow
- **After**: `return (_amountLD / decimalConversionRate).toUint64();` - Explicit revert on overflow
- **Prevents silent overflow**: Large amounts that exceed uint64 limits now revert with clear error messages instead of being silently truncated
- **Stops loss of funds when overriding shared decimals**: Incorrect shared decimal usage previously would overflow and trigger a cross-chain message that burnt funds on source chain, but delivered the truncated value. This fixes that problem by reverting on source send.
**File: `packages/oft-evm/test/OFT.t.sol`**
Updated fuzzing …
> DEVREL-608 fix: uint64 casting in _toSD

- packages/ovault-evm/contracts/VaultComposerSync.sol
- packages/ovault-evm/contracts/interfaces/IVaultComposerSync.sol
- packages/ovault-evm/test/vault-sync/VaultComposerSync_ProxySend.t.sol
Adding in `_from` as the "sender" in `quoteSend(_from, ...oldArgs)`
Updated interface and tests. 
`quoteSend()` also checks if the `vaultInAmout` can be deposited or redeemed by checking it against `maxDeposit()` OR `maxRedeem()`
> Ovault - audit paladin

- .changeset/moody-ears-smile.md
- examples/oft-solana/tasks/common/wire.ts
- packages/protocol-devtools-solana/src/uln302/schema.ts
- packages/ua-devtools-solana/src/oft/sdk.ts
Fixes DEVREL-658
Deploying Solana OFTs were encountering errors during the configuration process:
```
Error: Unable to find defaultSendLibraryConfig/sendLibraryConfig account at xxx/xxxx
```
**Workaround**: Downgrading to `@layerzerolabs/lz-solana-sdk-v2@3.0.114` temporarily resolved the issue, but this was not a sustainable solution as it affected all deploying Solana OFTs.
The issue was introduced in version 3.0.115 and was related to the transaction execution order in the devtools wiring process:
1. This caused the `getSendLibrary` call to fail when the required PDA accounts didn't exist
2. The `initSendLibrary` and `initReceiveLibrary` operations were only happening during `setPeer`, but library initialization shouldn't depend on peers being set
The issue was exposed by a **breaking …
> DEVREL-658 Fix Solana OFT initialization to prevent configuration failures

- .dockerignore
- Dockerfile
upgrading
rustc to 1.84.1
solana to 2.2.20
anchor to 0.31.1
platform-tools to 1.48
evm node no longer cares about solana
enabling parallel compilation on rust 
reducing layers by combining some
> feat: solana ci upgrade

- .changeset/pink-coins-fix.md
- examples/ovault-evm/script/DebugSendScript.sol
composeMsg is `abi.encode(SendParam, uint256 minMsgValue)` where `minMsgValue` is the `composeValue`
> fix: composeMsg in debug send script

- .changeset/pink-coins-fix.md
- examples/ovault-evm/script/DebugSendScript.sol
`composeMsg` is `abi.encode(SendParam, uint256 minMsgValue)` where `minMsgValue` is the `composeValue`
> ovault - update send script

- .github/workflows/reusable-test.yaml
Unconditionally skip lockfile validation on CI until we have time to implement a fix. This affects version bumping
> fix: temporarily skip lockfile validation

- .changeset/clean-ants-worry.md
- packages/ua-devtools-solana/src/oft/sdk.ts
- only call .initNonce on Endpoint if the Nonce Account does not yet exist
Using Arbitrum Sepolia (40231) <> Solana Devnet (40168)
To reproduce, I call .initNonce on the Endpoint before calling the wire task.
Txn that calls initNonce for the OApp + Peer combination before wiring task: https://solscan.io/tx/4MwquJFevRtVyvs9kS52SvTTwDnNu6d8t7rCAGpc4HkfSbgCd6Ko1dZ9EaCartVgub3diiNdnZkFb1mjYW2Mjh25?cluster=devnet
Running the wire task before patching devtools, I can reproduce the error:
```
Error: Simulation failed.
Message: Transaction simulation failed: Error processing Instruction 3: custom program error: 0x0.
Logs:
[
"Program log: Instruction: SetPeerConfig",
"Program H9j9Wp46t7GyDSU3NVV8AmYMdXZHoiZmAzVuDSVDY2jy consumed 9516 of 979896 compute units",
"Program …
```
> DEVREL-807 check nonce account existence in setPeer call

- examples/native-oft-adapter/.eslintrc.js
- turbo.json
> fix: ci build step after linting
