LayerZero-Labs/devtools

packages/devtools-evm-hardhat/CHANGELOG.md
packages/devtools-evm/CHANGELOG.md
packages/devtools/CHANGELOG.md
packages/omnicounter-devtools-evm/CHANGELOG.md
packages/omnicounter-devtools/CHANGELOG.md
packages/protocol-devtools-evm/CHANGELOG.md
packages/protocol-devtools/CHANGELOG.md
packages/toolbox-hardhat/CHANGELOG.md
packages/ua-devtools-evm-hardhat/CHANGELOG.md
packages/ua-devtools-evm/CHANGELOG.md
packages/ua-devtools/CHANGELOG.md

- Update versions in `CHANGELOG.md` after bumping minor versions

🚧 Update versions in CHANGELOG.md files

---

.changeset/giant-icons-bake.md
packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.check.ts
tests/ua-devtools-evm-hardhat-test/test/task/oapp/__data__/configs/valid.multi.network.config.connected.js
tests/ua-devtools-evm-hardhat-test/test/task/oapp/__data__/configs/valid.multi.network.config.missing.connection.js
tests/ua-devtools-evm-hardhat-test/test/task/oapp/__data__/configs/valid.multi.network.config.one.connection.js
tests/ua-devtools-evm-hardhat-test/test/task/oapp/__snapshots__/config.check.test.ts.snap
tests/ua-devtools-evm-hardhat-test/test/task/oapp/config.check.test.ts

- Updating `lz:oapp:config:check` task to printout a table of connected OApp peers

👷‍♂️⛏️Update checkWire task to printout table of connected peers

---

.changeset/little-jobs-pump.md
packages/ua-devtools/src/oapp/schema.ts
packages/ua-devtools/src/oapp/types.ts

- Updating Enforced Options Schema to handle EndpointV2 specific options in layerzero.config

🪲Updating Enforced Options Schema

---

.changeset/long-walls-push.md
packages/build-lz-options/README.md
packages/build-lz-options/src/utilities/prompts.ts

- Fixes to the `README` of `build-lz-options`
- Small wording change to the prompt that asks whether we want to keep adding options

🪲 Wording fixes for build-lz-options

---

.github/ISSUE_TEMPLATE/feature_request.md

- Add a new template for feature requests

🧹 Add feature request template

---

README.md

- Update the `README` after adding the `lz:deploy` hardhat task

🧹 Update README

---

tests/ua-devtools-evm-hardhat-test/tasks/index.ts

Adds a task to deploy OmniCounter locally.

🪚 Add a task to deploy OmniCounter locally

---

packages/create-lz-oapp/README.md

- Miniature README fixes for `create-lz-oapp`. I didn't even make a changeset since it's not quite worth publishing on its own - the writer's issue here will be to come up with a structure for docs that does not duplicate much but allows the users to clearly know what to do and where to get more info

🧹 Miniature README fixes

---

.changeset/mighty-chicken-give.md
examples/oapp/README.md
examples/oapp/hardhat.config.ts
examples/oft/README.md
examples/oft/hardhat.config.ts
packages/create-lz-oapp/src/config.ts

-Update a couple of the hardhat config network rpcs, as existing ones were not working
-Provide instructions in example readmes to provide and fund their deployer address

🗞️ Update dotenv to access .env mnemonic, example rpcs

---

.changeset/sweet-knives-divide.md
packages/ua-devtools/src/oapp/config.ts
packages/ua-devtools/src/oapp/schema.ts
packages/ua-devtools/src/oapp/types.ts
tests/ua-devtools-evm-hardhat-test/test/oapp/config.test.ts

- Adding missing optionType that allows you to configure enforcedOptions by (destEid -> msgType -> options)

🪲Adding optionType to enforcedOptions config

---

packages/devtools-evm-hardhat/src/tasks/deploy.ts
packages/ua-devtools-evm-hardhat/src/constants/tasks.ts
packages/ua-devtools-evm-hardhat/src/tasks/errors/decode.ts
packages/ua-devtools-evm-hardhat/src/tasks/errors/list.ts
packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.check.ts
packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.default.ts
packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.executor.ts
packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.ts
packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.init.ts
packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/index.ts
packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/subtask.configure.ts

- The first step towards composable hardhat tasks that allow us, amongst others, to support custom configuration 
- The functional bits that we want to allow users to modify will be isolated into subtasks that:
- Allow users to execute custom logic after a subtask is executed
- Allow users to modify the subtask without rewriting the whole task

🗞️ Task composability [1/N]

---

.changeset/dull-suits-drive.md
packages/devtools-evm-hardhat/src/constants/tasks.ts
packages/devtools-evm-hardhat/src/tasks/index.ts
packages/devtools-evm-hardhat/src/tasks/subtask.sign-and-send.ts
packages/devtools-evm-hardhat/src/tasks/transactions/index.ts
packages/devtools-evm-hardhat/src/tasks/transactions/subtask.sign-and-send.ts
packages/ua-devtools-evm-hardhat/src/tasks/index.ts
packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/index.ts
packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/subtask.configure.ts

- Move the sign & send logic into a subtask so that it can be both reused & modified by users

🗞️ Move sign & send logic into a subtask

---

.devcontainer/devcontainer.json
Dockerfile

- Add a simple VS Code Devcontainer for seamless containerized local development. Learn more about Devcontainers [here](https://code.visualstudio.com/docs/devcontainers/containers)

🗞️ Simple devcontainer

---

.devcontainer/devcontainer.json

- Adding common extensions to the devcontainer (prettiers, syntax highlighters, markdown viewers etc etc)

🧹 Add common extensions to the devcontainer

---

.github/workflows/reusable-test.yaml

- Use a new shiny large runner for both tests & user tests

🧹 Use large runners

---

.changeset/eight-hounds-bow.md
packages/toolbox-hardhat/README.md

- Adding in documentation for layerzero.config

🧹 Adding in documentation for layerzero.config

---

.changeset/popular-socks-deliver.md
packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.ts

- Fix a small typo in a hardhat task description

🪲 Fix a typo in a task description

---

examples/oapp/package.json
examples/oft/package.json

- Adding resolutions for `@openzeppelin/contracts-upgradeable` to example projects

🪲 Add resolutions to examples

---

.changeset/dull-shrimps-visit.md

- #430 was missing a changeset, adding it now

🪲 Missing changeset for package update

---

.changeset/silly-yaks-design.md
packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/index.ts

Provide missing changeset for version bump.

🧹 Provide changeset for the TestHelperOz5.sol updates

---

README.md

Using relative links instead of hardcoded github urls

🪲 Use relative links

---

packages/build-lz-options/jest.config.js
packages/create-lz-oapp/jest.config.js
packages/devtools-evm-hardhat/jest.config.js
packages/devtools-evm/jest.config.js
packages/devtools/jest.config.js
packages/export-deployments/jest.config.js
packages/io-devtools/jest.config.js
packages/omnicounter-devtools-evm/jest.config.js
packages/omnicounter-devtools/jest.config.js
packages/protocol-devtools-evm/jest.config.js
packages/protocol-devtools/jest.config.js
packages/toolbox-hardhat/jest.config.js
packages/ua-devtools-evm-hardhat/jest.config.js
packages/ua-devtools-evm/jest.config.js
packages/ua-devtools/jest.config.js
packages/verify-contract/jest.config.js
tests/devtools-evm-hardhat-test/jest.config.js
tests/devtools-evm-test/jest.config.js
tests/export-deployments-test/jest.config.js
tests/ua-devtools-evm-hardhat-test/jest.config.js
tests/ua-devtools-evm-hardhat-v1-test/jest.config.js

- Turns out that `summary` reporter is not really good for local testing, using `default` instead

🪲 Use default reporter instead of summary

---

.changeset/mean-crabs-rhyme.md

Updated Pragma for floating, vs fixed

🧹 Add changeset for updated EndpointV2Mock.sol

---

.changeset/nasty-pillows-film.md
packages/devtools-evm/src/simulation/anvil.ts
packages/devtools-evm/test/simulation/anvil.test.ts

- Tiny PR related to the simulation epic - adding [`stateInterval`](https://book.getfoundry.sh/reference/cli/anvil) option

🗞️ Add stateInterval to anvil options [5/N]

---

.changeset/brown-zebras-battle.md
packages/devtools-evm/src/simulation/anvil.ts
packages/devtools-evm/test/simulation/anvil.test.ts

- Adding more simulation-specific properties to `AnvilOptions`

🗞️ Add forkBlockNumber, retries & timeout to AnvilOptions [6/N]

---

.github/workflows/reusable-publish-docker.yaml

- Build the base image for both arm & amd

🧹 Build multi-platform base docker images

---

.changeset/quick-cameras-kneel.md
packages/protocol-devtools-evm/src/endpointv2/sdk.ts
packages/protocol-devtools/src/endpointv2/types.ts
packages/ua-devtools-evm/src/oapp/sdk.ts
packages/ua-devtools/src/oapp/config.ts
packages/ua-devtools/src/oapp/schema.ts
packages/ua-devtools/src/oapp/types.ts
tests/ua-devtools-evm-hardhat-test/test/oapp/config.test.ts

- Adding `delegate` optional configuration field to `OAppOmniGraph`

🗞️ Add delegate configuration

---

.changeset/popular-countries-roll.md
packages/toolbox-hardhat/types/index.d.ts

- Add more type exports to `toolbox-hardhat` for developer convenience

🗞️ Add more type exports to toolbox-hardhat

---

CHEATSHEET.md

- @lzBryan pointed out hat there are some errors in our `CHEATSHEET`, this fixes them

🪲 Fix wrong cheats

---

.changeset/small-walls-turn.md
packages/devtools-evm-hardhat/src/omnigraph/coordinates.ts

- Fix an issue where hardhat deploy would not find any deployments when search by address

🪲 Fix a problem with missing deployments

---

EXPERIMENTAL.md

- Fix a typo in `EXPERIMENTAL.md`

🪲 FIx experimental readme

---

packages/test-devtools-evm-hardhat/contracts/mocks/EndpointV2Mock.sol

chore: remove repetitive words

---

packages/io-devtools/src/swag/README.md

chore: fix typo

---

README.md
examples/oft/README.md

PR to merge README changes to update OFT guide

Updated OFT guide in README

---

.changeset/tame-mugs-count.md
packages/devtools-evm/src/signer/sdk.ts
packages/devtools-evm/test/signer/sdk.test.ts

- Add `nonce` coming from `getNextNonce` when proposing transactions to gnosis

🪲 Use `getNextNonce` when proposing transactions to safe

---

.changeset/brave-days-vanish.md
EXPERIMENTAL.md
packages/devtools-evm/src/signer/sdk.ts
packages/devtools-evm/test/signer/sdk.test.ts
packages/devtools/src/transactions/signer.ts
packages/devtools/src/transactions/types.ts
packages/devtools/test/transactions/signer.test.ts

- Add support for batched transaction sending under `LZ_ENABLE_EXPERIMENTAL_BATCHED_SEND ` feature flag

🗞️ Batched transaction sending for Gnosis Safe

---

.changeset/pretty-suits-enjoy.md
EXPERIMENTAL.md
packages/devtools/src/common/retry.ts
packages/devtools/test/common/retry.test.ts

- `AsyncRetriable` is now enabled by default

🧹 Make retry a stable feature

---

examples/oapp/test/hardhat/MyOApp.test.ts

**In this PR**
- fixing message in quote parameters to match subsequent send parameters to resolve https://github.com/LayerZero-Labs/devtools/issues/625

🐛 Issue-625 Fix test message

---

packages/ua-devtools/src/oapp/config.ts

- Refactored `configureOAppPeers` in `ua-devtools > src > oapp > config.ts` to use `createConfigureEdges` pattern and added more logging

🧹 Refactoring configureOAppPeers

---

packages/ua-devtools/src/oapp/config.ts

- Refactored `configureReceiveLibraryTimeouts` in `ua-devtools > src > oapp > config.ts` to use `createConfigureEdges` pattern and added logging

🧹 Refactoring configureReceiveLibraryTimeouts

---

.changeset/two-bags-wash.md
packages/ua-devtools/src/oapp/config.ts

- Refactored `configureReceiveLibraries` in `ua-devtools > src > oapp > config.ts` to use `createConfigureEdges` pattern and added logging

🧹 Refactoring configureReceiveLibraries

---

.changeset/lemon-brooms-watch.md
packages/ua-devtools/src/oapp/config.ts

- Added logging to `configureReceiveConfig` in `ua-devtools > src > oapp > config.ts`

🧹 Adding logging to configureReceiveConfig

---

.changeset/three-chicken-brake.md
packages/ua-devtools/src/oapp/config.ts

- Added logging to `configureEnforcedOptions` in `ua-devtools > src > oapp > config.ts`

🧹 Adding logging to configureEnforcedOptions

---

.changeset/swift-goats-wink.md
packages/ua-devtools-evm/package.json
packages/ua-devtools-evm/src/erc20/factory.ts
packages/ua-devtools-evm/src/erc20/index.ts
packages/ua-devtools-evm/src/erc20/sdk.ts
packages/ua-devtools-evm/src/erc20/types.ts
packages/ua-devtools-evm/src/index.ts
packages/ua-devtools-evm/test/erc20/sdk.test.ts
pnpm-lock.yaml

- Add a basic ERC20 SDK (mostly read methods) to `ua-devtools-evm`

🗞️ ERC20 SDK

---

.changeset/wild-ants-walk.md

- Configure `delegate` on the `OApp` before  configuring everything else

🧹 Configure OApp delegates before configuring the rest

---

.changeset/loud-suns-mate.md
examples/oapp/foundry.toml
examples/oapp/hardhat.config.ts
examples/oapp/test/foundry/MyOApp.t.sol
examples/oft/foundry.toml
examples/oft/hardhat.config.ts
examples/onft721/foundry.toml
examples/onft721/hardhat.config.ts
examples/onft721/package.json

- Add a dummy forge test for OApp example
- Fix cache paths for examples so that hardhat and forge don't overwrite each other's cache

🪲 Fix problem with missing forge tests in OApp example; Fix cache paths for examples

---

.changeset/light-cups-begin.md
packages/ua-devtools/src/oapp/config.ts

- The original PR's bulk has been rebased away #652 so this PR recreates its contents

🧹 Configure OApp delegates before configuring anything else

---

pnpm-lock.yaml
tests/export-deployments-test/hardhat.config.ts
tests/export-deployments-test/package.json

- Small fix found while working on #700 - using the network setup utility in one of the test packages

🧹 Use network setup utility in @layerzerolabs/export-deployments-test

---

.changeset/selfish-tables-shout.md
packages/ua-devtools/src/oapp/schema.ts

- Add missing `OAppOmniGraphSchema` to `ua-devtools`

🧹 CLI: Add missing schema [3/N]

---

packages/devtools-evm/src/provider/types.ts
packages/devtools-solana/.eslintignore
packages/devtools-solana/.eslintrc.json
packages/devtools-solana/.prettierignore
packages/devtools-solana/README.md
packages/devtools-solana/jest.config.js
packages/devtools-solana/jest.setup.js
packages/devtools-solana/package.json
packages/devtools-solana/src/connection/factory.ts
packages/devtools-solana/src/connection/index.ts
packages/devtools-solana/src/connection/types.ts
packages/devtools-solana/src/index.ts
packages/devtools-solana/src/omnigraph/index.ts
packages/devtools-solana/src/omnigraph/sdk.ts
packages/devtools-solana/src/omnigraph/types.ts
packages/devtools-solana/test/connection/factory.test.ts
packages/devtools-solana/tsconfig.json
packages/devtools-solana/tsup.config.ts
packages/devtools/src/types.ts
pnpm-lock.yaml

- Add a stub of `@layerzerolabs/devtools-solana` with generic Solana utilities

🗞️ Add devtools-solana package

---

.changeset/shy-papayas-rule.md
packages/verify-contract/src/common/url.ts

🧹 Add Sei api url

---

.changeset/cool-rockets-divide.md

- Add a forgotten changeset for `devtools-solana`

🪲 Solana: Forgotten changeset [19/N]

---

.changeset/thirty-falcons-stare.md
packages/protocol-devtools-solana/src/endpointv2/sdk.ts
packages/ua-devtools-solana/src/oft/sdk.ts
packages/ua-devtools-solana/test/oft/sdk.test.ts

- Add delegate getters/setters on the `OFT` and the underlying `EndpointV2` SDKs

🗞️ Solana: Add getters/setters for delegates [26/N]

---

.github/workflows/reusable-test.yaml
docker-compose.yaml
packages/protocol-devtools-solana/test/endpointv2/sdk.test.ts
packages/ua-devtools-solana/test/oft/sdk.test.ts

- Provided we have good RPCs available for Solana, we can enable the Solana tests in the CI

🧹 Solana: Enable tests on the CI [29/N]

---

.changeset/sharp-ladybugs-occur.md
packages/ua-devtools-solana/src/oft/sdk.ts
packages/ua-devtools-solana/test/oft/sdk.test.ts

- Add owner getters/setters to Solana OFT SDK

🗞️ Solana: Add owner getters/setters to OFT SDK [28/N]

---

.changeset/clean-bugs-clap.md
packages/ua-devtools/src/oapp/config.ts

- Show more logs when configuring OApp with the default log level

🧹 Update log levels in OApp configuration to give more user feedback with the default log level

---

.changeset/witty-singers-do.md
examples/oft-solana/tasks/solana/createOFT.ts
examples/oft-solana/tasks/solana/createOFTAdapter.ts
examples/oft-solana/tasks/solana/mintTo.ts
examples/oft-solana/tasks/solana/sendOFT.ts
examples/oft-solana/tasks/solana/setFreezeAuthority.ts
examples/oft-solana/tasks/solana/setMetadataAuthority.ts
examples/oft-solana/tasks/solana/setOFTMintAuthority.ts
examples/oft-solana/tasks/solana/setRateLimit.ts

- `bs58` does not support destructuring imports, hence the fix

🪲 Fix imports of bs58

---

.changeset/wicked-dingos-design.md
examples/oft-solana/package.json
packages/devtools-solana/package.json
packages/devtools-solana/src/transactions/signer.ts
packages/devtools-solana/test/transactions/signer.test.ts
pnpm-lock.yaml

- Stub of `OmniSigner` implementation for Solana. At the moment the signer is purely for preview purposes and should not be used in production apps

🗞️ Solana: Stub of Squads OmniSigner

---

.changeset/shy-frogs-mate.md
examples/oft-solana/.env.example
examples/oft-solana/README.md
examples/oft-solana/tasks/solana/createOFT.ts
examples/oft-solana/tasks/solana/createOFTAdapter.ts
examples/oft-solana/tasks/solana/mintTo.ts
examples/oft-solana/tasks/solana/sendOFT.ts
examples/oft-solana/tasks/solana/setFreezeAuthority.ts
examples/oft-solana/tasks/solana/setOFTMintAuthority.ts
examples/oft-solana/tasks/solana/setRateLimit.ts
examples/oft-solana/tasks/utils/getFee.ts
packages/devtools-cli/src/commands/oapp/wire/index.ts
packages/devtools-cli/src/setup/typescript.ts

current commands don't work out of the box if you try to deploy solana oft on solana devnet

🪲 Fix solana devnet oft deploy commands

---

docker-compose.registry.yaml

- When #826 is merged and base image built, we can run the user tests in parallel

🧹 Parallelize user tests

---

packages/oft-evm/contracts/NativeOFTAdapter.sol

- Added call data to `CreditFailed` error to help with debugging 
- See conversation [here](https://github.com/LayerZero-Labs/devtools/pull/838#discussion_r1738895442)

Improve error messaging

---

examples/oft-solana-v2/package.json
examples/oft-solana-v2/programs/oft/src/instructions/quote_send.rs
examples/oft-solana-v2/programs/oft/src/lib.rs
examples/oft-solana-v2/programs/oft/src/state/peer_config.rs
examples/oft-solana-v2/tasks/common/wire.ts
pnpm-lock.yaml

OS-SFT-ADV-00 (LOW): `compute_fee_and_adjust_amount` incorrectly applies `remove_dust` to the `amount_sent_ld`, potentially resulting in the sent amount being less than required.
OS-SFT-SUG-00: Suggestion to utilize saturating math to prevent any possibility of overflows in `RateLimiter:refill`.

fix: auditor feedback

---

.changeset/shaggy-actors-call.md
packages/oft-evm/contracts/NativeOFTAdapter.sol
packages/oft-evm/contracts/OFTCore.sol
packages/oft-evm/contracts/interfaces/IOFT.sol
packages/oft-evm/test/OFT.t.sol
packages/oft-evm/test/lib/NativeOFTAdapterMockCodec.sol
packages/oft-evm/test/mocks/NativeOFTAdapterMock.sol

- Implemented `NativeOFTAdapter` with tests

🗞️ Native OFT Adapter

---

.changeset/rich-berries-film.md
examples/oft-solana/tasks/solana/createOFT.ts
examples/oft-solana/tasks/solana/createOFTAdapter.ts

Fixed, tested e2e here:
https://testnet.layerzeroscan.com/tx/0x298949b6b65ae4f190214f91c9cfee0cacf996530dfbb60b318501885e750413
https://testnet.layerzeroscan.com/tx/5V6iPiQ4Suj6gnsuQSiBftL2RYWw3zF4LxSBrT5HYMYgaNoCJXx5pvntmAy427zGXJTjpK6daR7UYVa22mxDpQDV

🪲 allow amount=0 for createOFT

---

.github/workflows/actions/setup-build-cache/action.yaml

- Improve the fallbacks for build cache (exact match -> branch match -> PR base match -> default branch match -> anything else)

🧹 Better build cache

---

.github/workflows/reusable-publish-docker.yaml
Dockerfile

- Add Solana local node targets to the `Dockerfile`
- Add CI jobs to build & push the Solana local node images to GHCR

🗞️ Solana local node image

---

.changeset/stupid-zebras-collect.md
packages/ua-devtools-evm-hardhat/package.json
packages/ua-devtools-evm-hardhat/src/oapp/typescript/typescript.ts
packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.default.ts
packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.executor.ts
packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.ts
packages/ua-devtools-evm-hardhat/src/utils/taskHelpers.ts
packages/ua-devtools-evm-hardhat/tsconfig.json

- Another PR towards hardhat-independent implementations of the config getter tasks

🧹 Clean up implementations for config getter tasks

---

verdaccio.yaml

- Update verdaccio proxy rules with the (relatively) newly added packages

🪲 Verdaccio proxy rules

---

.changeset/angry-mayflies-grab.md
examples/oft-solana/tasks/common/wire.ts
packages/ua-devtools-solana/src/oft/sdk.ts

🪲 squads multisig support

---

.changeset/large-wombats-film.md
packages/devtools-solana/package.json
packages/devtools-solana/src/transactions/signer.ts
packages/devtools-solana/tsconfig.json
pnpm-lock.yaml

The client we were importing was specifically for squads3, when we are targetting squads4.

🪲 squads client

---

.changeset/tiny-peas-shake.md
packages/devtools-evm-hardhat/package.json
pnpm-lock.yaml

https://github.com/stargate-protocol/stargate-v2/pull/171#discussion_r1850841717

🧹 Updating devtools dependency for devtools-evm-hardhat

---

examples/oft-solana/README.md
examples/oft-solana/layerzero.config.ts
packages/devtools-evm-hardhat/src/tasks/deploy.ts
packages/ua-devtools-evm-hardhat/src/tasks/errors/decode.ts
packages/ua-devtools-evm-hardhat/src/tasks/errors/list.ts

- use collapsible for script that gets solana private key in base58
- oftStore address instruction as own heading
- mention options
- fix typo in log message when deploying
- explainer on enforcedOptions and extraOptions

docs(oft-solana): various improvements

---

examples/oft-solana/tasks/solana/createOFT.ts

I have tested this by deploying a Solana Devnet OFT with 5 shared decimals and 5 local decimals and OFT on Fuji with 18 local decimals and 5 shared decimals.
Example OFT creation command:
```
npx hardhat lz:oft:solana:create --eid 40168 --program-id u4y44AKRE9i4eRzCqD8Vfz9ikaePBCZs2XthXBG5x77 --local-decimals 5 --shared-decimals 5 --additional-minters Fty7h4FYAN7z8yjqaJExMHXbUoJYMcRjWYmggSxLbHp8
```
Fuji OFT with 5 shared decimals: https://testnet.snowtrace.io/address/0xD907A226556763bFE0A9b08C27A5294456373558/contract/43113/code
Solana token with 5 decimals: https://explorer.solana.com/address/5ttqPygkz9sBNZKsaWPB3ycEJuehUf91fmMoJjkdb6Ux?cluster=devnet
Solana Devnet deployment:
```
{
"programId": "u4y44AKRE9i4eRzCqD8Vfz9ikaePBCZs2XthXBG5x77",
"mint": …
```

add ability to define shared decimals during Solana OFT creation

---

examples/oft-solana/tasks/solana/createOFT.ts
examples/oft-solana/tasks/solana/multisig.ts
examples/oft-solana/tasks/solana/utils.ts

Ensure that the multisig is ready to be used prior to continuing onwards.

🪲 race condition in token_mint / multisig creation

---

.changeset/brown-candles-sort.md

Publishes new packages that centralize on most up to date dependencies.

🧹 bump web3 dependencies changeset

---

.changeset/brave-buckets-approve.md
packages/oft-evm/contracts/MintBurnOFTAdapter.sol
packages/oft-evm/contracts/interfaces/IMintableBurnable.sol
packages/oft-evm/test/mocks/ElevatedMinterBurnerMock.sol
packages/oft-evm/test/mocks/MintBurnERC20Mock.sol

- update licenses for MintBurnOFTAdapter
- add comments to mocks to reflect examples

🧹 Fix license in oft-evm for MintBurnOFTAdapter and periphery

---

.changeset/clean-ads-pump.md

This is not yet tested, do not merge.

update to the latest forge-std version

---

examples/oft-solana/tasks/solana/index.ts

- Solscan has a much better UI for viewing transactions and accounts

feat(oft-solana): change explorer from solana labs explorer to solscan

---

examples/oft-solana/layerzero.config.ts

- add commented out import line that's needed when commented out enforcedOptions are uncommented
- link to Simple Config Generator
- link to docs page on Options

docs(oft-solana): add commented out import and other comments

---

packages/devtools-move/tasks/evm/utils/types.ts
packages/devtools-move/tasks/evm/wire/setEnforcedOptions.ts
packages/devtools-move/tasks/evm/wire/transactionExecutor.ts

1. using latest run to make it easier to trace through transactions
2. fix: combining enforced options

fix - combine enforced options into a single transactions

---

packages/devtools-move/tasks/evm/utils/validateOmnicontracts.ts

1. `validateEidSupport()` had a bug where the badEid push can occur into an undefined record index. 
2. replace `eid` with `fromEid` which makes more sense

fix: accumulation of badEids inits key with fromEid in the record

---

.changeset/little-papayas-breathe.md
examples/oft-solana/tasks/solana/createOFT.ts

similar to https://github.com/LayerZero-Labs/devtools/pull/1260

fix:(oft-solana): fix import

---

.github/workflows/actions/setup-build-cache/action.yaml

bringing back architecture specific hardhat cache

Cache/bring back hardhat caching 

---

examples/oft-upgradeable/contracts/MyOFTAdapterUpgradeable.sol
examples/oft-upgradeable/contracts/MyOFTUpgradeable.sol
examples/oft-upgradeable/test/foundry/MyOFTUpgradeable.sol
examples/oft-upgradeable/test/foundry/MyOFTUpgradeable.t.sol
packages/oft-evm-upgradeable/test/OFT.t.sol

- add disableInitializers to oft and oft adapter upgradeable
- fix foundry compilation warnings in OFT.t.sol by adding view keyword

improve initialization logic in upgradeable oft

---

examples/lzapp-migration/tasks/solana/createOFT.ts
examples/oft-solana/README.md
examples/oft-solana/tasks/solana/createOFT.ts

provide clearer guidance for when devs bring their own token

feat: clearer instructions for MABA mode

---

README.md
examples/lzapp-migration/README.md
examples/mint-burn-oft-adapter/README.md
examples/native-oft-adapter/README.md
examples/oapp-read/README.md
examples/oapp/README.md
examples/oft-adapter/README.md
examples/oft-upgradeable/README.md
examples/oft/README.md
examples/onft721-zksync/README.md
examples/onft721/README.md
examples/uniswap-read/README.md

update community link

---

Dockerfile

`Dockerfile` currently runs `LD_LIBRARY_PATH="/root/.initia/lib:$LD_LIBRARY_PATH"` however this doesn't load `libmovevm` into `ldconfig` which is linux's dynamic linker cache. 
```
$ ldconfig -p | grep libmovevm
$     
```
^ note there are no lines printed 
`RUN echo "/root/.initia/lib" > /etc/ld.so.conf.d/initia.conf && ldconfig` is the fix that loads it into the cache and now running `ldconfig -p | grep libmovevm` works as expected 
```
$ ldconfig -p | grep libmovevm
libmovevm.x86_64.so (libc6,AArch64) => /root/.initia/lib/libmovevm.x86_64.so
libmovevm.aarch64.so (libc6,AArch64) => /root/.initia/lib/libmovevm.aarch64.so
```
+ replace `$HOME` with `/root/` to be consistent with the rest of `Dockerfile` (`$HOME` = `/root/` in our environment)

🪲ldconfig in ci needs to be set

---

examples/oft-solana/README.md

accidentally left this in, needs removing now

chore(oft-solana): remove deprecated flag

---

.github/workflows/reusable-test.yaml

increasing jest timeout as this may help with ton tests failing

🗞️ increase jest timeout in reusable-test.yaml

---

.changeset/pink-chairs-double.md
packages/create-lz-oapp/README.md
packages/create-lz-oapp/src/config.ts

Fixes https://github.com/LayerZero-Labs/devtools/issues/1324

disable yarn

---

examples/oft-solana/README.md

update `anchor build` instruction to use the env var flag `-e` for passing in `OFT_ID`

feat(oft-solana): update build instruction to use env var

---

examples/oft-solana/tasks/solana/debug.ts

To test, run:
```
LAYERZERO_EXAMPLES_REPOSITORY_REF=#nazreen/solana-debug LZ_ENABLE_SOLANA_OFT_EXAMPLE=1 npx create-lz-oapp@latest
```
Select `OFT (Solana)`
building on top of #1327
Changes
- unifies debugging for Solana OFTs under one task with the possibility of narrowing down by debug action name
- adds Token Mint/Freeze Authority prints
- adds a 'Checks' section
- filters OFT Store information to most relevant ones
Sample run and output:
```
reviews/solana-debug $ npx hardhat lz:oft:solana:debug --eid 40168 --oft-store 9Ccpw8khitczfmj7ThadPVsrwuvNzSPMeCCrApsXYqBU                                                                 
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
(node:74546) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. …
```

feat(oft-solana): unified debug task

---

packages/devtools-move/tasks/evm/utils/anvilForkNode.ts

This PR enhances the `AnvilForkNode` class to provide more robust error handling and port detection:
1. **Fixed port checking logic** to properly detect when ports are already in use
- Improved the `checkFreePort` method to correctly handle server events
- Added proper port binding to 127.0.0.1
2. **Enhanced error handling for Anvil process startup**
- Added proper error detection through stderr capture
- Improved error propagation to fail fast when Anvil can't start
- Simplified stdio configuration to only capture necessary streams
3. **Improved error propagation**
- Errors during node startup are now properly propagated up the call stack
- This ensures the application fails with clear error messages when something goes wrong
Tested by verifying:
- Have anvil running. Test wire on oft
- …

Improve Anvil Fork Node Error Handling and Port Detection

---

.changeset/tall-lies-attack.md

https://github.com/LayerZero-Labs/devtools/actions/runs/13721444529/job/38378819325#step:9:31

🪲changeset was incorrect

---

.changeset/sharp-doors-remember.md

bump package to publish new contracts added in https://github.com/LayerZero-Labs/devtools/pull/1283

bump oft-evm-upgradeable to publish oft fee

---

.changeset/dry-coats-unite.md
packages/metadata-tools/src/config-metadata.ts
packages/metadata-tools/test/__snapshots__/config-metadata.test.ts.snap
packages/metadata-tools/test/config-metadata.test.ts

which bug is it? idk. including both.

🐞 🐛  fix (metadata-tools): fix generateConnectionsConfig would error when called with no params

---

packages/metadata-tools/README.md

Current example was lacking elaboration.

📜  metadata-tools: elaborate readme

---

.changeset/lemon-monkeys-smile.md
examples/oft-adapter-initia/README.md
examples/oft-initia/README.md
examples/oft-initia/deploy-move/OFTInitParams.ts
examples/oft-initia/move.layerzero.config.ts
packages/devtools-move/sdk/IOFT.ts
packages/devtools-move/sdk/initiaOFT.ts
packages/devtools-move/tasks/move/transferObjectOwner.ts
packages/devtools-move/tasks/move/utils/moveVMOftConfigOps.ts
packages/devtools-move/tasks/move/utils/utils.ts

docs: update Initia README for key management and add multi-sig instructions; refactor OFTInitParams and IOFT to support multi-sig args

Initia Multisig Export support

---

Dockerfile

`transiton` and `utilit` are included but not valid english words.

Fix two typos in `Dockerfile`

---

.changeset/neat-bugs-drum.md
examples/oft-adapter-initia/README.md
examples/oft-initia/README.md

simplify object ownership validation instructions

Update README for Initia OApp

---

packages/hyperliquid-composer/HYPERLIQUID.README.md

Added in usage for the `hyperliquid-composer` sdk to:
- fetch core spot information from hyperliquid
- create a deployment file for the core spot
- deploy a core spot without hyperliquidity
- link the OFT with the Core Asset
Added in explanation for working on the composer
Update hyperliquid information regarding core spot, decimals, asset bridge.

🗞️ hyperliquid - docs 

---

packages/hyperliquid-composer/HYPERLIQUID.README.md

Resolving feedback from Luke based on his google doc

🧹hyperliquid docs update

---

.changeset/young-bobcats-accept.md
packages/hyperliquid-composer/package.json
pnpm-lock.yaml

Moving devDeps to deps so that the the required packages are installed during npx `@layerzerolabs/hyperliquid-composer`

🧹 hyperliquid - update dependecies

---

.changeset/fifty-insects-know.md
examples/oapp-aptos-move/Move.toml
examples/oapp-aptos-move/move.layerzero.config.ts
examples/oapp-aptos-move/package.json
examples/oft-adapter-aptos-move/Move.toml
examples/oft-adapter-aptos-move/move.layerzero.config.ts
examples/oft-adapter-aptos-move/package.json
examples/oft-aptos-move/Move.toml
examples/oft-aptos-move/move.layerzero.config.ts
examples/oft-aptos-move/package.json

Adjusting the examples to support aptos out of the box rather than movement

🧹 Cleanup aptos-move examples for accelerator demo

---

examples/lzapp-migration/README.md
examples/oft-solana/README.md

update priority fee deployment instructions in README to reference docs site
let's keep things DRY

docs: priority fee snippets reference docs site instead

---

packages/hyperliquid-composer/contracts/HyperLiquidComposer.sol
packages/hyperliquid-composer/contracts/HyperLiquidComposerCore.sol
packages/hyperliquid-composer/contracts/interfaces/IHyperLiquidComposerCore.sol
packages/hyperliquid-composer/contracts/interfaces/IHyperLiquidComposerErrors.sol
packages/hyperliquid-composer/test/HyperLiquidComposerRevert.t.sol

Adding in a min gas check since composeMsg do not have enforced options

hyperliquid composer - ottersec

---

packages/ovault-evm/.env.example
packages/ovault-evm/.gitignore
packages/ovault-evm/README.md
packages/ovault-evm/package.json
packages/ovault-evm/src/contracts/ERC20.ts
packages/ovault-evm/src/contracts/ERC4626.ts
packages/ovault-evm/src/contracts/OFT.ts
packages/ovault-evm/src/contracts/OVaultComposerSync.ts
packages/ovault-evm/src/index.ts
packages/ovault-evm/src/oVaultSync/index.ts
packages/ovault-evm/src/oVaultSync/tracking.ts
packages/ovault-evm/src/oVaultSync/transfer.ts
packages/ovault-evm/src/types.ts
packages/ovault-evm/test/sdk/tracker.test.ts
packages/ovault-evm/test/sdk/transfer.test.ts
packages/ovault-evm/tsconfig.json
packages/ovault-evm/tsconfig.test.json
pnpm-lock.yaml

Moving https://github.com/LayerZero-Labs/lz-ovault-sdk into package to be part of `@layerzerolabs/ovault-evm`

ovault - port sdk to package/ovault-evm
